SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "As-tu déjà vu le PARC SAFARI\n"
	.string "à PARMANIE?\p"
	.string "On y trouve plein de POKéMON\n"
	.string "rares!$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Mon pôpa et moi, on pense que le\n"
	.string "PARC SAFARI il est génial!$"

