CeladonCity_Condominiums_1F_Frlg_MapScripts::
	.byte 0

CeladonCity_Condominiums_1F_EventScript_TeaWoman::
	lock
	faceplayer
	goto_if_set FLAG_TALKED_TO_TEA_LADY_AFTER_HOF, CeladonCity_Condominiums_1F_EventScript_TeaWomanAfterTea
	goto_if_set FLAG_SYS_GAME_CLEAR, CeladonCity_Condominiums_1F_EventScript_TeaWomanMentionDaisy
	goto_if_set FLAG_GOT_TEA, CeladonCity_Condominiums_1F_EventScript_TeaWomanAfterTea
	msgbox CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead
	setflag FLAG_GOT_TEA
	giveitem ITEM_TEA
	goto_if_eq VAR_RESULT, FALSE, EventScript_BagIsFull
	msgbox CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea
	release
	end

CeladonCity_Condominiums_1F_EventScript_TeaWomanAfterTea::
	msgbox CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany
	release
	end

CeladonCity_Condominiums_1F_EventScript_TeaWomanMentionDaisy::
	famechecker FAMECHECKER_DAISY, 4
	setflag FLAG_TALKED_TO_TEA_LADY_AFTER_HOF
	msgbox CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea
	release
	end

CeladonCity_Condominiums_1F_EventScript_Meowth::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MEOWTH, CRY_MODE_NORMAL
	msgbox CeladonCity_Condominiums_1F_Text_Meowth
	waitmoncry
	release
	end

CeladonCity_Condominiums_1F_EventScript_Clefairy::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_CLEFAIRY, CRY_MODE_NORMAL
	msgbox CeladonCity_Condominiums_1F_Text_Clefairy
	waitmoncry
	release
	end

CeladonCity_Condominiums_1F_EventScript_Nidoran::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_NIDORAN_F, CRY_MODE_NORMAL
	msgbox CeladonCity_Condominiums_1F_Text_Nidoran
	waitmoncry
	release
	end

CeladonCity_Condominiums_1F_EventScript_SuiteSign::
	msgbox CeladonCity_Condominiums_1F_Text_ManagersSuite, MSGBOX_SIGN
	end

CeladonCity_Condominiums_1F_Text_Meowth::
	.string "MIAOUSS: Miaou!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
	.string "Tu devrais pas dépenser tout\n"
	.string "ton argent dans les boissons.\p"
	.string "Essaie-ça à la place.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
	.string "Contre la soif, il n'y a rien de\n"
	.string "mieux que le THE.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
	.string "Mes chers POKéMON me tiennent\n"
	.string "compagnie.\p"
	.string "MIAOUSS rapporte même\n"
	.string "de l'argent!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
	.string "Oh, bonjour poussin.\n"
	.string "As-tu aimé mon THE?\p"
	.string "Au fait, ne viendrais-tu pas de\n"
	.string "BOURG PALETTE par hasard?\p"
	.string "Je connais une fille qui vient \n"
	.string "aussi de cette ville, NINA.\p"
	.string "Elle boit du THE tous les jours.\p"
	.string "Elle va souvent au CENTRE\n"
	.string "COMMERCIAL pour en acheter.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
	.string "MELOFEE: Féé! Fééééféééé!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
	.string "NIDORAN♀: Nido! Nidoodoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
	.string "MANOIR CELADON\n"
	.string "Suite présidentielle$"

