SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
	.string "Tu ne saurais pas quelque chose\n"
	.string "sur cette grotte par hasard?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
	.string "Je ne m'y attendais pas. Mais tu\n"
	.string "aurais pu y aller plus doucement.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
	.string "Les RUINES TANOBY sont vieilles\n"
	.string "d'au moins 1 500 ans.\p"
	.string "Mais personne ne sait à quoi elles\n"
	.string "pouvaient servir.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
	.string "On raconte qu'un POKéMON mystique\n"
	.string "se repose ici.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
	.string "Je ne suis pas vraiment doué\n"
	.string "pour le combat.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
	.string "J'ai entendu dire qu'il y aurait\n"
	.string "d'autres ruines.\p"
	.string "Se pourrait-il que d'autres POKéMON\n"
	.string "mystiques s'y reposent?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
	.string "Je prends des cours avec XAVIER\n"
	.string "pour apprendre à peindre.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
	.string "Chut, on devrait faire moins de\n"
	.string "bruit ici.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
	.string "Comme je voulais peindre un \n"
	.string "vieil immeuble, \p"
	.string "XAVIER m'a amenée ici.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
	.string "On est venus ici aujourd'hui\n"
	.string "pour les travaux pratiques.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
	.string "Quel talent!$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
	.string "Oh, alors tu étudies les POKéMON\n"
	.string "de ton côté…\p"
	.string "Tu dois vraiment être quelqu'un\n"
	.string "de très intéressant, je pense.$"
