OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Les jours ensoleillés, je fais de\n"
	.string "grandes balades autour du volcan.$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Voyons voir. De quand date la\n"
	.string "dernière éruption du MONT BRAISE?$"

