SixIsland_RuinValley_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, SixIsland_RuinValley_OnLoad
	.byte 0

SixIsland_RuinValley_OnLoad::
	call_if_set FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE, SixIsland_RuinValley_EventScript_OpenDottedHoleDoor
	end

SixIsland_RuinValley_EventScript_OpenDottedHoleDoor::
	setmetatile 24, 24, METATILE_SeviiIslands67_DottedHoleDoor_Open, 0
	return

SixIsland_RuinValley_EventScript_Scientist::
	lock
	msgbox SixIsland_RuinValley_Text_CantFigureOutHowToGetInside
	applymovement LOCALID_RUIN_VALLEY_SCIENTIST, Common_Movement_FacePlayer
	waitmovement 0
	msgbox SixIsland_RuinValley_Text_IFoundThisPlace
	applymovement LOCALID_RUIN_VALLEY_SCIENTIST, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

SixIsland_RuinValley_EventScript_DottedHoleDoor::
	lockall
	goto_if_set FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE, SixIsland_RuinValley_EventScript_DottedHoleDoorOpen
	msgbox SixIsland_RuinValley_Text_CheckDoorMoreThoroughly, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, SixIsland_RuinValley_EventScript_IgnoreDottedHoleDoor
	msgbox SixIsland_RuinValley_Text_SeveralDotsOnTheDoor
	braillemsgbox Braille_Text_Cut
	releaseall
	end

SixIsland_RuinValley_EventScript_DottedHoleDoorOpen::
	msgbox SixIsland_RuinValley_Text_DoorIsOpen
	releaseall
	end

SixIsland_RuinValley_EventScript_IgnoreDottedHoleDoor::
	msgbox SixIsland_RuinValley_Text_LeftDoorAlone
	releaseall
	end

SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
	.string "Je ne vois pas ce que je dois\n"
	.string "faire pour entrer dedans.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
	.string "C'est moi qui ai trouvé cet endroit.\n"
	.string "Pas de jalousie, d'accord?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
	.string "La porte ne bouge pas d'un pouce.\n"
	.string "L'examiner plus attentivement?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
	.string "{PLAYER} s'éloigne de la porte.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
	.string "En regardant de plus près, on peut\n"
	.string "voir plusieurs points sur la porte.$"

SixIsland_RuinValley_Text_DoorIsOpen::
	.string "La porte est ouverte.$"

SixIsland_RuinValley_Text_StanlyIntro::
	.string "Plusieurs énigmes semblent ne pas\n"
	.string "avoir été élucidées ici.$"

SixIsland_RuinValley_Text_StanlyDefeat::
	.string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
	.string "J'ai un conseil à te donner. Pense\n"
	.string "aux énigmes et secrets de ce monde\p"
	.string "au moins une fois par jour.$"

SixIsland_RuinValley_Text_FosterIntro::
	.string "Je suis curieux, qu'est-ce qui a\n"
	.string "bien pu t'amener ici?$"

SixIsland_RuinValley_Text_FosterDefeat::
	.string "Ça faisait longtemps que je ne\n"
	.string "m'étais pas battu.\p"
	.string "Mes instincts sont un peu rouillés.$"

SixIsland_RuinValley_Text_FosterPostBattle::
	.string "Il y a plusieurs ruines sur les\n"
	.string "ILES SEVII.\p"
	.string "La majorité d'entre elles date\n"
	.string "de milliers d'années.$"

SixIsland_RuinValley_Text_LarryIntro::
	.string "On raconte qu'il y a des pierres\n"
	.string "mystérieuses sur cette île.\p"
	.string "Je pense qu'elles ont un rapport\n"
	.string "avec ces ruines.$"

SixIsland_RuinValley_Text_LarryDefeat::
	.string "Oh, intéressant.$"

SixIsland_RuinValley_Text_LarryPostBattle::
	.string "A propos de ces ruines…\p"
	.string "Je n'ai jamais trouvé le moyen\n"
	.string "d'y pénétrer.$"

SixIsland_RuinValley_Text_DarylIntro::
	.string "Un combat avec toi, c'est parti!$"

SixIsland_RuinValley_Text_DarylDefeat::
	.string "Oh, ça me casse le moral d'avoir\n"
	.string "perdu si facilement contre toi.$"

SixIsland_RuinValley_Text_DarylPostBattle::
	.string "A nous les joies de l'escalade!$"

SixIsland_RuinValley_Text_HectorIntro::
	.string "Je connais bien le coin et ses\n"
	.string "mystères.$"

SixIsland_RuinValley_Text_HectorDefeat::
	.string "Le prends pas comme ça, je vais\n"
	.string "parler, c'est bon.$"

SixIsland_RuinValley_Text_HectorPostBattle::
	.string "La porte de ces ruines…\n"
	.string "Il y a des formes étranges dessus.\p"
	.string "Mais bon, je sais pas ce que ça\n"
	.string "veut dire.$"
