Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
	.string "T'as des POKéMON avec toi!\n"
	.string "En garde!$"

Route9_Text_AliciaDefeat::
	.string "Ah!\n"
	.string "Bien défendu!$"

Route9_Text_AliciaPostBattle::
	.string "On n'y voit rien du tout dans ce\n"
	.string "tunnel.\p"
	.string "Il te faudrait FLASH pour le\n"
	.string "traverser.$"

Route9_Text_ChrisIntro::
	.string "Mais qui voilà, les bras chargés de\n"
	.string "POKéMON?$"

Route9_Text_ChrisDefeat::
	.string "Paf!\n"
	.string "J'suis fini!$"

Route9_Text_ChrisPostBattle::
	.string "Passe ton chemin!$"

Route9_Text_DrewIntro::
	.string "Je passe par la GROTTE pour\n"
	.string "aller à LAVANVILLE!$"

Route9_Text_DrewDefeat::
	.string "…\n"
	.string "J'suis pas bon!$"

Route9_Text_DrewPostBattle::
	.string "Tu vas dans la GROTTE, toi aussi?$"

Route9_Text_CaitlinIntro::
	.string "Traite-moi avec respect!$"

Route9_Text_CaitlinDefeat::
	.string "…\n"
	.string "Je ne mérite que ton dédain!$"

Route9_Text_CaitlinPostBattle::
	.string "Tu iras loin!\n"
	.string "Bonne chance à toi!$"

Route9_Text_JeremyIntro::
	.string "Bwahaha! Allez…\n"
	.string "Viens prendre ta pâtée…$"

Route9_Text_JeremyDefeat::
	.string "Ha!\n"
	.string "Viens, viens!\p"
	.string "Heu, j'ai plus de POKéMON!$"

Route9_Text_JeremyPostBattle::
	.string "T'as du courage, toi!$"

Route9_Text_BriceIntro::
	.string "Hahaha!\n"
	.string "T'as l'air coriace, toi!$"

Route9_Text_BriceDefeat::
	.string "Dur, très dur!$"

Route9_Text_BricePostBattle::
	.string "Les gosses, c'est pas assez fort!$"

Route9_Text_BrentIntro::
	.string "Mes cocons de POKéMON me\n"
	.string "prennent beaucoup de temps!$"

Route9_Text_BrentDefeat::
	.string "Nyargh?\p"
	.string "Quelle perte de temps!$"

Route9_Text_BrentPostBattle::
	.string "Il me faut autre chose que\n"
	.string "des insectes pour être plus fort…$"

Route9_Text_AlanIntro::
	.string "Viens t'battre, si tu oses!$"

Route9_Text_AlanDefeat::
	.string "Ha!\n"
	.string "Tu m'as bien eu!$"

Route9_Text_AlanPostBattle::
	.string "Hahahaha!\n"
	.string "Quand j'perds, j'me marre!$"

Route9_Text_ConnerIntro::
	.string "En avant mes POKéMON INSECTE!$"

Route9_Text_ConnerDefeat::
	.string "Mes POKéMON!$"

Route9_Text_ConnerPostBattle::
	.string "T'aimes pas les POKéMON INSECTE?\n"
	.string "T'es pas chouette!$"

Route9_Text_RouteSign::
	.string "ROUTE 9\n"
	.string "AZURIA - GROTTE$"

