Route21_South_Frlg_MapScripts::
	.byte 0

Route21_South_Text_JackIntro::
	.string "J'ai attrapé tous mes POKéMON\n"
	.string "dans l'eau!$"

Route21_South_Text_JackDefeat::
	.string "Splash!$"

Route21_South_Text_JackPostBattle::
	.string "Mais où as-tu attrapé autant de\n"
	.string "POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Hop là!\n"
	.string "J'suis en plein triathlon!$"

Route21_South_Text_JeromeDefeat::
	.string "Nyan…\n"
	.string "J'ai perdu le rythme…$"

Route21_South_Text_JeromePostBattle::
	.string "Tu m'as battu! Mais le marathon\n"
	.string "a pas encore commencé!$"

Route21_South_Text_RolandIntro::
	.string "Ah! Le ciel, le soleil et la mer!$"

Route21_South_Text_RolandDefeat::
	.string "Woh!\n"
	.string "J'ai perdu!$"

Route21_South_Text_RolandPostBattle::
	.string "J'ai des coups de soleil!$"

Route21_South_Text_ClaudeIntro::
	.string "Va-t-en, tu m'fais peur!$"

Route21_South_Text_ClaudeDefeat::
	.string "Heu!\n"
	.string "J'le ferai plus!$"

Route21_South_Text_ClaudePostBattle::
	.string "J'étais énervé de n'avoir rien\n"
	.string "attrapé.$"

Route21_South_Text_NolanIntro::
	.string "Reste donc avec moi, le temps\n"
	.string "d'avoir une touche!$"

Route21_South_Text_NolanDefeat::
	.string "Argh!\n"
	.string "Perte de temps!$"

Route21_South_Text_NolanPostBattle::
	.string "Attends!\n"
	.string "J'ai une touche!$"

Route21_North_Text_LilIntro::
	.string "LY: Hein? Tu veux te battre?\n"
	.string "IAN, on y va!$"

Route21_North_Text_LilDefeat::
	.string "LY: Oh, tu vois? On a perdu!\n"
	.string "T'es content?$"

Route21_North_Text_LilPostBattle::
	.string "LY: j'suis épuisée. On va rentrer\n"
	.string "à la maison.$"

Route21_North_Text_LilNotEnoughMons::
	.string "LY: Hein? Tu veux te battre?\p"
	.string "Je me bats qu'avec mon frère.\n"
	.string "Reviens avec deux POKéMON.$"

Route21_North_Text_IanIntro::
	.string "IAN: Je coache ma sœur pour \n"
	.string "qu'elle fasse du sport.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Aaaah. Il va falloir\n"
	.string "s'entraîner un peu plus.$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Allez sœurette! C'est pas\n"
	.string "comme ça que tu vas maigrir!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: On veut se battre en combat\n"
	.string "deux contre deux.\p"
	.string "Alors reviens avec deux POKéMON.$"
