FuchsiaCity_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, FuchsiaCity_OnTransition
	.byte 0

FuchsiaCity_OnTransition::
	setworldmapflag FLAG_WORLD_MAP_FUCHSIA_CITY
	call_if_set FLAG_GOT_DOME_FOSSIL, FuchsiaCity_EventScript_SetOmanyteGfx
	call_if_unset FLAG_GOT_DOME_FOSSIL, FuchsiaCity_EventScript_SetKabutoGfx
	end

FuchsiaCity_EventScript_SetOmanyteGfx::
	setvar VAR_OBJ_GFX_ID_0, OBJ_EVENT_GFX_OMANYTE
	return

FuchsiaCity_EventScript_SetKabutoGfx::
	setvar VAR_OBJ_GFX_ID_0, OBJ_EVENT_GFX_KABUTO
	return

FuchsiaCity_EventScript_LittleBoy::
	msgbox FuchsiaCity_Text_DidYouTrySafariGame, MSGBOX_NPC
	end

FuchsiaCity_EventScript_OldMan::
	msgbox FuchsiaCity_Text_SafariZoneZooInFront, MSGBOX_NPC
	end

FuchsiaCity_EventScript_Erik::
	msgbox FuchsiaCity_Text_WheresSara, MSGBOX_NPC
	end

FuchsiaCity_EventScript_Youngster::
	msgbox FuchsiaCity_Text_ItemBallInThere, MSGBOX_NPC
	end

FuchsiaCity_EventScript_Lass::
	lock
	faceplayer
	famechecker FAMECHECKER_KOGA, 3
	msgbox FuchsiaCity_Text_MyFatherIsGymLeader
	release
	end

FuchsiaCity_EventScript_CitySign::
	msgbox FuchsiaCity_Text_CitySign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariZoneSign::
	msgbox FuchsiaCity_Text_SafariZoneSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariGameSign::
	msgbox FuchsiaCity_Text_SafariGameSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_WardensHomeSign::
	msgbox FuchsiaCity_Text_WardensHomeSign, MSGBOX_SIGN
	end

@ Unused
FuchsiaCity_EventScript_SafariZoneOfficeSign::
	msgbox FuchsiaCity_Text_SafariZoneOfficeSign, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_GymSign::
	lockall
	famechecker FAMECHECKER_KOGA, 0
	msgbox FuchsiaCity_Text_GymSign
	releaseall
	end

FuchsiaCity_EventScript_ChanseySign::
	lockall
	setvar VAR_0x8004, SPECIES_CHANSEY
	special SetSeenMon
	showmonpic SPECIES_CHANSEY, 10, 3
	msgbox FuchsiaCity_Text_ChanseySign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_VoltorbSign::
	lockall
	setvar VAR_0x8004, SPECIES_VOLTORB
	special SetSeenMon
	showmonpic SPECIES_VOLTORB, 10, 3
	msgbox FuchsiaCity_Text_VoltorbSign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_KangaskhanSign::
	lockall
	setvar VAR_0x8004, SPECIES_KANGASKHAN
	special SetSeenMon
	showmonpic SPECIES_KANGASKHAN, 10, 3
	msgbox FuchsiaCity_Text_KangaskhanSign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_SlowpokeSign::
	lockall
	setvar VAR_0x8004, SPECIES_SLOWPOKE
	special SetSeenMon
	showmonpic SPECIES_SLOWPOKE, 10, 3
	msgbox FuchsiaCity_Text_SlowpokeSign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_LaprasSign::
	lockall
	setvar VAR_0x8004, SPECIES_LAPRAS
	special SetSeenMon
	showmonpic SPECIES_LAPRAS, 10, 3
	msgbox FuchsiaCity_Text_LaprasSign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_FossilMonSign::
	lockall
	goto_if_set FLAG_GOT_DOME_FOSSIL, FuchsiaCity_EventScript_OmanyteSign
	setvar VAR_0x8004, SPECIES_KABUTO
	special SetSeenMon
	showmonpic SPECIES_KABUTO, 10, 3
	msgbox FuchsiaCity_Text_KabutoSign
	hidemonpic
	releaseall
	end

FuchsiaCity_EventScript_OmanyteSign::
	setvar VAR_0x8004, SPECIES_OMANYTE
	special SetSeenMon
	showmonpic SPECIES_OMANYTE, 10, 3
	msgbox FuchsiaCity_Text_OmanyteSign
	hidemonpic
	releaseall
	end

FuchsiaCity_Text_DidYouTrySafariGame::
	.string "Connais-tu le jeu du SAFARI?\p"
	.string "Certains POKéMON n'apparaissent\n"
	.string "qu'à cet endroit.$"

FuchsiaCity_Text_SafariZoneZooInFront::
	.string "Il y a un zoo devant l'entrée du\n"
	.string "PARC SAFARI.\p"
	.string "Le jeu du SAFARI permet d'attraper\n"
	.string "des POKéMON.$"

FuchsiaCity_Text_WheresSara::
	.string "NICO: Mais où est JULIA? Elle est\n"
	.string "tout l'temps en retard.$"

FuchsiaCity_Text_ItemBallInThere::
	.string "Cette BALL, mais…\n"
	.string "Oh, c'est un POKéMON!$"

FuchsiaCity_Text_CitySign::
	.string "PARMANIE\n"
	.string "Rose comme la passion$"

FuchsiaCity_Text_SafariZoneSign::
	.string "LE PARADIS DES POKéMON\n"
	.string "PARC SAFARI$"

FuchsiaCity_Text_SafariGameSign::
	.string "JEU SAFARI\n"
	.string "Attrape-les tous!$"

FuchsiaCity_Text_WardensHomeSign::
	.string "PARC SAFARI\n"
	.string "MAISON DU GARDIEN$"

FuchsiaCity_Text_SafariZoneOfficeSign::
	.string "LE PARADIS DES\n"
	.string "POKéMON \p"
	.string "Bienvenue au PARC SAFARI$"

FuchsiaCity_Text_GymSign::
	.string "ARENE POKéMON de PARMANIE \n"
	.string "CHAMPION: KOGA\l"
	.string "Le ninja aux poisons redoutables$"

FuchsiaCity_Text_ChanseySign::
	.string "Nom: LEVEINARD\p"
	.string "Il faut une chance incroyable\n"
	.string "pour en capturer un.$"

FuchsiaCity_Text_VoltorbSign::
	.string "Nom: VOLTORBE\p"
	.string "Portrait craché d'une POKé BALL.$"

FuchsiaCity_Text_KangaskhanSign::
	.string "Nom: KANGOUREX\p"
	.string "Ce POKéMON élève son petit dans sa\n"
	.string "poche ventrale.$"

FuchsiaCity_Text_SlowpokeSign::
	.string "Nom: RAMOLOSS\p"
	.string "Sympa mais très lent!$"

FuchsiaCity_Text_LaprasSign::
	.string "Nom: LOKHLASS\p"
	.string "Le roi des mers.$"

FuchsiaCity_Text_OmanyteSign::
	.string "Nom: AMONITA\p"
	.string "Un POKéMON créé à partir\n"
	.string "d'un fossile.$"

FuchsiaCity_Text_KabutoSign::
	.string "Nom: KABUTO\p"
	.string "Un POKéMON créé à partir\n"
	.string "d'un fossile.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
	.string "……$"

Text_SubstituteTeach::
	.string "J'aimerais tellement être un bébé\n"
	.string "KANGOUREX.\p"
	.string "Si je pouvais, je me clonerais\n"
	.string "juste pour rester dans la\p"
	.string "poche confortable d'un\n"
	.string "KANGOUREX.\p"
	.string "Mais seuls les POKéMON peuvent\n"
	.string "utiliser CLONAGE…\p"
	.string "Tu veux que j'apprenne CLONAGE\n"
	.string "à un de tes POKéMON?$"

Text_SubstituteDeclined::
	.string "Oh, vraiment?\p"
	.string "Dommage, le CLONAGE a\n"
	.string "l'air sympa.$"

Text_SubstituteWhichMon::
	.string "A quel POKéMON enseigner\n"
	.string "CLONAGE?$"

Text_SubstituteTaught::
	.string "Aaah, je donnerais tout pour être\n"
	.string "dans la poche d'un KANGOUREX.$"

FuchsiaCity_Text_MyFatherIsGymLeader::
	.string "Mon père est le CHAMPION d'ARENE\n"
	.string "de cette ville.\p"
	.string "Je m'entraîne pour utiliser des\n"
	.string "POkéMON POISON, \p"
	.string "comme mon père.$"

