CeladonCity_DepartmentStore_1F_Frlg_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_1F_EventScript_Receptionist::
	msgbox CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_1F_EventScript_LayoutSign::
	msgbox CeladonCity_DepartmentStore_1F_Text_FloorDescriptions, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_1F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_1F_Text_ServiceCounter, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
	.string "Bonjour et bienvenue au CENTRE\n"
	.string "COMMERCIAL de CELADOPOLE.\p"
	.string "Le tableau sur la droite décrit les\n"
	.string "différents rayons du magasin.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
	.string "RDC: RENSEIGNEMENTS\p"
	.string "1er: MARCHE DES DRESSEURS\p"
	.string "2ème: JEUX VIDEO\p"
	.string "3ème: CADEAUX\p"
	.string "4ème: MEDICAMENTS\p"
	.string "TOIT: DISTRIBUTEURS$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
	.string "RDC: RENSEIGNEMENTS$"

