MtMoon_B2F_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, MtMoon_B2F_OnTransition
	.byte 0

MtMoon_B2F_OnTransition::
	call_if_unset FLAG_GOT_FOSSIL_FROM_MT_MOON, MtMoon_B2F_EventScript_ShowFossils
	end

MtMoon_B2F_EventScript_ShowFossils::
	clearflag FLAG_HIDE_DOME_FOSSIL
	clearflag FLAG_HIDE_HELIX_FOSSIL
	return

MtMoon_B2F_EventScript_MiguelTrigger::
	lockall
	applymovement LOCALID_MIGUEL, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	call MtMoon_B2F_EventScript_BattleMiguel
	releaseall
	end

MtMoon_B2F_EventScript_Miguel::
	lock
	faceplayer
	goto_if_set FLAG_GOT_FOSSIL_FROM_MT_MOON, MtMoon_B2F_EventScript_MiguelFossilPicked
	goto_if_defeated TRAINER_SUPER_NERD_MIGUEL, MtMoon_B2F_EventScript_MiguelGoPickFossil
	call MtMoon_B2F_EventScript_BattleMiguel
	release
	end

MtMoon_B2F_EventScript_BattleMiguel::
	textcolor NPC_TEXT_COLOR_MALE
	message MtMoon_B2F_Text_MiguelIntro
	waitmessage
	playbgm MUS_RG_ENCOUNTER_GYM_LEADER, 0
	waitbuttonpress
	setvar VAR_LAST_TALKED, LOCALID_MIGUEL
	trainerbattle_no_intro TRAINER_SUPER_NERD_MIGUEL, MtMoon_B2F_Text_MiguelDefeat
	setvar VAR_MAP_SCENE_MT_MOON_B2F, 1
	msgbox MtMoon_B2F_Text_WellEachTakeAFossil
	return

MtMoon_B2F_EventScript_MiguelFossilPicked::
	msgbox MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils
	release
	end

MtMoon_B2F_EventScript_MiguelGoPickFossil::
	msgbox MtMoon_B2F_Text_WellEachTakeAFossil
	release
	end

MtMoon_B2F_EventScript_DomeFossil::
	lock
	faceplayer
	msgbox MtMoon_B2F_Text_YouWantDomeFossil, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, MtMoon_B2F_EventScript_DontTakeFossil
	removeobject LOCALID_DOME_FOSSIL
	giveitem_msg MtMoon_B2F_Text_ObtainedDomeFossil, ITEM_DOME_FOSSIL, 1, MUS_RG_OBTAIN_KEY_ITEM
	closemessage
	delay 10
	applymovement LOCALID_MIGUEL, MtMoon_B2F_Movement_MiguelToHelixFossil
	waitmovement 0
	copyobjectxytoperm LOCALID_MIGUEL
	textcolor NPC_TEXT_COLOR_MALE
	playfanfare MUS_RG_OBTAIN_KEY_ITEM
	message MtMoon_B2F_Text_ThenThisFossilIsMine
	waitmessage
	waitfanfare
	removeobject LOCALID_HELIX_FOSSIL
	setflag FLAG_GOT_DOME_FOSSIL
	setflag FLAG_GOT_FOSSIL_FROM_MT_MOON
	release
	end

MtMoon_B2F_Movement_MiguelToHelixFossil::
	walk_right
	walk_up
	walk_up
	walk_up
	step_end

MtMoon_B2F_EventScript_HelixFossil::
	lock
	faceplayer
	msgbox MtMoon_B2F_Text_YouWantHelixFossil, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, MtMoon_B2F_EventScript_DontTakeFossil
	removeobject LOCALID_HELIX_FOSSIL
	giveitem_msg MtMoon_B2F_Text_ObtainedHelixFossil, ITEM_HELIX_FOSSIL, 1, MUS_RG_OBTAIN_KEY_ITEM
	closemessage
	delay 10
	applymovement LOCALID_MIGUEL, MtMoon_B2F_Movement_MiguelToDomeFossil
	waitmovement 0
	copyobjectxytoperm LOCALID_MIGUEL
	textcolor NPC_TEXT_COLOR_MALE
	playfanfare MUS_RG_OBTAIN_KEY_ITEM
	message MtMoon_B2F_Text_ThenThisFossilIsMine
	waitmessage
	waitfanfare
	removeobject LOCALID_DOME_FOSSIL
	setflag FLAG_GOT_HELIX_FOSSIL
	setflag FLAG_GOT_FOSSIL_FROM_MT_MOON
	release
	end

MtMoon_B2F_EventScript_DontTakeFossil::
	release
	end

MtMoon_B2F_Movement_MiguelToDomeFossil::
	walk_up
	walk_up
	walk_up
	step_end

MtMoon_B2F_EventScript_Grunt1::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT, MtMoon_B2F_Text_Grunt1Intro, MtMoon_B2F_Text_Grunt1Defeat
	msgbox MtMoon_B2F_Text_Grunt1PostBattle, MSGBOX_AUTOCLOSE
	end

MtMoon_B2F_EventScript_Grunt2::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_2, MtMoon_B2F_Text_Grunt2Intro, MtMoon_B2F_Text_Grunt2Defeat
	msgbox MtMoon_B2F_Text_Grunt2PostBattle, MSGBOX_AUTOCLOSE
	end

MtMoon_B2F_EventScript_Grunt3::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_3, MtMoon_B2F_Text_Grunt3Intro, MtMoon_B2F_Text_Grunt3Defeat
	msgbox MtMoon_B2F_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
	end

MtMoon_B2F_EventScript_Grunt4::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_4, MtMoon_B2F_Text_Grunt4Intro, MtMoon_B2F_Text_Grunt4Defeat
	msgbox MtMoon_B2F_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
	end

MtMoon_B2F_Text_MiguelIntro::
	.string "Hep! Toi là!\p"
	.string "Ces fossiles sont à moi!\n"
	.string "Pas touche!$"

MtMoon_B2F_Text_MiguelDefeat::
	.string "Bon, OK!\n"
	.string "On partage!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
	.string "Chacun le sien!\n"
	.string "Comme ça, pas de jaloux!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
	.string "OK, je prends celui-ci!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
	.string "Loin d'ici, sur CRAMOIS'ILE, se\n"
	.string "trouve un LABO POKéMON.\p"
	.string "On essaye d'y régénérer des\n"
	.string "fossiles de POKéMON.$"

MtMoon_B2F_Text_Grunt1Intro::
	.string "La TEAM ROCKET trouvera les \n"
	.string "fossiles et fera fortune en les \l"
	.string "vendant!$"

MtMoon_B2F_Text_Grunt1Defeat::
	.string "Grrr!\n"
	.string "J'suis vert!$"

MtMoon_B2F_Text_Grunt1PostBattle::
	.string "A cause de toi, j'suis vert!\n"
	.string "La TEAM ROCKET me vengera!$"

MtMoon_B2F_Text_Grunt2Intro::
	.string "La TEAM ROCKET?\n"
	.string "C'est nous!\l"
	.string "Les voleurs de POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat::
	.string "NOOOONNN!\n"
	.string "J'ai perdu!$"

MtMoon_B2F_Text_Grunt2PostBattle::
	.string "Hein?\n"
	.string "Mes compagnons vont me venger!$"

MtMoon_B2F_Text_Grunt3Intro::
	.string "Ça bosse dur ici!\n"
	.string "Alors du balai!$"

MtMoon_B2F_Text_Grunt3Defeat::
	.string "OK, j'ai perdu…$"

MtMoon_B2F_Text_Grunt3PostBattle::
	.string "Si tu trouves un fossile, tu me le\n"
	.string "donnes et tu décampes, pigé?$"

MtMoon_B2F_Text_Grunt4Intro::
	.string "Les p'tits gamins ne s'occupent pas\n"
	.string "des affaires des grands!$"

MtMoon_B2F_Text_Grunt4Defeat::
	.string "…\n"
	.string "J'suis épuisé!$"

MtMoon_B2F_Text_Grunt4PostBattle::
	.string "Les POKéMON existaient bien avant\n"
	.string "les Hommes…$"

MtMoon_B2F_Text_YouWantDomeFossil::
	.string "Tu veux le fossile DOME?$"

MtMoon_B2F_Text_YouWantHelixFossil::
	.string "Tu veux le fossile NAUTILE?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
	.string "Fossile NAUTILE obtenu!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
	.string "Fossile DOME obtenu!$"

