SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "Le PARC SAFARI est immense,\n"
	.string "tu trouves pas?\p"
	.string "KOGA, le CHAMPION d'ARENE de\n"
	.string "PARMANIE vient souvent ici.\p"
	.string "Grâce à lui, on peut se promener\n"
	.string "en sécurité.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Une PIERRE peut faire fuir les\n"
	.string "POKéMON mais ils seront plus\l"
	.string "faciles à capturer.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Un APPAT peut faciliter vos\n"
	.string "captures.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "J'ai cherché toute la sainte\n"
	.string "journée mais j'ai rien capturé.$"

