FiveIsland_MemorialPillar_Frlg_MapScripts::
	.byte 0

FiveIsland_MemorialPillar_EventScript_MemorialMan::
	lock
	goto_if_set FLAG_GOT_TM42_AT_MEMORIAL_PILLAR, FiveIsland_MemorialPillar_EventScript_AlreadyGotTM42
	goto_if_set FLAG_NO_ROOM_FOR_TM42_AT_MEMORIAL_PILLAR, FiveIsland_MemorialPillar_EventScript_ReturnedForTM42
	msgbox FiveIsland_MemorialPillar_Text_ScrubScrub
	closemessage
	applymovement LOCALID_MEMORIAL_MAN, Common_Movement_FacePlayer
	waitmovement 0
	delay 45
	msgbox FiveIsland_MemorialPillar_Text_YourMonsLookHealthy
	applymovement LOCALID_MEMORIAL_MAN, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	msgbox FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix
	release
	end

FiveIsland_MemorialPillar_EventScript_AlreadyGotTM42::
	msgbox FiveIsland_MemorialPillar_Text_ScrubScrubTectonix
	release
	end

FiveIsland_MemorialPillar_EventScript_ReturnedForTM42::
	msgbox FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks
	giveitem ITEM_TM42
	goto_if_eq VAR_RESULT, FALSE, FiveIsland_MemorialPillar_EventScript_NoRoomForTM42
	call FiveIsland_MemorialPillar_EventScript_ReceivedTM42
	release
	end

FiveIsland_MemorialPillar_EventScript_Memorial::
	lockall
	goto_if_set FLAG_GOT_TM42_AT_MEMORIAL_PILLAR, FiveIsland_MemorialPillar_EventScript_MemorialLemonadeAlreadyPlaced
	goto_if_set FLAG_NO_ROOM_FOR_TM42_AT_MEMORIAL_PILLAR, FiveIsland_MemorialPillar_EventScript_MemorialLemonadeAlreadyPlaced
	msgbox FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering
	checkitem ITEM_LEMONADE
	goto_if_eq VAR_RESULT, TRUE, FiveIsland_MemorialPillar_EventScript_AskPlaceLemonade
	releaseall
	end

FiveIsland_MemorialPillar_EventScript_AskPlaceLemonade::
	msgbox FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, FiveIsland_MemorialPillar_EventScript_PlaceLemonade
	releaseall
	end

FiveIsland_MemorialPillar_EventScript_PlaceLemonade::
	removeitem ITEM_LEMONADE
	msgbox FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade
	closemessage
	applymovement LOCALID_MEMORIAL_MAN, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	delay 45
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	textcolor NPC_TEXT_COLOR_MALE
	msgbox FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis
	giveitem ITEM_TM42
	goto_if_eq VAR_RESULT, FALSE, FiveIsland_MemorialPillar_EventScript_NoRoomForTM42
	call FiveIsland_MemorialPillar_EventScript_ReceivedTM42
	releaseall
	end

FiveIsland_MemorialPillar_EventScript_ReceivedTM42::
	msgbox FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo
	applymovement LOCALID_MEMORIAL_MAN, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	setflag FLAG_GOT_TM42_AT_MEMORIAL_PILLAR
	return

FiveIsland_MemorialPillar_EventScript_NoRoomForTM42::
	setflag FLAG_NO_ROOM_FOR_TM42_AT_MEMORIAL_PILLAR
	msgbox FiveIsland_MemorialPillar_Text_DontHaveRoomForIt
	releaseall
	end

FiveIsland_MemorialPillar_EventScript_MemorialLemonadeAlreadyPlaced::
	msgbox FiveIsland_MemorialPillar_Text_HereLiesTectonix
	releaseall
	end

FiveIsland_MemorialPillar_Text_MiloIntro::
	.string "Je suis l'aîné des FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est le bec!$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
	.string "Aïe, ça pique!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
	.string "A partir d'ici, tu peux voler\n"
	.string "jusqu'à l'ILE 4.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
	.string "Je suis le cadet des FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est les ailes!$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
	.string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
	.string "Il y avait un type super maussade\n"
	.string "par là-bas.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
	.string "Je suis le plus jeune des\n"
	.string "FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est le duvet!$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
	.string "J'adore me blottir dans le duvet.\n"
	.string "Ça me donne envie de dormir.$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
	.string "Je suis content quand je vois les\n"
	.string "POKéMON oiseau jouer ensemble.$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
	.string "Gratt, gratt…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
	.string "Bonjour…\n"
	.string "Ils ont l'air en forme vos POKéMON.$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
	.string "C'est ici qu'est enterré mon ONIX…\n"
	.string "Je l'appelais TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
	.string "On peut lire sur une pierre:\n"
	.string "“Ici repose TECTONIX”.\p"
	.string "Il y a une LIMONADE placée ici\n"
	.string "en signe d'offrande.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
	.string "Voulez-vous placer une autre\n"
	.string "LIMONADE en offrande?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
	.string "{PLAYER} place une LIMONADE\n"
	.string "en face de la stèle.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
	.string "M-Merci…\p"
	.string "C'était la boisson favorite de\n"
	.string "TECTONIX…\p"
	.string "Je ne vous connais pas, mais\n"
	.string "je suis très touché par\p"
	.string "votre bonté.\p"
	.string "Tenez, prenez ceci en\n"
	.string "remerciement.$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
	.string "Soyez toujours aussi bon envers\n"
	.string "vos POKéMON.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
	.string "Si vous n'avez plus de place,\n"
	.string "revenez me voir plus tard.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
	.string "Oh, vous revoilà.\p"
	.string "J'ai toujours cet objet que je\n"
	.string "voulais vous donner l'autre fois.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
	.string "Gratt, gratt…\p"
	.string "… … …\n"
	.string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
	.string "Les rochers sont empilés devant\n"
	.string "une plaque.\p"
	.string "On peut y lire:\n"
	.string "“Ici repose TECTONIX”.$"

