Route8_Frlg_MapScripts::
	.byte 0

Route8_EventScript_UndergroundPathSign::
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route8_Text_AidanIntro::
	.string "T'es habile avec tes POKéMON.\n"
	.string "Mais les maths, tu connais?$"

Route8_Text_AidanDefeat::
	.string "Ouch!\n"
	.string "Mauvais calcul.$"

Route8_Text_AidanPostBattle::
	.string "Je suis meilleur à l'école!$"

Route8_Text_StanIntro::
	.string "Le sort en est jeté!$"

Route8_Text_StanDefeat::
	.string "Haaa!\n"
	.string "Le hasard…$"

Route8_Text_StanPostBattle::
	.string "Dame chance n'est pas avec moi!$"

Route8_Text_GlennIntro::
	.string "Il te faut une bonne stratégie!$"

Route8_Text_GlennDefeat::
	.string "Hé!\n"
	.string "Pas logique!$"

Route8_Text_GlennPostBattle::
	.string "D'abord TADMORV, et après…\n"
	.string "Et puis…$"

Route8_Text_PaigeIntro::
	.string "Moi, j'aime les NIDORAN! Yaha!$"

Route8_Text_PaigeDefeat::
	.string "Hein?$"

Route8_Text_PaigePostBattle::
	.string "Quand un POKéMON grandit,\n"
	.string "il devient gros et moche.\p"
	.string "Je les préfère tout petits!$"

Route8_Text_LeslieIntro::
	.string "L'école c'est cool, comme les\n"
	.string "POKéMON!$"

Route8_Text_LeslieDefeat::
	.string "Ben…\n"
	.string "L'école c'est plus facile!$"

Route8_Text_LesliePostBattle::
	.string "On est bloqués ici, aux portes de\n"
	.string "SAFRANIA.$"

Route8_Text_AndreaIntro::
	.string "MIAOUSS est si mignon. Miaou!$"

Route8_Text_AndreaDefeat::
	.string "Miaou!$"

Route8_Text_AndreaPostBattle::
	.string "Je trouve que ROUCOOL et RATTATA\n"
	.string "sont trop cool!$"

Route8_Text_MeganIntro::
	.string "Je sais, on a l'air idiot à rester\n"
	.string "debout comme ça!$"

Route8_Text_MeganDefeat::
	.string "Ben…\n"
	.string "C'est malin ça!$"

Route8_Text_MeganPostBattle::
	.string "Le gardien de SAFRANIA ne nous\n"
	.string "laissera pas passer!\p"
	.string "Je sais que c'est son boulot, mais\n"
	.string "je ne l'aime pas beaucoup.$"

Route8_Text_RichIntro::
	.string "Je suis un joueur errant!$"

Route8_Text_RichDefeat::
	.string "J'ai raté le jackpot!$"

Route8_Text_RichPostBattle::
	.string "Le jeu et les POKéMON, c'est comme\n"
	.string "les cacahuètes. \p"
	.string "Tu commences et tu peux plus\n"
	.string "t'arrêter! C'est fou!$"

Route8_Text_JuliaIntro::
	.string "Qu'il est mimi, gentil et trognon\n"
	.string "ce POKéMON! Il est à qui?\l"
	.string "Hein? A qui?$"

Route8_Text_JuliaDefeat::
	.string "Arrête!\p"
	.string "T'es pas gentil avec MELOFEE!$"

Route8_Text_JuliaPostBattle::
	.string "Il paraît que MELOFEE peut\n"
	.string "évoluer grâce à une PIERRE LUNE.\p"
	.string "J'ai lu ça quelque part, je me\n"
	.string "demande si c'est vrai.$"

Route8_Text_UndergroundPathSign::
	.string "SOUTERRAIN\n"
	.string "CELADOPOLE - LAVANVILLE$"

Route8_Text_EliIntro::
	.string "ELI: La puissance des jumeaux est\n"
	.string "fantastique, tu le savais pas?$"

Route8_Text_EliDefeat::
	.string "ELI: Mais…\n"
	.string "On a utilisé notre puissance…$"

Route8_Text_EliPostBattle::
	.string "ELI: J'ai attrapé mes POKéMON\n"
	.string "avec ANNE.$"

Route8_Text_EliNotEnoughMons::
	.string "ELI: On ne pourra pas se battre\n"
	.string "ensemble si tu n'as qu'un POKéMON.$"

Route8_Text_AnneIntro::
	.string "ANNE: On va te montrer notre\n"
	.string "puissance!$"

Route8_Text_AnneDefeat::
	.string "ANNE: Notre force de jumelles…$"

Route8_Text_AnnePostBattle::
	.string "ANNE: Je dresse mes POKéMON\n"
	.string "avec ELI.$"

Route8_Text_AnneNotEnoughMons::
	.string "ANNE: Hi, hi. Si tu veux combattre,\n"
	.string "il te faut deux POKéMON.$"

Route8_Text_RicardoIntro::
	.string "Je ne crains personne sur ma\n"
	.string "bécane.$"

Route8_Text_RicardoDefeat::
	.string "Aaah, non!\n"
	.string "J'suis à sec.$"

Route8_Text_RicardoPostBattle::
	.string "Le terrain était mauvais pour moi.$"

Route8_Text_JarenIntro::
	.string "Pousse-toi de là, ou je te\n"
	.string "roule dessus.$"

Route8_Text_JarenDefeat::
	.string "Tu rigoles pas toi…$"

Route8_Text_JarenPostBattle::
	.string "Ne prends pas la grosse tête\n"
	.string "juste pour ça…$"
