Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
	.string "Tu veux gagner ou perdre?$"

Route11_Text_HugoDefeat::
	.string "OK.\n"
	.string "T'as gagné!$"

Route11_Text_HugoPostBattle::
	.string "Les POKéMON c'est la vie!\n"
	.string "Et la vie c'est le jeu!$"

Route11_Text_JasperIntro::
	.string "J'adore les défis!$"

Route11_Text_JasperDefeat::
	.string "J'ai eu ma chance!$"

Route11_Text_JasperPostBattle::
	.string "Dans le monde merveilleux des\n"
	.string "POKéMON, y'a pas de lâches!$"

Route11_Text_EddieIntro::
	.string "On y va!\n"
	.string "Mais triche pas!$"

Route11_Text_EddieDefeat::
	.string "Rha!\n"
	.string "C'est pas vrai!$"

Route11_Text_EddiePostBattle::
	.string "J'ai fait de mon mieux! Pas ma\n"
	.string "faute si j'suis nul!$"

Route11_Text_BraxtonIntro::
	.string "Attention!\n"
	.string "Je pose des câbles!$"

Route11_Text_BraxtonDefeat::
	.string "J'me suis pris du jus!$"

Route11_Text_BraxtonPostBattle::
	.string "Il faut économiser l'énergie!$"

Route11_Text_DillonIntro::
	.string "Je suis nouveau, mais je sais que\n"
	.string "je peux gagner!$"

Route11_Text_DillonDefeat::
	.string "Mes POKéMON sont nuls!\n"
	.string "Beuh…\p"
	.string "J'ai pas dû les faire assez\n"
	.string "progresser.$"

Route11_Text_DillonPostBattle::
	.string "Quoi encore?\n"
	.string "Laisse-moi!$"

Route11_Text_DirkIntro::
	.string "HAHAHA!\n"
	.string "J'ai jamais perdu!$"

Route11_Text_DirkDefeat::
	.string "Heu?\n"
	.string "Ma première défaite!$"

Route11_Text_DirkPostBattle::
	.string "Tu as la chance des débutants!$"

Route11_Text_DarianIntro::
	.string "Je n'ai encore jamais gagné…$"

Route11_Text_DarianDefeat::
	.string "Je m'y attendais…$"

Route11_Text_DarianPostBattle::
	.string "J'suis maudit, je crois!$"

Route11_Text_YasuIntro::
	.string "Je suis le plus fort de ma classe!$"

Route11_Text_YasuDefeat::
	.string "Argh!\n"
	.string "Tu veux être le chef de classe?$"

Route11_Text_YasuPostBattle::
	.string "Il y a un gros POKéMON qui vient\n"
	.string "de la montagne.\p"
	.string "Si t'es fort, tu pourrais l'attraper.$"

Route11_Text_BernieIntro::
	.string "Fais attention aux câbles!$"

Route11_Text_BernieDefeat::
	.string "Whoa!\n"
	.string "Tu fais des étincelles!$"

Route11_Text_BerniePostBattle::
	.string "Bon, j'ai du boulot, moi!$"

Route11_Text_DaveIntro::
	.string "Mes POKéMON sont prêts!$"

Route11_Text_DaveDefeat::
	.string "Trop, trop balèze!$"

Route11_Text_DavePostBattle::
	.string "Faut que j'en chope des\n"
	.string "plus forts!$"

Route11_Text_DiglettsCave::
	.string "CAVE TAUPIQUEUR$"

