MoveRelearner_Text_WouldLearnNewMoves:
	.string "Salut, je suis le Maître des Capacités.\p"
	.string "Est-ce que tu veux que j'enseigne à\n"
	.string "ton équipe de nouvelles capacités?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Cap. Niveau$"

MoveRelearner_Text_EggMoves:
	.string "Cap. Œuf$"

MoveRelearner_Text_TMMoves:
	.string "Cap. CT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Cap. Apprises$"

MoveRelearner_Text_SeeYa:
	.string "A plus!$"

MoveRelearner_Text_AnythingElse:
	.string "Que puis-je faire d'autre\n"
	.string "pour toi?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Choisis un Pokémon.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Tu n'as pas de Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Navré…\n"
	.string "Un Œuf ne peut pas apprendre de capacités.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Navré…\p"
	.string "Il ne semble pas que j'aie une capacité\n"
	.string "que je puisse enseigner à ce Pokémon.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "cap. niveau$"

MoveRelearner_Text_EggMoveLWR::
	.string "cap. œuf$"

MoveRelearner_Text_TMMoveLWR::
	.string "cap. CT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "cap. apprises$"

MoveRelearner_Text_MoveLWR::
	.string "cap.$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Quelle {STR_VAR_3} devrais-je\n"
	.string "enseigner?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Je te remercie de tes services.\n"
	.string "Reviens me voir!$"
