gText_ObtainedTheItem::
    .string "Obtenu: {STR_VAR_2}!$"

gText_TheBagIsFull::
    .string "Le SAC est plein…$"

gText_PutItemInPocket::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "POCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
    .string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull::
    .string "Dommage!\n"
    .string "Le SAC est plein.$"

gText_PlayerPutItemInBag::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "le SAC.$"

gText_ObtainedTheDecor::
    .string "Obtenu: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
    .string "Dommage! Il n'y a plus assez de place\n"
    .string "pour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
    .string "Transfert de {STR_VAR_2} sur le PC.$"

gText_ObtainedTheItems::
	.string "Obtenu: {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} a trouvé\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} a trouvé\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)$"

gText_CoinCaseIsFull::
	.string "Dommage!\n"
	.string "La BOITE JETONS est pleine.$"

gText_NothingToPutThemIn::
	.string "Dommage!\n"
	.string "Il n'y a rien pour les ranger.$"
