gText_PkmnTransferredSomeonesPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
    .string "PC de ???.\p"
    .string "Il a été placé dans la BOITE\n"
    .string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
#if IS_FRLG
	.string "PC de LEO.\p"
#else
    .string "PC d'ANNETTE.\p"
#endif
    .string "Il a été placé dans la BOITE\n"
    .string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
    .string "La BOITE {STR_VAR_3} sur le PC\n"
    .string "de ??? est pleine.\p"
    .string "{STR_VAR_2} a été placé dans la\n"
    .string "BOITE appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La BOITE {STR_VAR_3} sur le PC\n"
#if IS_FRLG
	.string "de LEO est pleine.\p"
#else
    .string "d'ANNETTE est pleine.\p"
#endif
	.string "{STR_VAR_2} a été placé dans la\n"
	.string "BOITE appelée “{STR_VAR_1}”.$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} was sent to\n"
	.string "{B_PC_CREATOR_NAME} PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PlayerObtainedTheMon::
	.string "{PLAYER} obtained\n"
	.string "the {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
    .string "Il n'y a plus de place pour\n"
    .string "les POKéMON.\p"
    .string "Les BOITES sont pleines et\n"
    .string "ne peuvent plus rien recevoir.$"

gText_NicknameThisPokemon::
    .string "Voulez-vous donner un surnom\n"
    .string "à {STR_VAR_1}?$"
