gBirchDexRatingText_AreYouCurious::
	.string "PROF. SEKO: Ah, {PLAYER}{KUN}!\p"
	.string "Tu veux que je te donne mon avis\n"
	.string "sur ton POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hum? Oh, tu n'as pas attrapé assez\n"
	.string "de POKéMON pour que ça en vaille\l"
	.string "la peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hum…\p"
	.string "Tu as rencontré {STR_VAR_1} POKéMON\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Tu devrais aller plus souvent dans\n"
	.string "les herbes et mieux chercher\l"
	.string "les POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu as bien\n"
	.string "compris ça. Mais désormais,\l"
	.string "ça va devenir plus dur.$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent\n"
	.string "que dans des zones précises.\l"
	.string "Sois tenace!$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il pourrait être un peu plus\n"
	.string "rempli, mais il ressemble déjà plus\l"
	.string "à un POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Hé, il commence à être plutôt\n"
	.string "pas mal. Continue sur ta lancée!$"

gBirchDexRatingText_LessThan60::
	.string "Est-ce que tu utilises des CANNES?\n"
	.string "Il y a beaucoup de POKéMON\l"
	.string "dans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Plutôt que juste attraper des\n"
	.string "POKéMON, pourquoi ne pas aussi\l"
	.string "les faire évoluer?$"

gBirchDexRatingText_LessThan80::
	.string "Ce POKéDEX va être formidable.\n"
	.string "J'en ai bien l'impression.$"

gBirchDexRatingText_LessThan90::
	.string "Tu as collecté tout ça…\n"
	.string "Tu as un talent remarquable!$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le PARC SAFARI?\p"
	.string "J'ai entendu dire que certains\n"
	.string "POKéMON ne s'attrapent que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as atteint la barre des 100.\n"
	.string "C'est un POKéDEX impressionnant!$"

gBirchDexRatingText_LessThan120::
	.string "En utilisant ECLATE-ROC, tu peux\n"
	.string "trouver des POKéMON.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais faire des échanges pour\n"
	.string "te procurer d'autres POKéMON.$"

gBirchDexRatingText_LessThan140::
	.string "Certains POKéMON évoluent quand\n"
	.string "ils aiment vraiment leur DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu'il y avait\n"
	.string "autant d'espèces de POKéMON\l"
	.string "à HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Il arrive que certains POKéMON\n"
	.string "sortent en grand nombre, telle une\l"
	.string "horde sauvage.\p"
	.string "Ne rate pas ce genre d'occasion!$"

gBirchDexRatingText_LessThan170::
	.string "On a une bonne représentation des\n"
	.string "POKéMON de la région de HOENN\l"
	.string "en regardant ton POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Je pourrais déjà te donner le titre\n"
	.string "de PROFESSEUR POKéMON!$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi bien rempli,\n"
	.string "tu passes en professionnel!$"

gBirchDexRatingText_LessThan200::
	.string "Tu es à deux doigts de compléter\n"
	.string "ce POKéDEX. Je le vois!$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations!\n"
	.string "Ton POKéDEX est complet!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hum…\n"
	.string "Sur l'ensemble du territoire…\p"
	.string "Tu as rencontré {STR_VAR_1} POKéMON\n"
	.string "et tu as attrapé {STR_VAR_2} POKéMON…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "CHEN: Je suis content de te\n"
	.string "revoir. Où en es-tu avec ton\l"
	.string "POKéDEX?\p"
	.string "Voyons, voyons…$"

PokedexRating_Text_SeenXOwnedY::
	.string "Niveau POKéDEX:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.\p"
	.string "{FONT_NORMAL}Observation du PROF. CHEN:$"

PokedexRating_Text_LessThan10::
	.string "Tu ne vas pas assez dans les\n"
	.string "hautes herbes.\p"
	.string "Il t'en reste beaucoup à trouver!$"

PokedexRating_Text_LessThan20::
	.string "Tu es sur la bonne voie!\p"
	.string "Un de mes ASSISTANTS te donnera\n"
	.string "la CS FLASH!$"

PokedexRating_Text_LessThan30::
	.string "Il t'en reste plein à attraper\n"
	.string "pour remplir ton POKéDEX!\p"
	.string "Essaie d'en capturer d'autres!$"

PokedexRating_Text_LessThan40::
	.string "Très bien! On voit bien que tu te\n"
	.string "donnes du mal.\p"
	.string "Un de mes ASSISTANTS a un\n"
	.string "CHERCH'OBJET pour toi!$"

PokedexRating_Text_LessThan50::
	.string "Ton POKéDEX prend vraiment forme.\p"
	.string "Un de mes ASSISTANTS te donnera\n"
	.string "une PIECE RUNE.$"

PokedexRating_Text_LessThan60::
	.string "Oh, tu as atteint 50 espèces\n"
	.string "différentes.\p"
	.string "Un de mes ASSISTANTS a un\n"
	.string "MULTI EXP pour toi!$"

PokedexRating_Text_LessThan70::
	.string "Oh! C'est de mieux en mieux!$"

PokedexRating_Text_LessThan80::
	.string "Excellent!\p"
	.string "Mais tu devrais aller pêcher plus\n"
	.string "de POKéMON marins!$"

PokedexRating_Text_LessThan90::
	.string "Magnifique! Mais dis-moi, tu aimes\n"
	.string "collectionner, non?$"

PokedexRating_Text_LessThan100::
	.string "Mirobolant!\n"
	.string "Ça n'a pas dû être facile!$"

PokedexRating_Text_LessThan110::
	.string "Tu as atteint 100 espèces\n"
	.string "différentes! Quel talent!$"

PokedexRating_Text_LessThan120::
	.string "Tu as même fait évoluer tes\n"
	.string "POKéMON! Génial!$"

PokedexRating_Text_LessThan130::
	.string "Parfait! Fais des échanges pour\n"
	.string "en avoir encore plus!$"

PokedexRating_Text_LessThan140::
	.string "Impressionnant! On dirait que tu\n"
	.string "as fait ça toute ta vie!$"

PokedexRating_Text_LessThan150::
	.string "Chapeau bas!\n"
	.string "C'est toi le Prof maintenant!$"

PokedexRating_Text_Complete::
	.string "Ton POKéDEX est complet!\n"
	.string "Félicitations!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Et ton POKéDEX NATIONAL est:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "J'ai hâte de te voir remplir le\n"
	.string "POKéDEX NATIONAL!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Enfin…\p"
	.string "Tu as rempli le POKéDEX!\p"
	.string "Je suis vraiment impressionné.$"

PokedexRating_Text_Wroooaaarrr::
	.string "Ouaaaaaah!!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Merci, {PLAYER}!\n"
	.string "Merci de tout cœur!\l"
	.string "Tu as exaucé mon rêve!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "CHEN: Ah, bienvenue!\p"
	.string "Dis-moi, à quoi ressemble ton\n"
	.string "POKéDEX?\p"
	.string "Ahahaha!\p"
	.string "Je sais bien à quoi ça ressemble,\n"
	.string "mais je veux y jeter un œil!\p"
	.string "Voyons voir…$"
