Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "Ha! J'ai trébuché sur un POKéMON\n"
	.string "ROCHE: RACAILLOU!$"

Route4_Text_CrissyIntro::
	.string "Je viens chercher mon POKéMON\n"
	.string "champignon!$"

Route4_Text_CrissyDefeat::
	.string "Oh!\n"
	.string "Mon POKéMON!$"

Route4_Text_CrissyPostBattle::
	.string "Je crois qu'il n'y a plus de\n"
	.string "champignons dans le coin.\p"
	.string "Je les ai tous ramassés.$"

Route4_Text_MtMoonEntrance::
	.string "MONT SELENITE\n"
	.string "Entrée du tunnel$"

Route4_Text_RouteSign::
	.string "ROUTE 4\n"
	.string "MONT SELENITE - AZURIA$"

Text_MegaPunchTeach::
	.string "Un coup de poing féroce d'une\n"
	.string "puissance destructrice!\p"
	.string "En cas de besoin, ULTIMAPOING\n"
	.string "est l'attaque idéale, tu crois pas?\p"
	.string "Bon, laisse-moi apprendre\n"
	.string "ULTIMAPOING à un de tes POKéMON!$"

Text_MegaPunchDeclined::
	.string "Tu reviendras quand tu auras\n"
	.string "compris l'intérêt d'ULTIMAPOING.$"

Text_MegaPunchWhichMon::
	.string "Parfait!\n"
	.string "Quel POKéMON doit l'apprendre?$"

Text_MegaPunchTaught::
	.string "Nous sommes maintenant frères\n"
	.string "dans l'art du combat!\p"
	.string "Tu devrais partir avant de tomber\n"
	.string "sur l'imbécile qui s'entraîne\p"
	.string "qu'en utilisant les coups de pied.$"

Text_MegaKickTeach::
	.string "Un coup de pied féroce d'une\n"
	.string "grande puissance destructrice!\p"
	.string "En cas de besoin, ULTIMAWASHI\n"
	.string "est l'attaque idéale, tu crois pas?\p"
	.string "Bon, laisse-moi apprendre\n"
	.string "ULTIMAWASHI à un de tes POKéMON!$"

Text_MegaKickDeclined::
	.string "Tu reviendras vite quand tu auras\n"
	.string "compris l'utilité d'ULTIMAWASHI.$"

Text_MegaKickWhichMon::
	.string "Très bien!\n"
	.string "Quel POKéMON doit l'apprendre?$"

Text_MegaKickTaught::
	.string "Nous partageons maintenant la\n"
	.string "même philosophie du combat.\p"
	.string "Tu devrais t'en aller avant de\n"
	.string "tomber sur l'imbécile qui ne\p"
	.string "s'entraîne qu'en utilisant les\n"
	.string "coups de poing.$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "Oh, c'est le BADGE ROCHE!\n"
	.string "C'est PIERRE qui te l'a donné, non?\p"
	.string "Il est cool. Il est très fort,\n"
	.string "les gens l'aiment et le respectent.\p"
	.string "Je voudrais devenir CHAMPION\n"
	.string "d'ARENE comme lui.$"
