SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "Bonjour! Je suis serveur sur ce\n"
	.string "bateau!\p"
	.string "Je me ferai une joie de vous\n"
	.string "servir!\p"
	.string "Ha!\n"
	.string "L'air du grand large!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "Les passagers sont en ébullition!\p"
	.string "Ils vont certainement vous\n"
	.string "provoquer en duel!$"

