Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
	.string "Je m'échauffe avant de piquer\n"
	.string "une tête!$"

Route19_Text_RichardDefeat::
	.string "J'suis tout chaud, là!$"

Route19_Text_RichardPostBattle::
	.string "OK, prêt à plonger!$"

Route19_Text_ReeceIntro::
	.string "Attends! Mouille-toi la nuque avant\n"
	.string "de plonger!$"

Route19_Text_ReeceDefeat::
	.string "Ha! J'suis bien refroidi, là!$"

Route19_Text_ReecePostBattle::
	.string "Fais gaffe aux TENTACOOL!$"

Route19_Text_MatthewIntro::
	.string "J'aime nager!\n"
	.string "Et toi?$"

Route19_Text_MatthewDefeat::
	.string "Plaouff!\n"
	.string "T'es dans la vague!$"

Route19_Text_MatthewPostBattle::
	.string "Je nage plus vite que les POKéMON!$"

Route19_Text_DouglasIntro::
	.string "D'où vient le vent?$"

Route19_Text_DouglasDefeat::
	.string "Glargh! OK, j'poserai plus de\n"
	.string "questions idiotes!$"

Route19_Text_DouglasPostBattle::
	.string "Je vois des îles au loin!$"

Route19_Text_DavidIntro::
	.string "Je cherche des POKéMON dans les\n"
	.string "grands fonds!$"

Route19_Text_DavidDefeat::
	.string "Glubb!\n"
	.string "J'me noie!$"

Route19_Text_DavidPostBattle::
	.string "C'est en pêchant que tu attraperas\n"
	.string "des POKéMON EAU!$"

Route19_Text_TonyIntro::
	.string "La mer, l'écume, les vagues…\n"
	.string "C'est beau!!!$"

Route19_Text_TonyDefeat::
	.string "Aïe!\n"
	.string "T'es pas poète!$"

Route19_Text_TonyPostBattle::
	.string "Je cherche la paix intérieure dans\n"
	.string "la mer!$"

Route19_Text_AnyaIntro::
	.string "Ah, j'en ai marre de nager!$"

Route19_Text_AnyaDefeat::
	.string "Oh!\n"
	.string "J'ai perdu!$"

Route19_Text_AnyaPostBattle::
	.string "C'est vraiment loin les\n"
	.string "ILES ECUME!\p"
	.string "Je vais retourner à PARMANIE.$"

Route19_Text_AliceIntro::
	.string "Nager c'est cool!\n"
	.string "Faut juste éviter de couler!$"

Route19_Text_AliceDefeat::
	.string "Plaouff!$"

Route19_Text_AlicePostBattle::
	.string "Mon p'tit copain veut nager\n"
	.string "jusqu'aux ILES ECUME.$"

Route19_Text_AxleIntro::
	.string "Ces eaux sont dangereuses!$"

Route19_Text_AxleDefeat::
	.string "Argh!\n"
	.string "Dangereux!$"

Route19_Text_AxlePostBattle::
	.string "J'ai une crampe!\n"
	.string "Gloup! Argl!$"

Route19_Text_ConnieIntro::
	.string "Je nage, mais j'en ai marre!$"

Route19_Text_ConnieDefeat::
	.string "J'en peux plus…$"

Route19_Text_ConniePostBattle::
	.string "Un LOKHLASS, c'est grand et gros!\p"
	.string "Si je montes sur son dos,\n"
	.string "je ne serai pas mouillée!$"

Route19_Text_RouteSign::
	.string "ROUTE 19\n"
	.string "PARMANIE - ILES ECUME$"

Route19_Text_LiaIntro::
	.string "VIVI: Je recherche mon frère.\n"
	.string "Il vient de devenir DRESSEUR.$"

Route19_Text_LiaDefeat::
	.string "VIVI: C'est pas une façon de\n"
	.string "traiter mon petit frère!$"

Route19_Text_LiaPostBattle::
	.string "VIVI: Tu as un petit frère toi\n"
	.string "aussi?\p"
	.string "J'espère que tu lui apprends tout\n"
	.string "plein de trucs.$"

Route19_Text_LiaNotEnoughMons::
	.string "VIVI: Je veux me battre aux côtés\n"
	.string "de mon frère.\p"
	.string "Bah, t'as pas deux POKéMON?$"

Route19_Text_LucIntro::
	.string "SAM: Ma grande sœur m'a tout\n"
	.string "appris sur les POKéMON.$"

Route19_Text_LucDefeat::
	.string "SAM: Oh, wow! J'ai trouvé quelqu'un\n"
	.string "de plus fort que ma sœur.$"

Route19_Text_LucPostBattle::
	.string "SAM: Ma grande sœur est balèze\n"
	.string "et sympa. Je l'adore.$"

Route19_Text_LucNotEnoughMons::
	.string "SAM: On s'battra que si j'suis\n"
	.string "avec ma sœur.\p"
	.string "T'as pas deux POKéMON?$"
