FiveIsland_House2_Frlg_MapScripts::
	.byte 0

FiveIsland_House2_EventScript_OldMan::
	msgbox FiveIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
	end

FiveIsland_House2_Text_MeadowBelongedToFamily::
	.string "Ce PRE est dans la famille depuis\n"
	.string "des générations.\p"
	.string "Je devrais faire construire un\n"
	.string "grand manoir dessus.\p"
	.string "Mais je pense qu'il vaut mieux\n"
	.string "laisser les animaux courir dessus!$"

