Route21_North_Frlg_MapScripts::
	.byte 0

Route21_North_Text_RonaldIntro::
	.string "Tu veux savoir s'il y a des\n"
	.string "poissons ici?$"

Route21_North_Text_RonaldDefeat::
	.string "Paf!$"

Route21_North_Text_RonaldPostBattle::
	.string "Y'a comme un manque de poisson!$"

Route21_North_Text_WadeIntro::
	.string "J'ai eu une bonne prise!\n"
	.string "Tu veux tester?$"

Route21_North_Text_WadeDefeat::
	.string "Zut!\n"
	.string "Encore un MAGICARPE!$"

Route21_North_Text_WadePostBattle::
	.string "Je ne pêche que\n"
	.string "des MAGICARPE!$"

Route21_North_Text_SpencerIntro::
	.string "Ah, je suis revigoré par l'écume.$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "J'adore la mer mais j'ai rien\n"
	.string "contre la montagne!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
