SSAnne_2F_Room6_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room6_EventScript_Woman1::
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end

SSAnne_2F_Room6_EventScript_Woman2::
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end

SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
	.string "Le CAPITAINE avait l'air tout\n"
	.string "pâlot!$"

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
	.string "C'est assez fréquent d'avoir le mal\n"
	.string "de mer!$"

