SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "Yahaa!\n"
	.string "Je vais te battre sans efforts.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "Tsss!\n"
	.string "Pas assez forte!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "Comment?\p"
	.string "Mes actes ne collent pas avec\n"
	.string "mon look?\p"
	.string "Hey, ça fait partie de ma\n"
	.string "stratégie.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "Hello!\n"
	.string "T'es membre de mon fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "Non, tu ne dois pas être fan…\p"
	.string "Bon, je peux y remédier. Je vais\n"
	.string "te chanter quelque chose.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "Lalalalaaa…\n"
	.string "Quand j'envoie mes POKéMON,\l"
	.string "les filles se mettent à crier.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "Cette île est trop étendue…\n"
	.string "C'est difficile d'aller partout.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "Oh oh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "Les DRESSEURS de la ville comme\n"
	.string "toi, ils sont tous aussi forts?\p"
	.string "Tu te diriges vers la TOUR, non?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "Je punis les gens qui font\n"
	.string "du mal aux POKéMON.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "Tu ne sembles pas être du genre\n"
	.string "à créer des problèmes.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "Si tu traites tes POKéMON avec\n"
	.string "gentillesse, ils le sentiront.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "EVE: Je vais me joindre à JOE\n"
	.string "pour t'écraser.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "EVE: On a perdu…$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "EVE: On va s'entraîner plus.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "EVE: Je vais me joindre à JOE\n"
	.string "pour t'écraser.\p"
	.string "Mais reviens quand tu auras\n"
	.string "deux POKéMON, OK?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "JOE: Avec EVE, je me sens\n"
	.string "invincible.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "JOE: La défaite ne compte pas tant\n"
	.string "que je suis avec elle.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "JOE: Quand je suis avec elle…\p"
	.string "je me sens bien que je gagne\n"
	.string "ou que je perde.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "JOE: Si c'est avec EVE, je serai\n"
	.string "content de me battre contre toi.\p"
	.string "Si c'était possible, on aurait pu\n"
	.string "faire un deux contre deux.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "ENTREE DU CANYON SESOR\p"
	.string "Evitez de piétiner les plantes\n"
	.string "du canyon.$"

