SafariZone_East_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker::
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan::
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end

SafariZone_East_Text_HowManyDidYouCatch::
	.string "T'en as capturé combien? Moi j'suis\n"
	.string "naze!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
	.string "J'ai trouvé un LEVEINARD!\p"
	.string "J'ai bien fait de chercher pendant\n"
	.string "4 heures!$"

SafariZone_East_Text_TiredFromAllTheFun::
	.string "Pffff!\n"
	.string "J'en ai marre!$"

