CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Yahahaha!\n"
	.string "Triple 7!!!\l"
	.string "Par ici l'pognon!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "CHEF!\p"
	.string "2000 POKéMON ont été envoyés\n"
	.string "comme prix au casino!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Ne touche pas au bouton derrière\n"
	.string "le poster du CASINO!\p"
	.string "Hein?\n"
	.string "Mais non j'l'ai pas dit!$"

