Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "De nombreux POKéMON vivent\n"
	.string "uniquement dans les forêts ou les\l"
	.string "cavernes.\p"
	.string "Cherche bien partout pour tous\n"
	.string "les attraper!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "As-tu remarqué les buissons sur la\n"
	.string "route?\p"
	.string "Une technique secrète de POKéMON\n"
	.string "peut les couper.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "Tu peux empêcher un POKéMON\n"
	.string "d'évoluer.\p"
	.string "Quand un POKéMON évolue, tu peux\n"
	.string "stopper le processus.\p"
	.string "C'est une technique pour qu'ils\n"
	.string "restent comme ils sont.$"

