TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "J'ai amélioré la capacité ultime\n"
	.string "de ce type…\p"
	.string "Quelqu'un voudrait-il la\n"
	.string "prendre pour plus tard?\p"
	.string "… Hmm? Alors?\p"
	.string "T-toi…\n"
	.string "C-ce {STR_VAR_1}…$"

Text_JustMistaken::
	.string "… Non…\n"
	.string "C'était une erreur.$"

Text_AllowMeToTeachMonUltimateMove::
	.string "Oh, c'est lui!\n"
	.string "C'est LE POKéMON!\p"
	.string "Ce {STR_VAR_1} mérite d'apprendre\n"
	.string "ma capacité ultime!\p"
	.string "Tu es d'accord?\p"
	.string "Laisseras-tu {STR_VAR_1} apprendre\n"
	.string "{STR_VAR_2}?$"

Text_YouRejectIt::
	.string "Koaa! T'es pas d'accord?\n"
	.string "Je ne renoncerai pas!$"

Text_LetMeConferUltimateMove::
	.string "Tu veux bien?\p"
	.string "Alors laisse-moi enseigner\n"
	.string "{STR_VAR_2} à ton {STR_VAR_1}.$"

Text_TaughtMove::
	.string "Ah… ah… ah…\p"
	.string "Je ne pensais pas avoir la chance\n"
	.string "de pouvoir un jour l'enseigner…$"

Text_MakeBestUseOfMove::
	.string "J'espère que tu en feras le\n"
	.string "meilleur usage!$"

Text_PassedOnEverythingIKnow::
	.string "Gasp…\p"
	.string "Je n'ai aucun regret. J'ai vu tout\n"
	.string "ce que je devais voir.\p"
	.string "Je peux terminer ma vie en sachant\n"
	.string "que mon œuvre est accomplie.$"

Text_FeelRejuvenated::
	.string "Je me sens libérée maintenant que\n"
	.string "je t'ai transmis mon savoir.\p"
	.string "En fait, je me sens renaître, comme\n"
	.string "si j'avais de nouveau 20 ans.$"
