ThreeIsland_BondBridge_Frlg_MapScripts::
	.byte 0

ThreeIsland_BondBridge_EventScript_BerryForestSign::
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_EventScript_BondBridgeSign::
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_Text_NikkiIntro::
	.string "L'odeur de la mer, le sel sur ma\n"
	.string "peau… Ça me donne la pêche!$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
	.string "Y'a comme une odeur bizarre…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
	.string "Tu laves jamais tes POKéMON?\n"
	.string "Ça sent vraiment pas bon…$"

ThreeIsland_BondBridge_Text_VioletIntro::
	.string "Où est-ce que tu cours si vite?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
	.string "Tu t'occupes vraiment bien de\n"
	.string "tes POKéMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
	.string "Si tu continues ton chemin, tu\n"
	.string "vas tomber sur les BOIS BAIES.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
	.string "Ma maman elle dit que j'ai pas le\n"
	.string "droit de nager sans ma bouée.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
	.string "Waaah!\n"
	.string "Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
	.string "Juré craché, cette année\n"
	.string "j'apprendrai à nager!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
	.string "Yeah, yeah!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
	.string "Qu'est-ce qui s'est passé?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
	.string "J'ai gagné ou… ?\n"
	.string "Je viens de perdre là!$"

ThreeIsland_BondBridge_Text_TishaIntro::
	.string "Oh non, ne viens pas là!\n"
	.string "Reste loin de moi!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
	.string "OK, t'as gagné!\n"
	.string "Tu veux bien me laisser maintenant?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
	.string "Un POKéMON a mordu ma combi.\n"
	.string "J'arrive pas à sortir de l'eau!$"

ThreeIsland_BondBridge_Text_JoyIntro::
	.string "BEA: Tu vas vite comprendre quel\n"
	.string "est notre POKéMON favori!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
	.string "BEA: Ohh…\n"
	.string "EVA!!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
	.string "BEA: C'était marrant, hein?\n"
	.string "J'espère qu'on se reverra.$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
	.string "BEA: J'aimerais beaucoup que tu\n"
	.string "nous affrontes, EVA et moi.\p"
	.string "Mais il te faudra plus d'un\n"
	.string "POKéMON.$"

ThreeIsland_BondBridge_Text_MegIntro::
	.string "EVA: Tu vas vite comprendre quel\n"
	.string "est notre POKéMON favori!$"

ThreeIsland_BondBridge_Text_MegDefeat::
	.string "EVA: Ohh…\n"
	.string "BEA!!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
	.string "EVA: C'était marrant, hein?\n"
	.string "J'espère qu'on se reverra.$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
	.string "EVA: J'aimerais beaucoup que tu\n"
	.string "nous affrontes BEA et moi.\p"
	.string "Mais il te faudra plus d'un\n"
	.string "POKéMON.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
	.string "BOIS BAIES\n"
	.string "DROIT DEVANT$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
	.string "PONT DU LIEN\n"
	.string "Silence en traversant.\p"
	.string "BOIS BAIES DROIT DEVANT$"

