Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "Pff… Un gosse, ça n'a jamais\n"
	.string "d'flouze!$"

Route17_Text_RaulDefeat::
	.string "Nan!!!\n"
	.string "Mon carbure!$"

Route17_Text_RaulPostBattle::
	.string "Y a plein de trucs qui traînent\n"
	.string "sur la PISTE CYCLABLE!$"

Route17_Text_IsaiahIntro::
	.string "Kess tu veux, toi l'mioche?$"

Route17_Text_IsaiahDefeat::
	.string "Whoua!$"

Route17_Text_IsaiahPostBattle::
	.string "Je vais t'éjecter d'ici à coup de\n"
	.string "claques!$"

Route17_Text_VirgilIntro::
	.string "Tu vas à PARMANIE?$"

Route17_Text_VirgilDefeat::
	.string "Argh!\n"
	.string "Fumé!$"

Route17_Text_VirgilPostBattle::
	.string "J'aime pédaler comme un dingue!\n"
	.string "Un giga-dingue!$"

Route17_Text_BillyIntro::
	.string "On est des MOTARDS!\n"
	.string "Des vrais, des purs, des durs,\l"
	.string "des méchants… Et tout et tout!$"

Route17_Text_BillyDefeat::
	.string "Nyargh!\n"
	.string "J'ai crevé une roue!$"

Route17_Text_BillyPostBattle::
	.string "Tu cherches l'aventure?$"

Route17_Text_NikolasIntro::
	.string "Mes VOLTORBE vont t'électrocuter!$"

Route17_Text_NikolasDefeat::
	.string "Arglagh!\n"
	.string "J'me suis fait électrocuter!$"

Route17_Text_NikolasPostBattle::
	.string "J'ai attrapé un VOLTORBE dans la\n"
	.string "CENTRALE.$"

Route17_Text_ZeekIntro::
	.string "Hein? Faire évoluer mes POKéMON?\n"
	.string "Ben pourquoi?$"

Route17_Text_ZeekDefeat::
	.string "Ha…\n"
	.string "OK, OK!$"

Route17_Text_ZeekPostBattle::
	.string "Certains POKéMON ont besoin d'une\n"
	.string "PIERRE pour évoluer.$"

Route17_Text_JamalIntro::
	.string "J'ai besoin d'un peu d'exercice!$"

Route17_Text_JamalDefeat::
	.string "Pfou!\n"
	.string "J'suis épuisé!$"

Route17_Text_JamalPostBattle::
	.string "Cool!\n"
	.string "J'ai perdu du poids!$"

Route17_Text_CoreyIntro::
	.string "No future!$"

Route17_Text_CoreyDefeat::
	.string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
	.string "Prépare-toi à la baston, microbe!$"

Route17_Text_JaxonIntro::
	.string "Mignon le VELO!\n"
	.string "Comment ça se conduit?$"

Route17_Text_JaxonDefeat::
	.string "Pan!\n"
	.string "Dans les dents!$"

Route17_Text_JaxonPostBattle::
	.string "La pente rend la conduite\n"
	.string "difficile!$"

Route17_Text_WilliamIntro::
	.string "Du vent toi!\n"
	.string "J'suis épuisé!$"

Route17_Text_WilliamDefeat::
	.string "Voilà, ça te va?$"

Route17_Text_WilliamPostBattle::
	.string "Je vais aller piquer un somme!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "Un conseil!\p"
	.string "Attention de ne pas jeter un objet\n"
	.string "important!$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "ASTUCE\p"
	.string "Chaque POKéMON est unique.\p"
	.string "Des POKéMON de même type et de\n"
	.string "même niveau évoluent différemment.$"

Route17_Text_PressBToStayInPlace::
	.string "ASTUCE\p"
	.string "Appuyez sur le bouton B pour\n"
	.string "vous arrêter dans une descente.$"

Route17_Text_RouteSign::
	.string "ROUTE 17\n"
	.string "CELADOPOLE - PARMANIE$"

Route17_Text_DontThrowGameThrowBalls::
	.string "Un conseil!\p"
	.string "Ne jetez pas la console, jetez\n"
	.string "plutôt des POKé BALLS.$"

Route17_Text_CyclingRoadSign::
	.string "PISTE CYCLABLE\n"
	.string "Fin de la descente!$"

