Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "Qui est là?\n"
	.string "Arrête de nous espionner!$"

Route6_Text_RickyDefeat::
	.string "…\n"
	.string "J'suis nul!$"

Route6_Text_RickyPostBattle::
	.string "Soupirs…\n"
	.string "Gros soupirs…$"

Route6_Text_NancyIntro::
	.string "Heu, c'est une conversation privée,\n"
	.string "DEGAGE!$"

Route6_Text_NancyDefeat::
	.string "Non!\n"
	.string "Je déteste perdre!$"

Route6_Text_NancyPostBattle::
	.string "Soupirs…\n"
	.string "Gros soupirs…$"

Route6_Text_KeigoIntro::
	.string "C'est plein d'insectes, ici.$"

Route6_Text_KeigoDefeat::
	.string "Non!\n"
	.string "C'est une blague!$"

Route6_Text_KeigoPostBattle::
	.string "Les insectes j'aime ça, je\n"
	.string "retourne dans la FORET DE JADE.$"

Route6_Text_JeffIntro::
	.string "Hein?\n"
	.string "Tu veux me causer?$"

Route6_Text_JeffDefeat::
	.string "…\n"
	.string "J'ai rien fait!$"

Route6_Text_JeffPostBattle::
	.string "Il me faut plus de POKéMON pour\n"
	.string "me protéger.$"

Route6_Text_IsabelleIntro::
	.string "Qui ça? Moi?\n"
	.string "OK. Attaque!$"

Route6_Text_IsabelleDefeat::
	.string "Oh!\n"
	.string "J'avais pas prévu ça!$"

Route6_Text_IsabellePostBattle::
	.string "Je veux être forte! Comme toi!\n"
	.string "C'est quoi ton secret?$"

Route6_Text_ElijahIntro::
	.string "J't'ai jamais vu dans le coin!\n"
	.string "T'es balèze?$"

Route6_Text_ElijahDefeat::
	.string "Whaa!\n"
	.string "Trop puissant!$"

Route6_Text_ElijahPostBattle::
	.string "Mes POKéMON sont nuls ou je suis\n"
	.string "très mauvais?$"

Route6_Text_UndergroundPathSign::
	.string "SOUTERRAIN\n"
	.string "AZURIA - CARMIN SUR MER$"

