SixIsland_OutcastIsland_Frlg_MapScripts::
	.byte 0

SixIsland_OutcastIsland_EventScript_Rocket::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
	end

SixIsland_OutcastIsland_Text_RocketIntro::
	.string "Il n'y a pas de POKéMON rare\n"
	.string "par ici! Pas un seul!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "… Hein?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "Dis-moi, t'as pas vu de POKéMON\n"
	.string "rare, hein?$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "J'ai pas du tout de chance.\p"
	.string "Il me faudrait une victoire pour\n"
	.string "me remonter le moral.$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "Non, pas de chance du tout…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "Je ne peux pas rentrer chez moi\n"
	.string "sans avoir attrapé quelque chose.\p"
	.string "J'crois que je suis pas près de\n"
	.string "rentrer…$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "Haaa… Haaaa…\p"
	.string "Je suis venu jusqu'ici depuis le\n"
	.string "port de l'ILE 6 sans m'arrêter.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "Haaa… Haaaa…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "Je n'ai fait que la moitié…\n"
	.string "J'suis crevé…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "C'est pas facile d'envoyer des\n"
	.string "POKéMON tout en nageant, tu sais?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "Au moins j'ai pas perdu à la nage…$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "Est-ce que tu vas sur l'île qui se\n"
	.string "trouve plus loin?\p"
	.string "Je n'ai pas vu grand chose\n"
	.string "d'intéressant là-bas.$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "AVA: C'est parti pour un combat\n"
	.string "marin deux contre deux!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "AVA: Oh, t'es formidable!\n"
	.string "J'dirais même plus, t'es unique!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "AVA: Tu sais, je préfère mille fois\n"
	.string "la mer à toutes les piscines.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "AVA: Tu veux te battre contre\n"
	.string "nous?\p"
	.string "Pour ça, il te faut au moins\n"
	.string "deux POKéMON.$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "GED: Grande sœur, au secours!\n"
	.string "Viens te battre avec moi!$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "GED: Grande sœur, j'ai sous-estimé\n"
	.string "ce combat.$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "GED: je m'accroche à ma sœur\n"
	.string "parce que j'ai pas pied.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "GED: Allez, viens te battre avec\n"
	.string "nous!\p"
	.string "…Oh, t'as pas deux POKéMON?$"
