Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "Utilise des CT pour apprendre de\n"
	.string "bonnes attaques à tes POKéMON!$"

Route14_Text_CarterDefeat::
	.string "…\n"
	.string "Pas encore assez bon!$"

Route14_Text_CarterPostBattle::
	.string "Tu as des CS?\n"
	.string "Les POKéMON ne peuvent pas\l"
	.string "les oublier.$"

Route14_Text_MitchIntro::
	.string "Mes POKéMON oiseau veulent\n"
	.string "se battre.$"

Route14_Text_MitchDefeat::
	.string "…\n"
	.string "Y veulent plus!$"

Route14_Text_MitchPostBattle::
	.string "Il leur faut de bonnes attaques.$"

Route14_Text_BeckIntro::
	.string "On vend des CT au CENTRE\n"
	.string "COMMERCIAL de CELADOPOLE!\p"
	.string "Mais, seuls quelques élus ont\n"
	.string "des CS!$"

Route14_Text_BeckDefeat::
	.string "Ah!\n"
	.string "Fiasco complet!$"

Route14_Text_BeckPostBattle::
	.string "Apprends à tes POKéMON des\n"
	.string "attaques de leur type.\p"
	.string "Apparemment, ça booste la\n"
	.string "puissance de l'attaque.$"

Route14_Text_MarlonIntro::
	.string "As-tu appris VOL à tes POKéMON\n"
	.string "oiseau?\p"
	.string "Grâce à ça, tu pourras voyager\n"
	.string "dans le ciel sur leur dos.$"

Route14_Text_MarlonDefeat::
	.string "Ah!\n"
	.string "Je me suis brûlé les ailes!$"

Route14_Text_MarlonPostBattle::
	.string "J'adore les POKéMON oiseau,\n"
	.string "je ne m'intéresse qu'à eux!$"

Route14_Text_DonaldIntro::
	.string "Connais-tu la légende des\n"
	.string "mirages ailés?$"

Route14_Text_DonaldDefeat::
	.string "Ah?\n"
	.string "J'ai perdu?$"

Route14_Text_DonaldPostBattle::
	.string "Les mirages ailés seraient les\n"
	.string "POKéMON oiseau légendaires.\p"
	.string "Ils sont trois: ARTIKODIN,\n"
	.string "ELECTHOR et SULFURA.$"

Route14_Text_BennyIntro::
	.string "J'suis pas d'humeur! Mais bon…$"

Route14_Text_BennyDefeat::
	.string "Ben, t'as gagné, non?$"

Route14_Text_BennyPostBattle::
	.string "Perdre ou gagner, c'est pas le plus\n"
	.string "important!$"

Route14_Text_LukasIntro::
	.string "Allez, viens! Tu vas voir la tête\n"
	.string "de tes POKéMON!$"

Route14_Text_LukasDefeat::
	.string "Arrg!\n"
	.string "Hors de ma vue!$"

Route14_Text_LukasPostBattle::
	.string "Quoi? Quoi?\n"
	.string "Tu veux quoi?$"

Route14_Text_IsaacIntro::
	.string "Parfait!\n"
	.string "Je m'ennuyais!$"

Route14_Text_IsaacDefeat::
	.string "Quoi?\n"
	.string "Me faire battre par toi?$"

Route14_Text_IsaacPostBattle::
	.string "Elever des POKéMON, c'est crevant!$"

Route14_Text_GeraldIntro::
	.string "Y'a plein de place pour les\n"
	.string "balades ici!$"

Route14_Text_GeraldDefeat::
	.string "Balayé!$"

Route14_Text_GeraldPostBattle::
	.string "Cool, tes POKéMON sont super\n"
	.string "balèzes!\p"
	.string "La force, c'est important, mais\n"
	.string "tu le sais, non?$"

Route14_Text_MalikIntro::
	.string "Un combat de POKéMON?\n"
	.string "Tremble, minable!$"

Route14_Text_MalikDefeat::
	.string "J'suis dans l'vent!$"

Route14_Text_MalikPostBattle::
	.string "Tu sais que sans tes POKéMON,\n"
	.string "je te pulvérise!$"

Route14_Text_RouteSign::
	.string "ROUTE 14\n"
	.string "PARMANIE à l'Ouest$"

Route14_Text_KiriIntro::
	.string "JOY: KATE, essayons ensemble!$"

Route14_Text_KiriDefeat::
	.string "JOY: …\n"
	.string "On a perdu, hein?$"

Route14_Text_KiriPostBattle::
	.string "JOY: On a perdu à cause de moi?$"

Route14_Text_KiriNotEnoughMons::
	.string "JOY: On pourra se battre si tu\n"
	.string "viens avec deux POKéMON.$"

Route14_Text_JanIntro::
	.string "KATE: Allons-y!\n"
	.string "Faisons de notre mieux!$"

Route14_Text_JanDefeat::
	.string "KATE: Aaaah!\n"
	.string "C'est pas juste!$"

Route14_Text_JanPostBattle::
	.string "KATE: Ne pleure pas JOY!\n"
	.string "On fera mieux la prochaine fois.$"

Route14_Text_JanNotEnoughMons::
	.string "KATE: Tu veux te battre?\n"
	.string "Mais t'as pas assez de POKéMON!$"
