SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "JULIA: Où est NICO, mon petit ami?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Je capture des POKéMON pour\n"
	.string "les offrir!$"

