Route20_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route20_OnTransition
	.byte 0

Route20_OnTransition::
	call_if_unset FLAG_STOPPED_SEAFOAM_B3F_CURRENT, Route20_EventScript_ResetSeafoamBouldersForB3F
	call_if_unset FLAG_STOPPED_SEAFOAM_B4F_CURRENT, Route20_EventScript_ResetSeafoamBouldersForB4F
	end

Route20_EventScript_ResetSeafoamBouldersForB3F::
	clearflag FLAG_HIDE_SEAFOAM_1F_BOULDER_1
	clearflag FLAG_HIDE_SEAFOAM_1F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B1F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B1F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B2F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B2F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_2
	return

Route20_EventScript_ResetSeafoamBouldersForB4F::
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_3
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_4
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_5
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_6
	setflag FLAG_HIDE_SEAFOAM_B4F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B4F_BOULDER_2
	return

Route20_EventScript_SeafoamIslandsSign::
	msgbox Route20_Text_SeafoamIslands, MSGBOX_SIGN
	end

Route20_Text_BarryIntro::
	.string "La mer est peu profonde ici,\n"
	.string "n'est-ce pas?$"

Route20_Text_BarryDefeat::
	.string "Splash!$"

Route20_Text_BarryPostBattle::
	.string "Ah, si je pouvais monter sur mes\n"
	.string "POKéMON.$"

Route20_Text_ShirleyIntro::
	.string "Les ILES ECUME sont tranquilles!$"

Route20_Text_ShirleyDefeat::
	.string "Nyann!$"

Route20_Text_ShirleyPostBattle::
	.string "Il y a une grande caverne sous\n"
	.string "cette île.$"

Route20_Text_TiffanyIntro::
	.string "J'aime faire la planche avec les\n"
	.string "poissons!$"

Route20_Text_TiffanyDefeat::
	.string "Glargh!$"

Route20_Text_TiffanyPostBattle::
	.string "Tu veux nager avec moi?$"

Route20_Text_IreneIntro::
	.string "T'es en vacances toi aussi?$"

Route20_Text_IreneDefeat::
	.string "Non!\n"
	.string "Pas de pitié!$"

Route20_Text_IrenePostBattle::
	.string "Avant, ben, les ILES ECUMES ne\n"
	.string "formaient qu'une seule île!$"

Route20_Text_DeanIntro::
	.string "Mate un peu mon corps de rêve!\n"
	.string "C'est beau hein?$"

Route20_Text_DeanDefeat::
	.string "Aïeu!$"

Route20_Text_DeanPostBattle::
	.string "J'aurais dû entraîner un peu\n"
	.string "plus mes POKéMON!$"

Route20_Text_DarrinIntro::
	.string "Ben, t'es sur un POKéMON, tu sais\n"
	.string "pas nager?$"

Route20_Text_DarrinDefeat::
	.string "Ouch!\n"
	.string "Je coule!$"

Route20_Text_DarrinPostBattle::
	.string "Surfer sur un POKéMON, c'est cool!$"

Route20_Text_RogerIntro::
	.string "Mes POKéMON oiseau m'ont\n"
	.string "déposé ici!$"

Route20_Text_RogerDefeat::
	.string "Oh!\n"
	.string "NOoOoOon!$"

Route20_Text_RogerPostBattle::
	.string "Mes oiseaux sont trop fatigués\n"
	.string "pour utiliser VOL!$"

Route20_Text_NoraIntro::
	.string "Mon p'tit copain m'a offert des\n"
	.string "perles sublimes!$"

Route20_Text_NoraDefeat::
	.string "Non!\n"
	.string "Mes perles étaient dedans!$"

Route20_Text_NoraPostBattle::
	.string "Et si je mettais mes perles dans un\n"
	.string "CRUSTABRI?$"

Route20_Text_MissyIntro::
	.string "J'ai nagé depuis CRAMOIS'ILE!$"

Route20_Text_MissyDefeat::
	.string "J'ai bu la tasse!$"

Route20_Text_MissyPostBattle::
	.string "Des POKéMON infestent un vieux\n"
	.string "manoir de CRAMOIS'ILE!\p"
	.string "On l'appelle le MANOIR POKéMON.$"

Route20_Text_MelissaIntro::
	.string "Il y a un LABO POKéMON à\n"
	.string "CRAMOIS'ILE.$"

Route20_Text_MelissaDefeat::
	.string "Attends!$"

Route20_Text_MelissaPostBattle::
	.string "CRAMOIS'ILE est une île\n"
	.string "volcanique!$"

Route20_Text_SeafoamIslands::
	.string "ILES ECUME$"

Route20_Text_MistyTrainsHere::
	.string "On voit souvent des DRESSEURS\n"
	.string "avec des POKéMON EAU par ici.\p"
	.string "Ils disent qu'ONDINE de l'ARENE\n"
	.string "d'AZURIA s'entraîne dans le coin.$"
