CeladonCity_Hotel_Frlg_MapScripts::
	.byte 0

CeladonCity_Hotel_EventScript_Receptionist::
	msgbox CeladonCity_Hotel_Text_ThisHotelIsForPeople, MSGBOX_NPC
	end

CeladonCity_Hotel_EventScript_Beauty::
	msgbox CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend, MSGBOX_NPC
	end

CeladonCity_Hotel_EventScript_BeautyBoyfriend::
	msgbox CeladonCity_Hotel_Text_WhyDidSheBringBrother, MSGBOX_NPC
	end

CeladonCity_Hotel_EventScript_BeautyBrother::
	msgbox CeladonCity_Hotel_Text_SisBroughtMeOnVacation, MSGBOX_NPC
	end

CeladonCity_Hotel_Text_ThisHotelIsForPeople::
	.string "Des POKéMON quoi?\n"
	.string "C'est un hôtel ici…\p"
	.string "Et c'est complet.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
	.string "Je suis en vacances avec mon\n"
	.string "frère et mon petit ami.\p"
	.string "CELADOPOLE est si belle!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
	.string "Pourquoi?\n"
	.string "Mais pourquoi y'a son frère?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
	.string "Je suis en vacances avec ma\n"
	.string "sœur… Ça craint à mort!$"

