Route16_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_RESUME, Route16_OnResume
	map_script MAP_SCRIPT_ON_TRANSITION, Route16_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route16_OnWarp
	.byte 0

Route16_OnResume::
	call_if_set FLAG_SYS_CTRL_OBJ_DELETE, Route16_EventScript_RemoveSnorlax
	end

Route16_EventScript_RemoveSnorlax::
	removeobject VAR_LAST_TALKED
	return

Route16_OnTransition::
	call_if_eq VAR_MAP_SCENE_ROUTE16, 1, Route16_OnTransitionCyclingRoad
	end

Route16_OnTransitionCyclingRoad::
	setflag FLAG_SYS_ON_CYCLING_ROAD
	return

Route16_OnWarp::
	map_script_2 VAR_MAP_SCENE_ROUTE16, 1, Route16_OnWarpCyclingRoad
	.2byte 0

Route16_OnWarpCyclingRoad::
	special ForcePlayerOntoBike
	end

Route16_EventScript_Snorlax::
	lock
	faceplayer
	goto_if_unset FLAG_GOT_POKE_FLUTE, Route16_EventScript_SnorlaxNoPokeFlute
	msgbox Text_WantToUsePokeFlute, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, Route16_EventScript_DontUsePokeFlute
	call EventScript_AwakenSnorlax
	setwildbattle SPECIES_SNORLAX, 30
	waitse
	playmoncry SPECIES_SNORLAX, CRY_MODE_ENCOUNTER
	delay 40
	waitmoncry
	setflag FLAG_HIDE_ROUTE_16_SNORLAX
	setflag FLAG_SYS_CTRL_OBJ_DELETE
	dowildbattle
	clearflag FLAG_SYS_CTRL_OBJ_DELETE
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_WON, Route16_EventScript_FoughtSnorlax
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, Route16_EventScript_FoughtSnorlax
	goto_if_eq VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED, Route16_EventScript_FoughtSnorlax
	release
	end

Route16_EventScript_DontUsePokeFlute::
	release
	end

Route16_EventScript_FoughtSnorlax::
	msgbox Text_SnorlaxReturnedToMountains
	release
	end

Route16_EventScript_SnorlaxNoPokeFlute::
	msgbox Route16_Text_MonSprawledOutInSlumber
	release
	end

Route16_EventScript_CyclingRoadSign::
	msgbox Route16_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route16_EventScript_RouteSign::
	msgbox Route16_Text_RouteSign, MSGBOX_SIGN
	end

Route16_Text_LaoIntro::
	.string "Kess t'as ta?$"

Route16_Text_LaoDefeat::
	.string "…\n"
	.string "Galère!$"

Route16_Text_LaoPostBattle::
	.string "Nous? On squatte ici…\n"
	.string "Et toi?$"

Route16_Text_KojiIntro::
	.string "Joli VELO!\n"
	.string "Donne-le moi!$"

Route16_Text_KojiDefeat::
	.string "Tu peux garder ton VELO!$"

Route16_Text_KojiPostBattle::
	.string "Je le veux pas ton VELO!$"

Route16_Text_LukeIntro::
	.string "Viens t'battre!\n"
	.string "Sale fouine!$"

Route16_Text_LukeDefeat::
	.string "Toi!!\n"
	.string "Espèce de fennec!$"

Route16_Text_LukePostBattle::
	.string "Je déteste perdre…\n"
	.string "Surtout dans ces conditions!$"

Route16_Text_HideoIntro::
	.string "Hé!\n"
	.string "Tu viens de me rentrer dedans, là?$"

Route16_Text_HideoDefeat::
	.string "Schplaff!$"

Route16_Text_HideoPostBattle::
	.string "On restera là, que ça te plaise\n"
	.string "ou pas!\p"
	.string "Tu peux aussi aller de CARMIN\n"
	.string "SUR MER à PARMANIE par la côte.$"

Route16_Text_CamronIntro::
	.string "J'ai faim, j'suis furax et j'vais\n"
	.string "t'exploser!$"

Route16_Text_CamronDefeat::
	.string "Grrr!\n"
	.string "J'suis encore plus furax!$"

Route16_Text_CamronPostBattle::
	.string "Mes POKéMON sont féroces!\n"
	.string "Ils déchirent mes ennemis!$"

Route16_Text_RubenIntro::
	.string "BASTOONNNN!$"

Route16_Text_RubenDefeat::
	.string "Bah!\n"
	.string "M'énerve pas!$"

Route16_Text_RubenPostBattle::
	.string "Je terrorise mes adversaires avec\n"
	.string "mes POKéMON super vicieux!\p"
	.string "Ils sont super pour faire flipper.\n"
	.string "Et en plus ils mordent!$"

Route16_Text_MonSprawledOutInSlumber::
	.string "Un gros POKéMON endormi bloque\n"
	.string "le chemin!$"

Route16_Text_CyclingRoadSign::
	.string "Bonne descente!\n"
	.string "PISTE CYCLABLE$"

Route16_Text_RouteSign::
	.string "ROUTE 16\n"
	.string "CELADOPOLE - PARMANIE$"

Route16_Text_JedIntro::
	.string "ALI: Notre amour n'a pas de limite.\n"
	.string "On s'aime et on le montre!$"

Route16_Text_JedDefeat::
	.string "ALI: Noon, mon amour va me\n"
	.string "prendre pour un perdant.$"

Route16_Text_JedPostBattle::
	.string "ALI: Ecoute LISE, c'est au combat\n"
	.string "que tu dois penser, pas à moi.$"

Route16_Text_JedNotEnoughMons::
	.string "ALI: Tu n'as qu'un POKéMON?\p"
	.string "N'y a-t-il pas de place dans\n"
	.string "ton cœur?$"

Route16_Text_LeaIntro::
	.string "LISE: Je suis parfois effrayée par\n"
	.string "la force de notre amour.$"

Route16_Text_LeaDefeat::
	.string "LISE: Mais je le trouve beau même\n"
	.string "quand il perd.$"

Route16_Text_LeaPostBattle::
	.string "LISE: Je suis désolée.\n"
	.string "Je pensais à ALI.$"

Route16_Text_LeaNotEnoughMons::
	.string "LISE: Tu n'as qu'un POKéMON?\p"
	.string "Tu n'as pas peur qu'il se sente\n"
	.string "un peu seul?$"
