SafariZone_East_Frlg_MapScripts::
	.byte 0

SafariZone_East_EventScript_RestHouseSign::
	msgbox SafariZone_East_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_East_EventScript_TrainerTips::
	msgbox SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk, MSGBOX_SIGN
	end

SafariZone_East_EventScript_AreaSign::
	msgbox SafariZone_East_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_East_Text_RestHouse::
	.string "ABRI$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
	.string "ASTUCE\p"
	.string "Le temps s'écoule en fonction\n"
	.string "des pas!$"

SafariZone_East_Text_AreaSign::
	.string "PARC 1\n"
	.string "OUEST: PARC CENTRAL$"

