@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Des bouquins sur les POKéMON!$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Une CARTE.$"

Text_PokeMartShelf::
	.string "Cool! Plein de machins sur les\n"
	.string "POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "De la vaisselle est rangée\n"
	.string "dans ce placard.$"

Text_Kitchen::
	.string "Quelqu'un a cuisiné ici,\n"
	.string "ça sent vraiment bon.$"

Text_Dresser::
	.string "C'est une belle commode.\n"
	.string "On peut y ranger plein de trucs.$"

Text_Snacks::
	.string "Il y a plusieurs sandwichs.$"

Text_PokemartSign::
	.string "Faites le plein d'objets!\n"
	.string "BOUTIQUE POKéMON$"

Text_PokecenterSign::
	.string "Soignez vos POKéMON!\n"
	.string "CENTRE POKéMON$"

Text_Indigo_UltimateGoal::
	.string "PLATEAU INDIGO\p"
	.string "Le rêve de tout DRESSEUR!\n"
	.string "Quartier général de la LIGUE\l"
	.string "POKéMON$"

Text_Indigo_HighestAuthority::
	.string "PLATEAU INDIGO\p"
	.string "La plus haute instance POKéMON.\n"
	.string "Quartier général de la LIGUE\l"
	.string "POKéMON$"

Text_Food::
	.string "Il doit y avoir plein de bonnes\n"
	.string "choses à manger.$"

Text_Blueprints::
	.string "C'est une sorte de plan. Il y a\n"
	.string "quelque chose d'écrit dessus.$"

Text_Painting::
	.string "Une belle image d'un POKéMON.\n"
	.string "Il semble heureux.$"

Text_PowerPlantMachine::
	.string "A quoi ça peut bien servir? Mieux\n"
	.string "vaut ne pas y toucher!$"

Text_Telephone::
	.string "C'est un téléphone. Il vaut mieux\n"
	.string "ne pas l'utiliser.$"

Text_Computer::
	.string "C'est rempli de mots et de chiffres\n"
	.string "incompréhensibles.$"

Text_AdvertisingPoster::
	.string "C'est une publicité pour de\n"
	.string "nombreux articles.$"

Text_TastyFood::
	.string "Mmm, quelle bonne odeur.\n"
	.string "Ça donne vraiment faim!$"

Text_TrashBin::
	.string "Alors ici…\n"
	.string "… …\p"
	.string "Il n'y a absolument rien!$"

Text_Cup::
	.string "C'est une tasse avec une\n"
	.string "marque de POKéMON.$"

Text_PolishedWindow::
	.string "La fenêtre est super propre!$"

Text_BeautifulSkyWindow::
	.string "A l'extérieur…\p"
	.string "Il fait un temps magnifique!$"

Text_BlinkingLights::
	.string "Il y a plein de petites lampes\n"
	.string "qui clignotent.$"

Text_NeatlyLinedUpTools::
	.string "Plusieurs outils sont rangés ici.$"

Text_ImpressiveMachine::
	.string "C'est une sorte de machine.\n"
	.string "Elle est vraiment impressionnante.$"

Text_VideoGame::
	.string "Le dernier jeu vidéo qui vient de\n"
	.string "sortir. Ça a l'air génial.$"

Text_Burglary::
	.string "Il y a des signes d'effraction ici…$"

Text_PlayerFacingTVScreen::
	.string "Une émission avec des POKéMON.\n"
	.string "Ça a l'air cool!$"
