gText_HowMayIServeYou::
    .string "Bienvenue!\p"
    .string "En quoi puis-je vous aider?$"

gText_PleaseComeAgain::
    .string "A la prochaine!$"

gText_PlayerWhatCanIDoForYou::
    .string "Bienvenue {PLAYER}{KUN}!\p"
    .string "Que puis-je faire pour vous?$"

Pokemart_DefaultItemList::
    .2byte ITEM_ULTRA_BALL
    .2byte ITEM_HYPER_POTION
    .2byte ITEM_MAX_POTION
    .2byte ITEM_FULL_RESTORE
    .2byte ITEM_FULL_HEAL
    .2byte ITEM_REVIVE
    .2byte ITEM_MAX_REPEL
    pokemartlistend
