ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "Tu ne dois jamais, je dis bien\n"
	.string "jamais, aller aux BOIS BAIES.\p"
	.string "Pourquoi? Mais parce qu'ils sont\n"
	.string "remplis de fantômes.$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "Papa arrête pas de me mentir\n"
	.string "pour que j'aille pas jouer dehors.$"

