PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "Les secrets de l'espace…\n"
	.string "Les mystères de la terre…\p"
	.string "Il y a tant de choses que nous\n"
	.string "ne comprenons pas encore.\p"
	.string "Mais cela doit nous motiver à\n"
	.string "apprendre davantage.\p"
	.string "D'ailleurs, désires-tu que\n"
	.string "j'apprenne FRAPPE ATLAS\p"
	.string "à un de tes POKéMON?$"

Text_SeismicTossDeclined::
	.string "Vraiment?\n"
	.string "Tu me déçois.$"

Text_SeismicTossWhichMon::
	.string "A quel POKéMON dois-je l'enseigner?$"

Text_SeismicTossTaught::
	.string "Je suis sûr que ça te sera\n"
	.string "utile. Bon courage.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "PIERRE LUNE?\p"
	.string "Ouais? Et alors?$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "20 Juillet 1969!\p"
	.string "L'homme a marché sur la lune!\p"
	.string "J'ai acheté une télé couleur pour\n"
	.string "voir toutes les nuances de la lune!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "Nous faisons une exposition sur\n"
	.string "l'espace.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "Je veux un PIKACHU!\p"
	.string "Papa va m'en trouver un!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "Oui, oui, tu vas l'avoir ton\n"
	.string "PIKACHU… C'est ça.$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "NAVETTE SPATIALE$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "Un météore du MONT SELENITE.\n"
	.string "Serait-ce une PIERRE LUNE?$"

