SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "Tiens! J'ai vu des POKéMON\n"
	.string "transporter des gens sur l'eau!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "Les POKéMON peuvent couper des\n"
	.string "petits buissons avec COUPE.\p"
	.string "Mais n'oublie pas! COUPE est\n"
	.string "une CS.\p"
	.string "Une fois apprise, on ne peut pas\n"
	.string "facilement l'oublier.$"

