SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Tu peux garder tous les objets\n"
	.string "trouvés dans le coin.\p"
	.string "Mais ne perds pas de temps à tous\n"
	.string "les essayer!$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Le coin le plus reculé du PARC\n"
	.string "SAFARI cache un prix spécial!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Mon EVOLI s'est transformé en\n"
	.string "PYROLI!\p"
	.string "Mais celui d'un ami s'est changé\n"
	.string "en AQUALI! Bah pourquoi?$"

