Route2_ViridianForest_SouthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
	.string "Vas-tu dans la FORET DE JADE?\n"
	.string "Fais bien attention de ne pas te\l"
	.string "perdre, c'est un vrai labyrinthe!$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
	.string "RATTATA est petit mais il est\n"
	.string "sournois! En as-tu capturé un?$"

