@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Je m'occupe de la PENSION.\p"
	.string "Veux-tu que j'élève un de tes\n"
	.string "POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "A plus tard.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Quel POKéMON veux-tu me confier?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Je vois.\n"
	.string "Reviens me voir.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Très bien, je vais m'occuper de\n"
	.string "{STR_VAR_1}.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Reviens un peu plus tard.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Déjà de retour?\p"
	.string "Ton {STR_VAR_1} doit rester encore\n"
	.string "un peu.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Donne-moi {STR_VAR_2}¥ pour que\n"
	.string "je te rende ton POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Merci!\n"
	.string "Voilà ton p'tit POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} récupère\n"
	.string "{STR_VAR_1}!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Oh!\n"
	.string "Tu n'as qu'un POKéMON sur toi.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Si tu me le laisses, avec quoi\n"
	.string "vas-tu pouvoir combattre?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Ton {STR_VAR_1} a bien grandi!\p"
	.string "Il a {STR_VAR_2} niveau(x)\n"
	.string "de plus!\p"
	.string "Merci qui? Hein?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Tu n'as plus de place pour ce\n"
	.string "POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Hé! Tu n'as pas assez d'argent!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"
