Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "Pfou… Je vais faire une halte.\n"
	.string "Moouarf…\p"
	.string "Ce tunnel venant d'AZURIA\n"
	.string "est épuisant!$"

Route3_Text_ColtonIntro::
	.string "Hé! On s'est déjà vus dans la\n"
	.string "FORET DE JADE!$"

Route3_Text_ColtonDefeat::
	.string "Ben, tu m'as encore battu!$"

Route3_Text_ColtonPostBattle::
	.string "Il y a beaucoup de POKéMON\n"
	.string "différents dans la forêt!$"

Route3_Text_BenIntro::
	.string "Yahaa!\n"
	.string "J'adore les shorts! Viens t'battre!$"

Route3_Text_BenDefeat::
	.string "Nyahaa, tu m'as taillé un short!$"

Route3_Text_BenPostBattle::
	.string "Pour ranger tes POKéMON,\n"
	.string "utilise un PC.\p"
	.string "Chaque boîte contient 30 POKéMON!$"

Route3_Text_JaniceIntro::
	.string "Tu veux ma photo?$"

Route3_Text_JaniceDefeat::
	.string "Tiens, c'est ma photo!$"

Route3_Text_JanicePostBattle::
	.string "Baisse les yeux si tu veux éviter\n"
	.string "la baston!$"

Route3_Text_GregIntro::
	.string "T'es un DRESSEUR?\n"
	.string "A l'attaque!$"

Route3_Text_GregDefeat::
	.string "Avec d'autres POKéMON,\n"
	.string "j'aurais gagné!$"

Route3_Text_GregPostBattle::
	.string "Quand l'une des boîtes de ton PC\n"
	.string "est pleine, active une autre boîte!$"

Route3_Text_SallyIntro::
	.string "Ce regard que tu m'as lancé…\n"
	.string "C'est plutôt intrigant.$"

Route3_Text_SallyDefeat::
	.string "Hmmm…\n"
	.string "Sois plus sympa!$"

Route3_Text_SallyPostBattle::
	.string "Evite les regards si tu ne veux\n"
	.string "pas combattre!$"

Route3_Text_CalvinIntro::
	.string "Hé! T'as pas de short!\n"
	.string "Tu crains!$"

Route3_Text_CalvinDefeat::
	.string "Perdu!\n"
	.string "Perdu, et perdu!$"

Route3_Text_CalvinPostBattle::
	.string "Je porte toujours des shorts, même\n"
	.string "en hiver!$"

Route3_Text_JamesIntro::
	.string "Fais gaffe à mes nouveaux\n"
	.string "POKéMON!$"

Route3_Text_JamesDefeat::
	.string "Ben, y m'en faut des nouveaux!$"

Route3_Text_JamesPostBattle::
	.string "Les POKéMON dressés sont plus\n"
	.string "forts que les POKéMON sauvages!$"

Route3_Text_RobinIntro::
	.string "Hé!\n"
	.string "Tu m'as poussée là?$"

Route3_Text_RobinDefeat::
	.string "OK!$"

Route3_Text_RobinPostBattle::
	.string "La ROUTE 4 est au pied du MONT\n"
	.string "SELENITE.$"

Route3_Text_RouteSign::
	.string "ROUTE 3\n"
	.string "MONT SELENITE DROIT DEVANT$"

