OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "Se faire balloter par les vagues…\n"
	.string "J'adore!$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "J'ai perdu…\n"
	.string "C'est vraiment trop injuste.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "L'eau est vraiment à la température\n"
	.string "idéale par ici.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "Le courant dépose souvent plein\n"
	.string "d'objets sur la plage.\p"
	.string "Je viens souvent voir s'il n'y a\n"
	.string "rien d'intéressant à trouver.$"

