Route15_Frlg_MapScripts::
	.byte 0

Route15_EventScript_RouteSign::
	msgbox Route15_Text_RouteSign, MSGBOX_SIGN
	end

Route15_Text_KindraIntro::
	.string "Je vais tester les POKéMON que\n"
	.string "j'ai échangés!$"

Route15_Text_KindraDefeat::
	.string "Oh!\n"
	.string "Perdu!$"

Route15_Text_KindraPostBattle::
	.string "Tu ne peux pas renommer un\n"
	.string "POKéMON échangé.\p"
	.string "Seul son premier DRESSEUR\n"
	.string "peut le faire.$"

Route15_Text_BeckyIntro::
	.string "T'as l'air stupide, je devrais\n"
	.string "pouvoir te battre!$"

Route15_Text_BeckyDefeat::
	.string "Pas si stupide en fait!$"

Route15_Text_BeckyPostBattle::
	.string "Les MOTARDS me font peur, ils sont\n"
	.string "si méchants!$"

Route15_Text_EdwinIntro::
	.string "Je peux appeler des POKéMON\n"
	.string "oiseau rien qu'en sifflant!$"

Route15_Text_EdwinDefeat::
	.string "Oh!\n"
	.string "J'le crois pas!$"

Route15_Text_EdwinPostBattle::
	.string "Je ne suis pas doué pour les\n"
	.string "bastons.$"

Route15_Text_ChesterIntro::
	.string "Hmm? Mes oiseaux ont peur!\n"
	.string "T'es fortiche, toi?$"

Route15_Text_ChesterDefeat::
	.string "…\n"
	.string "C'est bien ce que je pensais!$"

Route15_Text_ChesterPostBattle::
	.string "Les attaques comme SEISME ou\n"
	.string "ABIME ne font rien aux oiseaux.\p"
	.string "Tu l'savais?$"

Route15_Text_GraceIntro::
	.string "Oh! T'es bien jeune, toi!$"

Route15_Text_GraceDefeat::
	.string "T'étais adorable, pourtant!$"

Route15_Text_GracePostBattle::
	.string "Je te pardonne!\n"
	.string "T'es trop adorable!$"

Route15_Text_OliviaIntro::
	.string "J'ai des POKéMON pour me protéger\n"
	.string "comme je vis toute seule!$"

Route15_Text_OliviaDefeat::
	.string "Pour moi, les POKéMON ce n'est\n"
	.string "pas juste gagner ou perdre.$"

Route15_Text_OliviaPostBattle::
	.string "Je rentre chez moi pour être avec\n"
	.string "mes POKéMON!$"

Route15_Text_ErnestIntro::
	.string "Hé, toi!\n"
	.string "Regarde ça!$"

Route15_Text_ErnestDefeat::
	.string "Pourquoi pas?$"

Route15_Text_ErnestPostBattle::
	.string "On ne vit qu'une fois! C'est pour\n"
	.string "ça que je suis méchant, nyark!$"

Route15_Text_AlexIntro::
	.string "La bourse ou la vie!$"

Route15_Text_AlexDefeat::
	.string "C'est pas possible!$"

Route15_Text_AlexPostBattle::
	.string "Heu…\n"
	.string "Pour l'argent, je plaisantais!$"

Route15_Text_CeliaIntro::
	.string "Quoi? Echanger des POKéMON\n"
	.string "c'est cool?$"

Route15_Text_CeliaDefeat::
	.string "Hé! Je parlais d'échanges, pas de\n"
	.string "bastons!$"

Route15_Text_CeliaPostBattle::
	.string "J'échange des POKéMON avec\n"
	.string "mes amis!$"

Route15_Text_YazminIntro::
	.string "Je veux me battre avec mes\n"
	.string "POKéMON!$"

Route15_Text_YazminDefeat::
	.string "…\n"
	.string "J'étais trop impatiente!$"

Route15_Text_YazminPostBattle::
	.string "Je vais me battre avec des\n"
	.string "DRESSEURS moins forts!$"

Route15_Text_RouteSign::
	.string "ROUTE 15\n"
	.string "PARMANIE à l'Ouest$"

Route15_Text_MyaIntro::
	.string "MYA: On dirait que tu sais\n"
	.string "te battre.\p"
	.string "Tu aurais un instant pour qu'on\n"
	.string "entraîne mon petit frère?$"

Route15_Text_MyaDefeat::
	.string "MYA: RON, tu dois te concentrer!\n"
	.string "Pense à ce que tu fais!$"

Route15_Text_MyaPostBattle::
	.string "MYA: OK, il va falloir revoir mon\n"
	.string "programme d'entraînement.$"

Route15_Text_MyaNotEnoughMons::
	.string "MYA: Tu veux vraiment nous\n"
	.string "affronter?\p"
	.string "Et tu ne sais pas qu'il te faut\n"
	.string "deux POKéMON pour ça?$"

Route15_Text_RonIntro::
	.string "RON: Ma sœur me fait peur quand\n"
	.string "on perd.$"

Route15_Text_RonDefeat::
	.string "RON: Oh non…\n"
	.string "Désolé grande sœur.$"

Route15_Text_RonPostBattle::
	.string "RON: … Elle me\n"
	.string "traite comme un gamin.$"

Route15_Text_RonNotEnoughMons::
	.string "RON: Tu veux te battre contre nous\n"
	.string "deux? Avec un seul POKéMON?$"
