Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "T'es dingue des POKéMON?\n"
	.string "Tu veux voir ma collec'?$"

Route10_Text_MarkDefeat::
	.string "Nyan!\n"
	.string "Ma belle collec'!$"

Route10_Text_MarkPostBattle::
	.string "A la maison, j'ai plein de POKéMON\n"
	.string "super rares!$"

Route10_Text_ClarkIntro::
	.string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
	.string "Ha!\n"
	.string "Je ris pas!\l"
	.string "C'est les nerfs!$"

Route10_Text_ClarkPostBattle::
	.string "Haha-ha-ha!\n"
	.string "Nyahahahaha!\l"
	.string "Hohohoho!$"

Route10_Text_HermanIntro::
	.string "Hé, toi!\n"
	.string "Tu veux voir mes POKéMON?$"

Route10_Text_HermanDefeat::
	.string "Yah!\n"
	.string "Mes POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "Je t'aime pas et j'aime pas\n"
	.string "quand tu gagnes!$"

Route10_Text_HeidiIntro::
	.string "Je reviens de l'ARENE POKéMON!\n"
	.string "Mais je perds tout le temps!$"

Route10_Text_HeidiDefeat::
	.string "Ben, voilà!\n"
	.string "J'ai encore perdu!$"

Route10_Text_HeidiPostBattle::
	.string "J'ai rencontré des POKéMANIACS\n"
	.string "dans le coin.$"

Route10_Text_TrentIntro::
	.string "Ah! L'air de la montagne, c'est\n"
	.string "vivifiant!$"

Route10_Text_TrentDefeat::
	.string "Ben…\n"
	.string "Me voilà tout vivifié!$"

Route10_Text_TrentPostBattle::
	.string "J'en ai marre de la montagne!$"

Route10_Text_CarolIntro::
	.string "Cette randonnée m'a épuisée!$"

Route10_Text_CarolDefeat::
	.string "Trop fatiguée.\n"
	.string "J'laisse tomber!$"

Route10_Text_CarolPostBattle::
	.string "Les POKéMON de la montagne\n"
	.string "sont trop trapus!\p"
	.string "Il en faudrait des roses en forme\n"
	.string "de jolies fleurs!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "GROTTE\n"
	.string "Détour pour LAVANVILLE$"

Route10_Text_RockTunnel::
	.string "GROTTE$"

Route10_Text_PowerPlant::
	.string "CENTRALE$"

