.set SPOKE_TO_WOMAN_LAST,   FLAG_TEMP_2
.set SPOKE_TO_FAT_MAN_LAST, FLAG_TEMP_3

VermilionCity_PokemonFanClub_Frlg_MapScripts::
	.byte 0

VermilionCity_PokemonFanClub_EventScript_Chairman::
	lock
	faceplayer
	goto_if_set FLAG_GOT_BIKE_VOUCHER, VermilionCity_PokemonFanClub_EventScript_AlreadyHeardStory
	msgbox VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, VermilionCity_PokemonFanClub_EventScript_ChairmanStory
	msgbox VermilionCity_PokemonFanClub_Text_ComeBackToHearStory
	release
	end

VermilionCity_PokemonFanClub_EventScript_AlreadyHeardStory::
	msgbox VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain
	release
	end

VermilionCity_PokemonFanClub_EventScript_ChairmanStory::
	msgbox VermilionCity_PokemonFanClub_Text_ChairmansStory
	checkitemspace ITEM_BIKE_VOUCHER
	goto_if_eq VAR_RESULT, FALSE, VermilionCity_PokemonFanClub_EventScript_NoRoomForBikeVoucher
	setflag FLAG_GOT_BIKE_VOUCHER
	giveitem_msg VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman, ITEM_BIKE_VOUCHER, 1, MUS_RG_OBTAIN_KEY_ITEM
	msgbox VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher
	release
	end

VermilionCity_PokemonFanClub_EventScript_NoRoomForBikeVoucher::
	msgbox VermilionCity_PokemonFanClub_Text_MakeRoomForThis
	release
	end

VermilionCity_PokemonFanClub_EventScript_WorkerF::
	lock
	faceplayer
	goto_if_set FLAG_SYS_GAME_CLEAR, VermilionCity_PokemonFanClub_EventScript_WorkerFGameClear
	msgbox VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon
	release
	end

VermilionCity_PokemonFanClub_EventScript_WorkerFGameClear::
	famechecker FAMECHECKER_DAISY, 1
	msgbox VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons
	release
	end

VermilionCity_PokemonFanClub_EventScript_Woman::
	lock
	faceplayer
	goto_if_set SPOKE_TO_FAT_MAN_LAST, VermilionCity_PokemonFanClub_EventScript_WomanSpokeToFatMan
	msgbox VermilionCity_PokemonFanClub_Text_AdoreMySeel
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_WOMAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	setflag SPOKE_TO_WOMAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_WomanSpokeToFatMan::
	msgbox VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_WOMAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	clearflag SPOKE_TO_FAT_MAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_FatMan::
	lock
	faceplayer
	goto_if_set SPOKE_TO_WOMAN_LAST, VermilionCity_PokemonFanClub_EventScript_FatManSpokeToWoman
	msgbox VermilionCity_PokemonFanClub_Text_AdmirePikachusTail
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_FAT_MAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	setflag SPOKE_TO_FAT_MAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_FatManSpokeToWoman::
	msgbox VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_FAT_MAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	clearflag SPOKE_TO_WOMAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_Pikachu::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PIKACHU, CRY_MODE_NORMAL
	msgbox VermilionCity_PokemonFanClub_Text_Pikachu
	waitmoncry
	release
	end

VermilionCity_PokemonFanClub_EventScript_Seel::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SEEL, CRY_MODE_NORMAL
	msgbox VermilionCity_PokemonFanClub_Text_Seel
	waitmoncry
	release
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign1::
	msgbox VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers, MSGBOX_SIGN
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign2::
	msgbox VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack, MSGBOX_SIGN
	end

VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
	.string "Mon PIKACHU est le plus beau de\n"
	.string "tous les PIKACHU!$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
	.string "Hmm!\p"
	.string "Mon PIKACHU est deux fois plus\n"
	.string "mignon que celui-ci!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
	.string "Moi, celui que j'aime c'est OTARIA!\p"
	.string "Il fait squitch quand je lui fais\n"
	.string "un câlin!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
	.string "Oh!\p"
	.string "Mon OTARIA est beaucoup plus\n"
	.string "élégant!$"

VermilionCity_PokemonFanClub_Text_Pikachu::
	.string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
	.string "OTARIA: Riaaa!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
	.string "Je suis le président du Fan Club\n"
	.string "des POKéMON!\p"
	.string "J'ai plus de 100 POKéMON!\p"
	.string "Je suis trop méga tatillon quand on\n"
	.string "parle de POKéMON!\p"
	.string "Alors…\p"
	.string "Tu veux encore savoir des trucs\n"
	.string "sur mes POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
	.string "Bien!\n"
	.string "Ecoute!\p"
	.string "Mon préféré c'est GALOPA…\p"
	.string "Il est… mignon… adorable…\n"
	.string "intelligent… et… incroyable…\l"
	.string "Tu crois pas?\l"
	.string "Oh oui… simplement…\l"
	.string "incroyable…\l"
	.string "Je… l'adore!\p"
	.string "Il est tout doux… quand…\n"
	.string "je lui… fais des câlins…\l"
	.string "et puis…\l"
	.string "et aussi…\l"
	.string "… Oups! Regarde l'heure!\l"
	.string "J'arrête pas de parler!\p"
	.string "Merci de m'avoir écouté!\n"
	.string "Tiens, c'est pour toi!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
	.string "{PLAYER} reçoit le\n"
	.string "BON COMMANDE!$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
	.string "Echange-le contre une BICYCLETTE\n"
	.string "aux CYCLES A GOGO d'AZURIA!\p"
	.string "Moi, c'est mon RAPASDEPIC qui me\n"
	.string "transporte n'importe où!\p"
	.string "Je n'ai plus besoin de\n"
	.string "BICYCLETTE!\p"
	.string "J'espère que tu aimes pédaler!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
	.string "Reviens quand tu veux. Je te\n"
	.string "raconterai mes histoires!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
	.string "Salut, {PLAYER}!\p"
	.string "Tu es là pour écouter mes\n"
	.string "histoires de POKéMON?\p"
	.string "Non? Dommage!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
	.string "Ton inventaire est plein!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
	.string "Le PRESIDENT est très bavard en\n"
	.string "ce qui concerne les POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
	.string "Ecoutons donc l'avis des autres\n"
	.string "DRESSEURS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
	.string "Si on te nargue, nargue en retour!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
	.string "Notre PRESIDENT aime beaucoup\n"
	.string "ses POKéMON.\p"
	.string "Mais c'est NINA que les POKéMON\n"
	.string "préfèrent, je crois.$"
