FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "Nous avons surnommé le GARDIEN,\n"
	.string "RAMOLOSS.\p"
	.string "Ben, oui! Il ressemble à un\n"
	.string "RAMOLOSS!$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "RAMOLOSS s'y connaît beaucoup\n"
	.string "en POKéMON!\p"
	.string "Il a même des fossiles de POKéMON\n"
	.string "rares et anciens!$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "RAMOLOSS m'a parlé, mais je ne\n"
	.string "comprends rien à c'qu'il m'dit.\p"
	.string "Je crois qu'il a un problème pour\n"
	.string "parler!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
	.string "RAMOLOSS vient de lancer une\n"
	.string "campagne de promotion.\p"
	.string "Essaie d'aller dans le coin le\n"
	.string "plus éloigné du PARC SAFARI.\p"
	.string "Si tu y arrives, tu recevras un\n"
	.string "prix.$"

