SixIsland_House_Frlg_MapScripts::
	.byte 0

SixIsland_House_EventScript_OldMan::
	msgbox SixIsland_House_Text_GoodPlaceForNatureAndHistory, MSGBOX_NPC
	end

SixIsland_House_Text_GoodPlaceForNatureAndHistory::
	.string "Il n'y a vraiment rien de bien\n"
	.string "intéressant pour les jeunes ici.\p"
	.string "Mais historiquement, cet endroit\n"
	.string "est sans égal.\p"
	.string "Repose-toi, et profite de ton\n"
	.string "séjour.$"

