SixIsland_Mart_Frlg_MapScripts::
	.byte 0

SixIsland_Mart_EventScript_Clerk::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart SixIsland_Mart_Items
	msgbox gText_PleaseComeAgain
	release
	end

	.align 2
SixIsland_Mart_Items::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_MAX_POTION
	.2byte ITEM_REVIVE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_ESCAPE_ROPE
	.2byte ITEM_MAX_REPEL
	.2byte ITEM_DREAM_MAIL
	.2byte ITEM_NONE
	release
	end

SixIsland_Mart_EventScript_Picnicker::
	msgbox SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter, MSGBOX_NPC
	end

SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
	.string "Joue beaucoup avec tes POKéMON\n"
	.string "et profite de la vie.\p"
	.string "Prends AGATHA par exemple.\n"
	.string "C'est la personne la plus\p"
	.string "âgée qui ait jamais fait partie\n"
	.string "du CONSEIL 4.\p"
	.string "Elle me pousse à me surpasser.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
	.string "Je devrais acheter du papier et\n"
	.string "lui envoyer une LETTRE.$"

