Route13_Frlg_MapScripts::
	.byte 0

Route13_EventScript_TrainerTips1::
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
	end

Route13_EventScript_TrainerTips2::
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
	end

Route13_EventScript_RouteSign::
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
	end

Route13_Text_SebastianIntro::
	.string "Mes POKéMON oiseau cherchent la\n"
	.string "baston!$"

Route13_Text_SebastianDefeat::
	.string "Tu m'as volé dans les plumes!$"

Route13_Text_SebastianPostBattle::
	.string "Mes POKéMON ont l'air contents,\n"
	.string "même s'ils ont perdu.$"

Route13_Text_SusieIntro::
	.string "Pas mal pour une fille, hein?$"

Route13_Text_SusieDefeat::
	.string "Oh!\n"
	.string "Perdu!$"

Route13_Text_SusiePostBattle::
	.string "Je veux être un bon DRESSEUR.\n"
	.string "Je travaille dur.$"

Route13_Text_ValerieIntro::
	.string "Woaa!\n"
	.string "Tes BADGES sont trop cool!$"

Route13_Text_ValerieDefeat::
	.string "…\n"
	.string "J'en ai assez!$"

Route13_Text_ValeriePostBattle::
	.string "Tu as gagné ces BADGES chez les\n"
	.string "CHAMPIONS!$"

Route13_Text_GwenIntro::
	.string "Mes POKéMON tout mignons veulent\n"
	.string "te connaître.$"

Route13_Text_GwenDefeat::
	.string "Wow!\n"
	.string "J'suis morte!$"

Route13_Text_GwenPostBattle::
	.string "Tu dois faire combattre tes\n"
	.string "POKéMON pour les entraîner!$"

Route13_Text_AlmaIntro::
	.string "J'ai trouvé du CARBONE dans une\n"
	.string "grotte en faisant de la spéléo.$"

Route13_Text_AlmaDefeat::
	.string "J'ai tout raté!$"

Route13_Text_AlmaPostBattle::
	.string "Le CARBONE a augmenté la vitesse\n"
	.string "de mon POKéMON.$"

Route13_Text_PerryIntro::
	.string "Le vent souffle par là. Cool!$"

Route13_Text_PerryDefeat::
	.string "Le vent a tourné!$"

Route13_Text_PerryPostBattle::
	.string "J'ai perdu.\n"
	.string "Je rentre chez moi avec VOL.$"

Route13_Text_LolaIntro::
	.string "Tu veux te mesurer à moi?$"

Route13_Text_LolaDefeat::
	.string "Oh!\n"
	.string "Sale teigne!$"

Route13_Text_LolaPostBattle::
	.string "C'est quoi le plus fort, un POKéMON\n"
	.string "mâle ou femelle?$"

Route13_Text_SheilaIntro::
	.string "Et si on se battait?$"

Route13_Text_SheilaDefeat::
	.string "Fini?\n"
	.string "Déjà?$"

Route13_Text_SheilaPostBattle::
	.string "J'y connais rien aux POKéMON!\n"
	.string "Je les trouve juste cool!$"

Route13_Text_JaredIntro::
	.string "Qu'est-ce que tu regardes, toi!?$"

Route13_Text_JaredDefeat::
	.string "Zipp!\n"
	.string "J'ai glissé!$"

Route13_Text_JaredPostBattle::
	.string "Du balai!$"

Route13_Text_RobertIntro::
	.string "J'aime bien mes POKéMON oiseau!\n"
	.string "Je leur consacre tout mon temps.$"

Route13_Text_RobertDefeat::
	.string "Oh!\n"
	.string "Ma cage!$"

Route13_Text_RobertPostBattle::
	.string "J'aimerais voler comme ROUCOOL ou\n"
	.string "ROUCOUPS…$"

Route13_Text_LookToLeftOfThatPost::
	.string "ASTUCE\p"
	.string "Regardez à gauche!$"

Route13_Text_SelectToSwitchItems::
	.string "ASTUCE\p"
	.string "Utilisez SELECT pour organiser\n"
	.string "votre inventaire!$"

Route13_Text_RouteSign::
	.string "ROUTE 13\n"
	.string "PONT DU SILENCE au Nord$"

