#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("SAPPHIRE");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBY");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("EMERAUDE");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ARTHUR");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAX");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRICE");
const u8 gText_ExpandedPlaceholder_May[] = _("FLORA");
const u8 gText_ExpandedPlaceholder_Red[] = _("RED");
const u8 gText_ExpandedPlaceholder_Green[] = _("GREEN");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("OEUF");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("JOUEUR"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("TIME");
const u8 gText_Badges[] = _("BADGES"); // Unused
const u8 gText_AButton[] = _("Bouton A"); // Unused
const u8 gText_BButton[] = _("Bouton B"); // Unused
const u8 gText_RButton[] = _("Bouton R"); // Unused
const u8 gText_LButton[] = _("Bouton L"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ DPAD"); // Unused
const u8 gText_LButtonRButton[] = _("Bouton L  Bouton R"); // Unused
const u8 gText_Controls[] = _("COMMANDES"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}CHOISIR {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}SUIV."); // Unused
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}SUIV. {B_BUTTON}RET."); // Unused
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}CHOIX {A_BUTTON}SUIV. {B_BUTTON}ANN.");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}CHOIX {A_BUTTON}{B_BUTTON}ANNUL.");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}RETOUR");
const u8 gText_Boy[] = _("GARÇON");
const u8 gText_Girl[] = _("FILLE");
const u8 gText_ThisIsAPokemon[] = _("Voici ce qu'on appelle un “POKéMON”.{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("?????");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 12}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 12}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("CRI DE");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("TAILLE COMPAREE A ");
const u8 gText_PokedexRegistration[] = _("Enregistrement du POKéDEX terminé.");
const u8 gText_HTHeight[] = _("HAUT.");
const u8 gText_WTWeight[] = _("POIDS");
const u8 gText_SearchingPleaseWait[] = _("Recherche en cours…\nVeuillez patienter.");
const u8 gText_SearchCompleted[] = _("Recherche terminée.");
const u8 gText_NoMatchingPkmnWereFound[] = _("Aucun POKéMON correspondant trouvé.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Recherche de POKéMON selon certains\ncritères.");
const u8 gText_SwitchPokedexListings[] = _("Changer le classement du POKéDEX.");
const u8 gText_ReturnToPokedex[] = _("Revenir au POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Choisir le mode du POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Choisir le mode de classement du POKéDEX.");
const u8 gText_ListByFirstLetter[] = _("Recherche par la première lettre du nom:\nPOKéMON vus.");
const u8 gText_ListByBodyColor[] = _("Recherche par la couleur:\nPOKéMON vus.");
const u8 gText_ListByType[] = _("Recherche par le type:\nPOKéMON pris uniquement.");
const u8 gText_ExecuteSearchSwitch[] = _("Exécuter recherche/changement.");
const u8 gText_DexHoennTitle[] = _("DEX HOENN");
const u8 gText_DexNatTitle[] = _("DEX NATIONAL");
const u8 gText_DexSortNumericalTitle[] = _("MODE NUMERIQUE");
const u8 gText_DexSortAtoZTitle[] = _("MODE A à Z");
const u8 gText_DexSortHeaviestTitle[] = _("MODE + - LOURD");
const u8 gText_DexSortLightestTitle[] = _("MODE + - LEGER");
const u8 gText_DexSortTallestTitle[] = _("MODE + - GRAND");
const u8 gText_DexSortSmallestTitle[] = _("MODE + - PETIT");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROUGE");
const u8 gText_DexSearchColorBlue[] = _("BLEU");
const u8 gText_DexSearchColorYellow[] = _("JAUNE");
const u8 gText_DexSearchColorGreen[] = _("VERT");
const u8 gText_DexSearchColorBlack[] = _("NOIR");
const u8 gText_DexSearchColorBrown[] = _("MARRON");
const u8 gText_DexSearchColorPurple[] = _("VIOLET");
const u8 gText_DexSearchColorGray[] = _("GRIS");
const u8 gText_DexSearchColorWhite[] = _("BLANC");
const u8 gText_DexSearchColorPink[] = _("ROSE");
const u8 gText_DexHoennDescription[] = _("POKéDEX de la région HOENN");
const u8 gText_DexNatDescription[] = _("POKéDEX édition nationale");
const u8 gText_DexSortNumericalDescription[] = _("POKéMON classés selon leur numéro.");
const u8 gText_DexSortAtoZDescription[] = _("POKéMON vus et pris, classés par ordre\nalphabétique.");
const u8 gText_DexSortHeaviestDescription[] = _("POKéMON pris, classés du plus lourd au\nplus léger.");
const u8 gText_DexSortLightestDescription[] = _("POKéMON pris, classés du plus léger au\nplus lourd.");
const u8 gText_DexSortTallestDescription[] = _("POKéMON pris, classés du plus grand au\nplus petit.");
const u8 gText_DexSortSmallestDescription[] = _("POKéMON pris, classés du plus petit au\nplus grand.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("INDIFFERENT");
const u8 gText_DexSearchTypeNone[] = _("AUCUN");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" ");
const u8 gText_WelcomeToHOF[] = _("Bienvenue au PANTHEON!");
const u8 gText_HOFDexRating[] = _("Spotted POKéMON: {STR_VAR_1}!\nOwned POKéMON: {STR_VAR_2}!\pPROF. BIRCH's POKéDEX rating!\pPROF. BIRCH: Let's see…\p");
const u8 gText_HOFDexSaving[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_HOFCorrupted[] = _("Données du PANTHEON corrompues.");
const u8 gText_HOFNumber[] = _("PANTHEON Nº {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("MAITRE DE LA LIGUE!\nFELICITATIONS!");
const u8 gText_Number[] = _("Nº ");
const u8 gText_Level[] = _("N. ");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("NOM");
const u8 gText_IDNumber[] = _("NºID");
const u8 gText_BirchInTrouble[] = _("Le PROF. SEKO a des ennuis!\nChoisis un POKéMON et sauve-le!");
const u8 gText_ConfirmStarterChoice[] = _("Prendre ce POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("VOLER où?");
const u8 gMenuText_Use[] = _("UTILIS.");
const u8 gMenuText_Toss[] = _("JETER");
const u8 gMenuText_Register[] = _("ENREG.");
const u8 gMenuText_Give[] = _("DONNER");
const u8 gMenuText_Confirm[] = _("CONFIR.");
const u8 gText_Cancel[] = _("SORTIR");
const u8 gText_Cancel2[] = _("RETOUR");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("AUCUN");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("N.");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{NO}{ID}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Retourner au menu\nprécédent.");
const u8 gText_WhatWouldYouLike[] = _("Que voulez-vous faire?");
const u8 gMenuText_Give2[] = _("DONNER");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BERRY"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} JETONS");
const u8 gText_CloseBag[] = _("FERMER LE SAC");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1} est\nsélectionné.");
const u8 gText_CantWriteMail[] = _("Vous ne pouvez pas\nécrire de LETTRE ici.");
const u8 gText_NoPokemon[] = _("Il n'y a pas de\nPOKéMON.");
const u8 gText_MoveVar1Where[] = _("Où voulez-vous\nplacer\n{STR_VAR_1}?");
const u8 gText_Var1CantBeHeld[] = _("Impossible de tenir {STR_VAR_1}!");
const u8 gText_TossHowManyVar1s[] = _("En jeter combien?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_1}:\njeté {STR_VAR_2}.");
const u8 gText_ConfirmTossItems[] = _("{STR_VAR_1}:\nen jeter {STR_VAR_2}?");
const u8 gText_DadsAdvice[] = _("Conseil de PAPA…\n{PLAYER}, chaque chose en son temps!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} utilise\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Mais le REPOUSSE précédent est\ntoujours actif.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Mais le PARFUM précédent est\ntoujours actif.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Les BOITES sont pleines.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("au jeu");
const u8 gText_TheBattle[] = _("au combat");
const u8 gText_ThePokemonList[] = _("à la LISTE POKéMON");
const u8 gText_TheShop[] = _("au magasin");
const u8 gText_ThePC[] = _("au PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Retourner {STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("OBJETS"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("POKé BALLS"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("CT & CS"),
    [POCKET_BERRIES] =      COMPOUND_STRING("BAIES"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("OBJ. RARES")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("ACHETER");
const u8 gText_ShopSell[] = _("VENDRE");
const u8 gText_ShopQuit[] = _("QUITTER");
const u8 gText_ThatItemIsSoldOut[] = _("Navré, mais cet objet n'est plus en stock.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("EPUISE");
const u8 gText_InBagVar1[] = _("SAC: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Arrêter d'acheter.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Bien sûr.\nCombien en voulez-vous?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_2} de {STR_VAR_1}?\nBien sûr. Combien en voulez-vous?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? Vous en voulez {STR_VAR_2}?\nÇa fera {STR_VAR_3}¥.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, n'est-ce pas?\nÇa fera {STR_VAR_2}¥. Ça vous convient?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Vous voulez {STR_VAR_1}?\nÇa fera {STR_VAR_2}¥. Ça vous convient?");
const u8 gText_HereYouGoThankYou[] = _("Tenez!\nMerci infiniment.");
const u8 gText_ThankYouIllSendItHome[] = _("Merci!\nJe l'envoie sur votre PC.");
const u8 gText_ThanksIllSendItHome[] = _("Merci!\nJe l'envoie sur votre PC à la maison.");
const u8 gText_YouDontHaveMoney[] = _("Vous n'avez pas assez d'argent.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("Vous n'avez plus de place pour cela.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("La place pour {STR_VAR_1}\nest prise.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Je peux faire quelque chose d'autre?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Vous avez besoin d'autre chose?");
const u8 gText_ThrowInPremierBall[] = _("Je mets une HONOR BALL en plus.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("Je mets {STR_VAR_1} HONOR BALLS en plus.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, non.\nJe ne peux pas acheter ça.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nCombien voulez-vous en vendre?");
const u8 gText_ICanPayVar1[] = _("Je peux vous en donner {STR_VAR_1}¥.\nÇa vous va?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Obtenu {STR_VAR_1}¥\npour cette vente.");
const u8 gText_PokedollarVar1[] = _("{STR_VAR_1}¥");
const u8 gText_HP3[] = _("PV");
const u8 gText_SpAtk3[] = _("ATQ. SPE.");
const u8 gText_SpDef3[] = _("DEF. SPE.");
const u8 gText_WontHaveEffect[] = _("Ça n'aura aucun effet.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Choisir un {PKMN} avec qui fusionner.");
const u8 gText_CantBeUsedOnPkmn[] = _("C'est inutilisable\nsur ce POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} ne peut pas être\néchangé!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} est déjà au\ncombat!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} est déjà\nsélectionné.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} n'a plus d'énergie\npour combattre!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Impossible d'échanger POKéMON\nde {STR_VAR_1} avec un des vôtres!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Un OEUF ne se bat pas, voyons!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Impossible de l'utiliser jusqu'à\nl'obtention du prochain BADGE.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Seuls {STR_VAR_1} POKéMON\npeuvent participer.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Envoyer la LETTRE enlevée\nsur votre PC?");
const u8 gText_MailSentToPC[] = _("La LETTRE a été envoyée\nsur votre PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("La BOITE AUX LETTRES\ndu PC est pleine.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Si la LETTRE est enlevée,\nle message sera perdu. D'accord?");
const u8 gText_RemoveMailBeforeItem[] = _("Il faut enlever la LETTRE pour \npouvoir garder un objet.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} doit tenir\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} tient déjà\n{STR_VAR_2}!\pEchanger les deux objets?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} ne tient rien.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Reçu {STR_VAR_2} de\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("La LETTRE a été prise\nau POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_1} a remplacé\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Ce POKéMON tient un objet.\nIl ne peut pas tenir une LETTRE.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("La LETTRE vient de la\nBOITE AUX LETTRES.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Le SAC est plein. Impossible\nd'enlever l'objet au POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} apprend\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} apprend\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} et {STR_VAR_2}\nne sont pas compatibles.\pImpossible de l'enseigner.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} veut apprendre\n{STR_VAR_2}.\pMais {STR_VAR_1} connaît déjà\nquatre capacités.\pRemplacer une capacité\npar {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Arrêter d'enseigner\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} n'a pas appris la\ncapacité {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Oublier quelle capacité?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, et{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Tadaa!\p{STR_VAR_1} ne sait plus\ncomment utiliser {STR_VAR_2}.\pEt…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} connaît déjà\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("Les PV de {STR_VAR_1} sont res-\ntaurés de {STR_VAR_2} points.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} n'est plus\nempoisonné.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} n'est plus\nparalysé.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} se réveille.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1} n'est plus brûlé.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1} s'est remis de sa gelure.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} est décongelé.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("Les PP sont restaurés.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} retrouve la forme.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("Les PP de {STR_VAR_1}\naugmentent.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} monte au N. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} a gagné {STR_VAR_2}\nPoints d'Expérience!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} a gagné {STR_VAR_2} Points\nd'Expérience et s'élève au N. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_2} de\n{STR_VAR_1} augmente.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} est devenu amical.\n{STR_VAR_2} de base en baisse!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} vous adore!\n{STR_VAR_2} de base en baisse!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} est devenu amical.\n{STR_VAR_2} de base ne peut pas baisser!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} n'est plus confus.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} n'est plus\namoureux.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} se transforme!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("Jeter {STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1} a été jeté.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Teach which POKéMON?"); // Unused
const u8 gText_ChoosePokemon[] = _("Choisir un POKéMON.");
const u8 gText_MoveToWhere[] = _("Le mettre où?");
const u8 gText_TeachWhichPokemon[] = _("Enseigner à quel POKéMON?");
const u8 gText_UseOnWhichPokemon[] = _("Utiliser sur quel POKéMON?");
const u8 gText_GiveToWhichPokemon[] = _("Donner à quel POKéMON?");
const u8 gText_DoWhatWithPokemon[] = _("Que faire avec ce PKMN?");
const u8 gText_NothingToCut[] = _("Il n'y a rien à COUPER.");
const u8 gText_CantSurfHere[] = _("On ne peut pas SURFER ici.");
const u8 gText_AlreadySurfing[] = _("Vous SURFEZ déjà.");
const u8 gText_CantUseHere[] = _("Impossible ici.");
const u8 gText_RestoreWhichMove[] = _("Laquelle restaurer?");
const u8 gText_BoostPP[] = _("Augmenter quels PP?");
const u8 gText_DoWhatWithItem[] = _("Que faire avec un objet?");
const u8 gText_NoPokemonForBattle[] = _("Aucun POKéMON utilisable!");
const u8 gText_ChoosePokemon2[] = _("Choisir un POKéMON.");
const u8 gText_NotEnoughHp[] = _("Pas assez de PV…");
const u8 gText_PokemonAreNeeded[] = _("Il faut {STR_VAR_1} POKéMON.");
const u8 gText_PokemonCantBeSame[] = _("Pas les mêmes POKéMON.");
const u8 gText_NoIdenticalHoldItems[] = _("Pas d'objets identiques.");
const u8 gText_CurrentIsTooFast[] = _("Le courant est trop rapide!");
const u8 gText_DoWhatWithMail[] = _("Que faire avec LETTRE?");
const u8 gText_ChoosePokemonCancel[] = _("Choisir un PKMN ou annuler.");
const u8 gText_ChoosePokemonConfirm[] = _("Choisir un PKMN et confirmer.");
const u8 gText_SendWhichMonToPC[] = _("Envoyer quel POKéMON au PC?");
const u8 gText_MoveItemWhere[] = _("Le mettre où?");
const u8 gText_XsYAnd[] = _("{STR_VAR_2} de {STR_VAR_1} et\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_2} de {STR_VAR_1} ont été échangés!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("C'est parti pour une balade!");
const u8 gText_InUseAlready_PM[] = _("Déjà en cours d'utilisation.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} tient déjà\n{STR_VAR_2}!");
const u8 gText_WhichAppliance[] = _("Commander quel\nappareil?");
const u8 gText_NoUse[] = _("Pas utilis.");
const u8 gText_Able[] = _("APTE");
const u8 gText_First_PM[] = _("PREMIER");
const u8 gText_Second_PM[] = _("DEUXIEME");
const u8 gText_Third_PM[] = _("TROISIEME");
const u8 gText_Able2[] = _("APTE");
const u8 gText_NotAble[] = _("PAS APTE");
const u8 gText_Able3[] = _("APTE");
const u8 gText_NotAble2[] = _("PAS APTE");
const u8 gText_Learned[] = _("APPRIS");
const u8 gText_Have[] = _("PORTE");
const u8 gText_DontHave[] = _("PAS D'OBJET");
const u8 gText_Fourth[] = _("QUATRIEME");
const u8 gText_PkmnCantParticipate[] = _("Ce POKéMON ne peut pas participer.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Annuler la participation?");
const u8 gText_CancelBattle[] = _("Annuler le combat?");
const u8 gText_ReturnToWaitingRoom[] = _("Retourner à la SALLE D'ATTENTE?");
const u8 gText_CancelChallenge[] = _("Annuler le défi?");
const u8 gText_EscapeFromHere[] = _("Fuir d'ici et retourner à\n{STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("Retourner au dernier lieu\nde soins?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("C'est votre seul\nPOKéMON pour combattre.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Ce POKéMON ne peut\npas être échangé maintenant.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Ce POKéMON ne peut\npas être échangé.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Un OEUF ne peut pas être\néchangé maintenant.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Le POKéMON du DRESSEUR\nne peut pas être échangé.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("L'autre DRESSEUR ne peut pas\naccepter ce POKéMON maintenant.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Impossible d'échanger avec\nce DRESSEUR maintenant.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Le DRESSEUR ne cherche\npas ce type de POKéMON.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Ce n'est pas un OEUF.");
const u8 gText_Register[] = _("ENREG.");
const u8 gText_Attack3[] = _("ATTAQUE");
const u8 gText_Defense3[] = _("DEFENSE");
const u8 gText_SpAtk4[] = _("ATQ SP");
const u8 gText_SpDef4[] = _("DEF SP");
const u8 gText_Speed2[] = _("VIT.");
const u8 gText_HP4[] = _("PV");
const u8 gText_EmptyString8[] = _("");
const u8 gText_OTSlash[] = _("DO/");
const u8 gText_RentalPkmn[] = _("POKéMON A LOUER");
const u8 gText_TypeSlash[] = _("TYPE/");
const u8 gText_Power[] = _("POUV.");
const u8 gText_Accuracy2[] = _("PRECIS.");
const u8 gText_Appeal[] = _("CHARME");
const u8 gText_Jam[] = _("BLOCAG.");
const u8 gText_Status[] = _("STATUT");
const u8 gText_ExpPoints[] = _("POINTS EXP.");
const u8 gText_NextLv[] = _("N. SUIVANT");
const u8 gText_RibbonsVar1[] = _("RUBANS: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTS"); // Unused
const u8 gText_Switch[] = _("CHANG.");
const u8 gText_PkmnInfo[] = _("INFOS POKéMON");
const u8 gText_PkmnSkills[] = _("APTITU. POKéMON");
const u8 gText_BattleMoves[] = _("CAPACITES COMB.");
const u8 gText_ContestMoves[] = _("CAPACITES CONC.");
const u8 gText_Info[] = _("INFOS");
const u8 gText_EggWillTakeALongTime[] = _("Cet OEUF va sûrement\nmettre du temps à éclore.");
const u8 gText_EggWillTakeSomeTime[] = _("Qu'est-ce qui va en sortir?\nÇa va mettre du temps.");
const u8 gText_EggWillHatchSoon[] = _("Il bouge de temps en temps.\nIl devrait bientôt éclore.");
const u8 gText_EggAboutToHatch[] = _("Il fait du bruit.\nIl va éclore!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Impossible d'oublier les\ncapacités CS maintenant.");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, rencontré au {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}\n({DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}).");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, a éclos au {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}\n({DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}).");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, obtenu dans un échange.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, obtenu lors d'un évènement\nspécial au {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, probablement rencontré au\n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1} ({DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}).");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature.");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, rencontré quelque part\nau {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} de nature, a éclos quelque part\nau {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Drôle d'OEUF de PKMN trouvé\npar le couple de la PENSION.");
const u8 gText_PeculiarEggNicePlace[] = _("Drôle d'OEUF de PKMN\nobtenu dans un bel endroit.");
const u8 gText_PeculiarEggTrade[] = _("Drôle d'OEUF de PKMN\nobtenu lors d'un échange.");
const u8 gText_EggFromHotSprings[] = _("Drôle d'OEUF de PKMN obtenu\naux sources chaudes.");
const u8 gText_EggFromTraveler[] = _("Drôle d'OEUF de PKMN\nreçu d'un voyageur.");
const u8 gText_ApostropheSBase[] = _("BASE DE {STR_VAR_1}");
const u8 gText_OkayToDeleteFromRegistry[] = _("Supprimer {STR_VAR_1} du\nREGISTRE?");
const u8 gText_RegisteredDataDeleted[] = _("Données enregistrées effacées.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Il n'y a pas de REGISTRE.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("EFF. REGIST.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DECORER");
const u8 gText_PutAway[] = _("RANGER");
const u8 gText_Toss2[] = _("JETER");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW}0");
const u8 gText_PutOutSelectedDecorItem[] = _("Retirer une décoration.");
const u8 gText_StoreChosenDecorInPC[] = _("Stocker une décoration dans le PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Jeter les décorations indésirables.");
const u8 gText_NoDecorations[] = _("Pas de décorations.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("BUREAU");
const u8 gText_Chair[] = _("CHAISE");
const u8 gText_Plant[] = _("PLANTE");
const u8 gText_Ornament[] = _("ORNEMENT");
const u8 gText_Mat[] = _("TAPIS");
const u8 gText_Poster[] = _("POSTER");
const u8 gText_Doll[] = _("POUPEE");
const u8 gText_Cushion[] = _("COUSSIN");
const u8 gText_Gold[] = _("or");
const u8 gText_Silver[] = _("argent");
const u8 gText_PlaceItHere[] = _("Placer ici?");
const u8 gText_CantBePlacedHere[] = _("Impossible ici.");
const u8 gText_CancelDecorating[] = _("Annuler décoration?");
const u8 gText_InUseAlready[] = _("Déjà en cours d'utilisation.");
const u8 gText_NoMoreDecorations[] = _("Impossible de placer plus de\ndécorations. Le maximum est de {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("Impossible de placer plus de\ndécorations. Le maximum est de {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("This can't be placed here.\nIt must be on a DESK, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Vous ne pouvez pas mettre\ncette décoration dans votre chambre.");
const u8 gText_CantThrowAwayInUse[] = _("Cette décoration est utilisée.\nElle ne peut pas être jetée.");
const u8 gText_DecorationWillBeDiscarded[] = _("Jeter {STR_VAR_1}.\nOK?");
const u8 gText_DecorationThrownAway[] = _("Cette décoration a été jetée.");
const u8 gText_StopPuttingAwayDecorations[] = _("Arrêter de ranger les décorations?");
const u8 gText_NoDecorationHere[] = _("Il n'y a pas de décoration ici.");
const u8 gText_ReturnDecorationToPC[] = _("Ranger cette décoration dans le PC?");
const u8 gText_DecorationReturnedToPC[] = _("Cette décoration est rangée dans le PC.");
const u8 gText_NoDecorationsInUse[] = _("Aucune décoration n'est utilisée.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Il n'y a pas d'objets.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Pas de LETTRE ici.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Que faire avec la\nLETTRE de {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("Le message sera perdu.\nContinuer?");
const u8 gText_BagIsFull[] = _("Le SAC est plein.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("La LETTRE a été remise dans le SAC\net son message a été effacé.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("PAPA");
const u8 gText_Mom[] = _("MAMAN");
const u8 gText_CoolnessContest[] = _("SANG-FROID");
const u8 gText_BeautyContest[] = _("BEAUTE");
const u8 gText_CutenessContest[] = _("GRACE");
const u8 gText_SmartnessContest[] = _("INTELLIGENCE");
const u8 gText_ToughnessContest[] = _("ROBUSTESSE");
const u8 gText_Information[] = _("INFORMATION");
const u8 gText_Yes[] = _("OUI");
const u8 gText_No[] = _("NON");
const u8 gText_Lv50[] = _("NIVEAU 50");
const u8 gText_OpenLevel[] = _("NIVEAU LIBRE");
const u8 gText_BattleFrontier[] = _("ZONE DE COMBAT");
const u8 gText_Cool[] = _("SG-FD");
const u8 gText_Beauty[] = _("BEAUTE");
const u8 gText_Cute[] = _("GRACE");
const u8 gText_Smart[] = _("INTEL.");
const u8 gText_Tough[] = _("ROBUS.");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HYPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_SomeonesPC[] = _("PC de ???");
const u8 gText_LanettesPC[] = _("PC d'ANNETTE");
const u8 gText_BillsPc[] = _("PC de LEO");
const u8 gText_PlayersPC[] = _("PC de {PLAYER}");
const u8 gText_HallOfFame[] = _("PANTHEON");
const u8 gText_LogOff[] = _("DECONNEXION");
const u8 gText_Single2[] = _("SOLO");
const u8 gText_Double2[] = _("DUO");
const u8 gText_Multi[] = _("MULTI");
const u8 gText_MultiLink[] = _("MULTI LINK");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("SAC");
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("SAUVER");
const u8 gText_MenuOptionOption[] = _("OPTIONS");
const u8 gText_MenuOptionExit[] = _("RETOUR");
const u8 gText_SouthernIsland[] = _("ILE DU SUD");
const u8 gText_BirthIsland[] = _("ILE AURORE");
const u8 gText_FarawayIsland[] = _("ILE LOINTAINE");
const u8 gText_NavelRock[] = _("ROC NOMBRI");
const u8 gText_NormalTagMatch[] = _("MATCH NORMAL");
const u8 gText_VarietyTagMatch[] = _("MATCH VARIE");
const u8 gText_UniqueTagMatch[] = _("MATCH UNIQUE");
const u8 gText_ExpertTagMatch[] = _("MATCH EXPERT");
const u8 gText_BattleBasics[] = _("REGLES DE BASE");
const u8 gText_PokemonNature[] = _("NATURE");
const u8 gText_PokemonMoves[] = _("CAPACITES");
const u8 gText_Underpowered[] = _("POTENTIEL");
const u8 gText_WhenInDanger[] = _("EN DANGER");
const u8 gText_BattlePokemon[] = _("POKéMON");
const u8 gText_BattleTrainers[] = _("DRESSEURS");
const u8 gText_1F[] = _("RC");
const u8 gText_2F[] = _("1{SUPER_ER}");
const u8 gText_3F[] = _("2{SUPER_E}");
const u8 gText_4F[] = _("3{SUPER_E}");
const u8 gText_5F[] = _("4{SUPER_E}");
const u8 gText_6F[] = _("5{SUPER_E}");
const u8 gText_7F[] = _("6{SUPER_E}");
const u8 gText_8F[] = _("7{SUPER_E}");
const u8 gText_9F[] = _("8{SUPER_E}");
const u8 gText_10F[] = _("9{SUPER_E}");
const u8 gText_11F[] = _("10{SUPER_E}");
const u8 gText_B1F[] = _("1 SS");
const u8 gText_B2F[] = _("2 SS");
const u8 gText_B3F[] = _("3 SS");
const u8 gText_B4F[] = _("4 SS");
const u8 gText_Rooftop[] = _("TOIT");
const u8 gText_ElevatorNowOn[] = _("Etage:");
const u8 gText_BP[] = _("Pco");
const u8 gText_RankingHall[] = _("CLASSEMENT");
const u8 gText_ExchangeService[] = _("ECHANGE");
const u8 gText_SlateportCity[] = _("POIVRESSEL");
const u8 gText_Exit[] = _("ANNULER");
const u8 gText_YourPartysFull[] = _("L'équipe est pleine!");
const u8 gText_InParty[] = _("DE L'EQUIPE");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combinez 4 mots ou groupes");
const u8 gText_AndMakeYourProfile[] = _("de mots et créez votre profil.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Créez un message avec six mots.");
const u8 gText_AndMakeAMessage[] = _("Max. deux (groupes de) mots/ligne.");
const u8 gText_FindWordsThatDescribeYour[] = _("Choisissez des mots qui");
const u8 gText_FeelingsRightNow[] = _("décrivent votre opinion.");
const u8 gText_WithFourPhrases[] = _("With four phrases,");
const u8 gText_CombineNineWordsOrPhrases[] = _("Avec neuf (groupes de) mots,");
const u8 gText_AndMakeAMessage2[] = _("créez un message.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Changez un mot ou groupe de mots");
const u8 gText_AndImproveTheBardsSong[] = _("de la chanson de CAPELO.");
const u8 gText_YourProfile[] = _("Votre profil ");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Votre sentiment avant le combat ");
const u8 gText_WhatYouSayIfYouWin[] = _("Ce que vous dites si vous gagnez ");
const u8 gText_WhatYouSayIfYouLose[] = _("Ce que vous dites si vous perdez ");
const u8 gText_TheAnswer[] = _("La réponse");
const u8 gText_TheMailMessage[] = _("Le message de la LETTRE ");
const u8 gText_TheMailSalutation[] = _("The MAIL salutation");
const u8 gText_TheBardsSong2[] = _("La nouvelle chanson ");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Avec deux (groupes de) mots,");
const u8 gText_AndMakeATrendySaying[] = _("créez une expression cool.");
const u8 gText_TheTrendySaying[] = _("L'expression cool ");
const u8 gText_IsAsShownOkay[] = _("est comme ceci. OK?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Avec deux (groupes de) mots,");
const u8 gText_ToTeachHerAGoodSaying[] = _("apprenez-lui une expression.");
const u8 gText_FindWordsWhichFit[] = _("Trouvez des mots pour décrire");
const u8 gText_TheTrainersImage[] = _("l'image du DRESSEUR.");
const u8 gText_TheImage[] = _("L'image");
const u8 gText_OutOfTheListedChoices[] = _("Parmi les choix proposés,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("sélectionnez la réponse!");
const u8 gText_AndCreateAQuiz[] = _("vous devez créer un quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Choisissez un mot ou un groupe");
const u8 gText_SetTheQuizAnswer[] = _("de mots pour créer la réponse.");
const u8 gText_TheAnswerColon[] = _("La réponse");
const u8 gText_TheQuizColon[] = _("The quiz:");
const u8 gText_ApprenticePhrase[] = _("L'expression de l'apprenti");
const u8 gText_QuitEditing[] = _("Quitter?");
const u8 gText_StopGivingPkmnMail[] = _("Ne plus donner LETTRE à PKMN?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("de mots pour remplir le sondage.");
const u8 gText_LetsReplyToTheInterview[] = _("de mots pour répondre.");
const u8 gText_AllTextBeingEditedWill[] = _("Tout votre texte sera effacé.");
const u8 gText_BeDeletedThatOkay[] = _("D'accord?");
const u8 gText_QuitEditing2[] = _("Quit editing?");
const u8 gText_EditedTextWillNotBeSaved[] = _("The edited text will not be saved.");
const u8 gText_IsThatOkay[] = _("Is that okay?");
const u8 gText_PleaseEnterPhraseOrWord[] = _("Please enter a phrase or word.");
const u8 gText_EntireTextCantBeDeleted[] = _("The entire text can't be deleted.");
const u8 gText_OnlyOnePhrase[] = _("Un seul groupe de mots modifiable.");
const u8 gText_OriginalSongWillBeUsed[] = _("La chanson originale sera reprise.");
const u8 gText_ThatsTrendyAlready[] = _("That's trendy already!");
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combinez deux mots.");
const u8 gText_QuitGivingInfo[] = _("Quit giving information?");
const u8 gText_StopGivingPkmnMail2[] = _("Stop giving the POKéMON MAIL?");
const u8 gText_CreateAQuiz2[] = _("Create a quiz!");
const u8 gText_SetTheAnswer[] = _("Set the answer!");
const u8 gText_CancelSelection[] = _("Cancel the selection?");
const u8 gText_Profile[] = _("PROFIL");
const u8 gText_AtTheBattlesStart[] = _("Avant le combat.");
const u8 gText_UponWinningABattle[] = _("Après une victoire.");
const u8 gText_UponLosingABattle[] = _("Après une défaite.");
const u8 gText_TheBardsSong[] = _("La chanson de CAPELO");
const u8 gText_WhatsHipAndHappening[] = _("C'est quoi la dernière chose à la mode?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Expression");
const u8 gText_FansQuestion[] = _("Question du fan");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Expression de l'apprenti");
const u8 gText_Questionnaire[] = _("SONDAGE");
const u8 gText_YouCannotQuitHere[] = _("Vous ne pouvez pas quitter ici.");
const u8 gText_SectionMustBeCompleted[] = _("Il faut terminer cette section.");
const u8 gText_F700sQuiz[] = _("Quiz de {DYNAMIC 0}");
const u8 gText_Lady[] = _("DAME QUIZ");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Après avoir lu la question");
const u8 gText_QuestionPressTheAButton[] = _("du quiz, appuyez sur le bouton A.");
const u8 gText_TheQuizAnswerIs[] = _("La réponse est?");
const u8 gText_LikeToQuitQuiz[] = _("Voulez-vous quitter le défi");
const u8 gText_ChallengeQuestionMark[] = _("du quiz?");
const u8 gText_IsThisQuizOK[] = _("Est-ce que ce quiz est OK?");
const u8 gText_CreateAQuiz[] = _("Créez un quiz!");
const u8 gText_SelectTheAnswer[] = _("Sélectionnez la réponse!");
const u8 gText_LyricsCantBeDeleted[] = _("Impossible d'effacer les paroles.");
const u8 gText_PokemonLeague[] = _("LIGUE POKéMON");
const u8 gText_PokemonCenter[] = _("CENTRE POKéMON");
const u8 gText_Coolness[] = _("Son sang-froid ");
const u8 gText_Beauty3[] = _("Sa beauté ");
const u8 gText_Cuteness[] = _("Sa grâce ");
const u8 gText_Smartness[] = _("Son intelligence ");
const u8 gText_Toughness[] = _("Sa robustesse ");
const u8 gText_SaveFailedCheckingBackup[] = _("Echec de la sauvegarde.\nVérification de la mémoire de\nsauvegarde… Veuillez patienter.\n{COLOR 4}“Durée nécessaire: 1 minute”");
const u8 gText_BackupMemoryDamaged[] = _("Mémoire de sauvegarde endommagée\nou pile interne vide. La progression\nne sera pas sauvegardée.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR 4}“Impossible de continuer à jouer.\nRetour à l'écran titre…”");
const u8 gText_CheckCompleted[] = _("Vérification terminée.\nSauvegarde en cours…\nVeuillez patienter.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Sauvegarde terminée.\n{COLOR 4}“Impossible de continuer à jouer.\nRetour à l'écran titre.”");
const u8 gText_SaveCompletePressA[] = _("Sauvegarde terminée.\n{COLOR 4}“Veuillez appuyer sur le bouton A.”");
const u8 gText_Ferry[] = _("FERRY");
const u8 gText_SecretBase[] = _("BASE SECRETE");
const u8 gText_Hideout[] = _("PLANQUE");
const u8 gText_ResetRTCConfirmCancel[] = _("Régler l'heure?\nA: Confirmer, B: Annuler");
const u8 gText_PresentTime[] = _("Heure actuelle du jeu");
const u8 gText_PreviousTime[] = _("Heure précédente du jeu");
const u8 gText_PleaseResetTime[] = _("Veuillez régler l'heure.");
const u8 gText_ClockHasBeenReset[] = _("L'horloge a été réglée.\nSauvegarde en cours…");
const u8 gText_SaveCompleted[] = _("Sauvegarde terminée.");
const u8 gText_SaveFailed[] = _("Echec de la sauvegarde…");
const u8 gText_NoSaveFileCantSetTime[] = _("Il n'y a pas de fichier de sauvegarde,\ndonc l'heure ne peut pas être réglée.");
const u8 gText_InGameClockUsable[] = _("Vous pouvez maintenant régler l'heure.");
const u8 gText_Spicy2[] = _("épicé");
const u8 gText_Dry2[] = _("sec");
const u8 gText_Sweet2[] = _("doux");
const u8 gText_Bitter2[] = _("amer");
const u8 gText_Sour2[] = _("aigre");
const u8 gText_Single[] = _("SOLO");
const u8 gText_Double[] = _("DUO");
const u8 gText_Knockout[] = _("KO");
const u8 gText_Mixed[] = _("MIXTE");
const u8 gText_First[] = _("premier prix");
const u8 gText_Second[] = _("deuxième prix");
const u8 gText_Third[] = _("troisième prix");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} est K.O…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} a survécu au poison.\nLe poison s'est dissipé!\p");
#endif
const u8 gText_Marco[] = _("MARCUS");
const u8 gText_TrainerCardName[] = _("NOM ");
const u8 gText_TrainerCardIDNo[] = _("NºID /");
const u8 gText_TrainerCardMoney[] = _("ARGENT");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" points");
const u8 gText_TrainerCardTime[] = _("DUREE JEU");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("CARTE DE DRESSEUR de {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("PANTHEON Nº 1");
const u8 gText_LinkBattles[] = _("COMBATS EN LINK");
const u8 gText_LinkCableBattles[] = _("COMBATS CABLE LINK");
const u8 gText_WinsLosses[] = _("V:{COLOR 4}{SHADOW 5}{STR_VAR_1}{COLOR 2}{SHADOW 3}  D:{COLOR 4}{SHADOW 5}{STR_VAR_2}{COLOR 2}{SHADOW 3}");
const u8 gText_PokemonTrades[] = _("ECHANGES DE POKéMON");
const u8 gText_UnionTradesAndBattles[] = _("ECHANGE UNION & COMBATS");
const u8 gText_BerryCrush[] = _("BROYEUR DE BAIES");
const u8 gText_WaitingTrainerFinishReading[] = _("En attente… L'autre DRESSEUR doit\nfinir de lire votre CARTE DE DRESSEUR.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S EN LINK");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR 2}{SHADOW 3}");
const u8 gText_WonContestsWFriends[] = _("CONCOURS EN LINK GAGNES");
const u8 gText_BattlePtsWon[] = _("POINT(S) DE COMBAT GAGNE(S)");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR 2}{SHADOW 3}Pco");
const u8 gText_BattleTower[] = _("TOUR DE COMBAT");
const u8 gText_WinsStraight[] = _("V/{COLOR 4}{SHADOW 5}{STR_VAR_1}{COLOR 2}{SHADOW 3} CONSEC./{COLOR 4}{SHADOW 5}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("TOUR DE COMBAT");
const u8 gText_BattleDome[] = _("DOME DE COMBAT");
const u8 gText_BattlePalace[] = _("PALACE DE COMBAT");
const u8 gText_BattleFactory[] = _("USINE DE COMBAT");
const u8 gText_BattleArena[] = _("DOJO DE COMBAT");
const u8 gText_BattlePike[] = _("REPTILE DE COMBAT");
const u8 gText_BattlePyramid[] = _("PYRAMIDE DE COMBAT");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} SOLO");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DUO");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Montrer");
const u8 gText_NoNeed[] = _("Pas besoin");
const u8 gText_AnnouncingResults[] = _("Annonce des résultats!");
const u8 gText_PreliminaryResults[] = _("Résultats du premier tour!");
const u8 gText_Round2Results[] = _("Résultats du second tour!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_2} de {STR_VAR_1} a gagné!");
const u8 gText_CommunicationStandby[] = _("Connexion en cours…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("MAJ.");
const u8 gText_Lower[] = _("min.");
const u8 gText_Others[] = _("OTHERS");
const u8 gText_Symbols[] = _("SYMBOLES");
const u8 gText_Register2[] = _("ENREG.");
const u8 gText_Exit2[] = _("RETOUR");
const u8 gText_QuitChatting[] = _("Quitter le tchat?");
const u8 gText_RegisterTextWhere[] = _("Où enregistrer le texte?");
const u8 gText_RegisterTextHere[] = _("Enregistrer le texte ici?");
const u8 gText_InputText[] = _("Entrer le texte.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} rejoint le tchat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} quitte le tchat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Départ du tchat…");
const u8 gText_LeaderLeftEndingChat[] = _("Le MENEUR, {DYNAMIC 0}, part\net met fin au tchat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Le texte enregistré a été modifié.\nSauvegarder la partie?");
const u8 gText_AlreadySavedFile_Chat[] = _("Ecraser les données de\nsauvegarde existantes?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SAUVEGARDE EN COURS…\nNE PAS ETEINDRE.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} a sauvegardé la partie.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Si le MENEUR part, le forum\nse termine. OK?");
const u8 gText_Hello[] = _("SALUT");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("ECHANGE");
const u8 gText_Battle[] = _("COMBAT");
const u8 gText_Lets[] = _("ÇA VA?");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("DESOLE");
const u8 gText_YaySmileEmoji[] = _("OUAIS{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("MERCI");
const u8 gText_ByeBye[] = _("BYE-BYE!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} vient de sortir de l'OEUF!");
const u8 gText_NicknameHatchPrompt[] = _("Voulez-vous donner un surnom\nau {STR_VAR_1} nouveau-né?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Sélectionnez une BAIE pour utiliser\nle BROYEUR DE BAIES.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Patientez le temps que tous les\nparticipants aient choisi une BAIE.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM}íÀVous terminez avec {STR_VAR_1} unités de\nfine POUDRE BAIE.{RESUME_MUSIC}\pVotre quantité totale de POUDRE\nBAIE est {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Sauvegarde de vos résultas en\ncours. Veuillez patienter.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Voulez-vous encore utiliser le\nBROYEUR DE BAIES?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Vous n'avez pas de BAIES.\nLa partie est annulée.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Un participant est parti. Le jeu\nva se terminer.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Le temps est écoulé.\pVous n'avez pas pu faire une\nbonne POUDRE BAIE…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Connexion en cours…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("BAIE {STR_VAR_1}");
ALIGNED(4) const u8 gText_TimeColon[] = _("Temps:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Vitesse:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Finesse:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" MIN ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" secondes");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" Fois/s");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Nº de pressages");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Résultats");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Finesse");
ALIGNED(4) const u8 gText_CoopRankings[] = _("En coopération");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Force du pressage");
ALIGNED(4) const u8 gText_BerryCrush2[] = _("BROYEUR DE BAIES");
ALIGNED(4) const u8 gText_PressingSpeedRankings[] = _("Vitesse du pressage");
ALIGNED(4) const u8 gText_Var1Players[] = _("{STR_VAR_1} JOUEURS");
const u8 gText_SymbolsEarned[] = _("Symboles");
const u8 gText_BattleRecord[] = _("Enregistrement");
const u8 gText_BattlePoints[] = _("Points de combat");
const u8 gText_UnusedCancel[] = _("CANCEL");
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Voir la CARTE de la ZONE DE COMBAT.");
const u8 gText_CheckTrainerCard[] = _("Voir la CARTE DE DRESSEUR.");
const u8 gText_ViewRecordedBattle[] = _("Voir le combat enregistré.");
const u8 gText_PutAwayFrontierPass[] = _("Quitter le PASSE ZONE.");
const u8 gText_CurrentBattlePoints[] = _("Vos points de combat actuels.");
const u8 gText_CollectedSymbols[] = _("Les symboles que vous avez collectés.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Tour de combat - Symbole capacité");
const u8 gText_BattleDomeTacticsSymbol[] = _("Dôme de combat - Symbole tactique");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Palace de combat - Symbole esprit");
const u8 gText_BattleArenaGutsSymbol[] = _("Dojo de combat - Symbole cran");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Usine de combat - Symbole savoir");
const u8 gText_BattlePikeLuckSymbol[] = _("Reptile de combat - Symbole chance");
const u8 gText_BattlePyramidBraveSymbol[] = _("Pyramide de combat - Symbole bravoure");
const u8 gText_ThereIsNoBattleRecord[] = _("Pas d'enregistrement.");
const u8 gText_BattleTower3[] = _("TOUR");
const u8 gText_BattleDome2[] = _("DOME");
const u8 gText_BattlePalace2[] = _("PALACE");
const u8 gText_BattleArena2[] = _("DOJO");
const u8 gText_BattleFactory2[] = _("USINE");
const u8 gText_BattlePike2[] = _("REPTILE");
const u8 gText_BattlePyramid2[] = _("PYRAMIDE");
const u8 gText_BattleTowerDesc[] = _("Eliminez vos adversaires pour aller\nau sommet et prouver votre talent.");
const u8 gText_BattleDomeDesc[] = _("Enchaînez les victoires en\nfaisant preuve de tactique.");
const u8 gText_BattlePalaceDesc[] = _("Regardez vos POKéMON se battre\net mettez votre esprit à l'épreuve.");
const u8 gText_BattleArenaDesc[] = _("Gagnez avec des équipes de POKéMON\npour prouver que vous avez du cran.");
const u8 gText_BattleFactoryDesc[] = _("Visez la victoire en louant des\nPOKéMON pour prouver votre savoir.");
const u8 gText_BattlePikeDesc[] = _("Choisissez un des trois chemins pour\ncombattre et testez votre chance.");
const u8 gText_BattlePyramidDesc[] = _("Partez à l'aventure et rendez-vous au\nsommet pour prouver votre bravoure.");
const u8 gText_Powder[] = _("POUDRE");
const u8 gText_BerryPickingRecords[] = _("RECORDS D'ATTRAPE-BAIES DODRIO");
const u8 gText_BerriesPicked[] = _("Baies attrapées:");
const u8 gText_BestScore[] = _("Meilleur score:");
const u8 gText_BerriesInRowFivePlayers[] = _("Baies attrapées à la suite\navec cinq joueurs:");
const u8 gText_BerryPickingResults[] = _("Annonce des résultats!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Annonce du classement!");
const u8 gText_AnnouncingPrizes[] = _("Remise des prix!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("La première place remporte\n1 {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Vous ne pouvez plus rien tenir!");
const u8 gText_FilledStorageSpace[] = _("Le prix est rangé à sa place.");
const u8 gText_WantToPlayAgain[] = _("Rejouer?");
const u8 gText_SomeoneDroppedOut[] = _("Quelqu'un est parti.\nLa connexion va se terminer.");
const u8 gText_SpacePoints[] = _(" points");
const u8 gText_CommunicationStandby3[] = _("Connexion en cours…");
const u8 gText_SpacePoints2[] = _(" points");
const u8 gText_SpaceTimes3[] = _("");
const u8 gText_PkmnJumpRecords[] = _("RECORDS DE SAUTS POKéMON");
const u8 gText_JumpsInARow[] = _("Sauts consécutifs:");
const u8 gText_BestScore2[] = _("Meilleur score:");
const u8 gText_ExcellentsInARow[] = _("EXCELLENTS consécutifs:");
const u8 gText_AwesomeWonF701F700[] = _("Score incroyable! Tu as\ngagné {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("Il n'y a plus de place.");
const u8 gText_CantHoldMore[] = _("Vous ne pouvez plus rien tenir!");
const u8 gText_WantToPlayAgain2[] = _("Rejouer?");
const u8 gText_SomeoneDroppedOut2[] = _("Quelqu'un est parti.\nLa connexion va se terminer.");
const u8 gText_CommunicationStandby4[] = _("Connexion en cours…");
const u8 gText_LinkContestResults[] = _("Résultats du concours link de {PLAYER}");
const u8 gText_1st[] = _("1{SUPER_ER}");
const u8 gText_2nd[] = _("2{SUPER_E}");
const u8 gText_3rd[] = _("3{SUPER_E}");
const u8 gText_4th[] = _("4{SUPER_E}");
const u8 gText_Friend[] = _("Friend");
const u8 gText_Pokemon3[] = _("POKeMON");
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Combats solo de {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Combats duo de {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Combats multi de {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Combats multi link de {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Tournois de combat solo de {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Tournois de combat duo de {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Combats solo de {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Combats duo de {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Combats hasard de {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("Tournoi K.O. de {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Combats échange solo de {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Combats échange duo de {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Combats quête de {PLAYER}");
const u8 gText_Lv502[] = _("N. 50");
const u8 gText_OpenLv[] = _("N. LIBRE");
const u8 gText_WinStreak[] = _("Victoires: {STR_VAR_1}");
const u8 gText_Current[] = _("ACTUEL");
const u8 gText_Record[] = _("RECORD");
const u8 gText_Prev[] = _("PRECED.");
const u8 gText_RentalSwap[] = _("Loc./Ech.");
const u8 gText_Total[] = _("Total");
const u8 gText_ClearStreak[] = _("Séries: {STR_VAR_1}");
const u8 gText_Championships[] = _("Championnats: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Salles: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Réussites: {STR_VAR_1}");
const u8 gText_KOsInARow[] = _("K.O.s: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Nombre: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Niveaux: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("NIVEAU 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("NIVEAU LIBRE");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Victoires: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Séries: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Salles: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("K.O.s: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Niveaux: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" et {STR_VAR_2} des POKéMON capturés\nsont inaptes");
const u8 gText_FrontierFacilityIncluding[] = _(".\pIncluant ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" sont inaptes");

const u8 gText_YesNo[] = _("OUI\nNON");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("PIKABOUH!");
const u8 gText_CommErrorCheckConnections[] = _("Erreur de communication…\nVeuillez vérifier toutes les connexions\npuis éteignez et rallumez les consoles.");
const u8 gText_CommErrorEllipsis[] = _("Erreur de connexion…");
const u8 gText_MoveCloserToLinkPartner[] = _("Rapprochez-vous de vos partenaires.\nEvitez tout obstacle entre vous.");
const u8 gText_ABtnRegistrationCounter[] = _("Bouton A: Comptoir d'enregistrement");
const u8 gText_ABtnTitleScreen[] = _("Bouton A: Ecran titre");
const u8 gText_NumPlayerLink[] = _("LINK {STR_VAR_1}J");
const u8 gText_BronzeCard[] = _("BRONZE");
const u8 gText_CopperCard[] = _("CUIVRE");
const u8 gText_SilverCard[] = _("ARGENT");
const u8 gText_GoldCard[] = _("OR");
const u8 gText_Day[] = _("JOUR");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("CONFIR.");
const u8 gText_Days[] = _("Jours");
const u8 gText_TimeColon2[] = _("Temps:");
const u8 gText_GameTime[] = _("Temps de jeu");
const u8 gText_RTCTime[] = _("Temps réel");
const u8 gText_UpdatedTime[] = _("Mise à jour");
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("SAC");
const u8 gText_MenuPokenav[] = _("POKéNAV");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("SAUVER");
const u8 gText_MenuOption[] = _("OPTIONS");
const u8 gText_MenuExit[] = _("RETOUR");
const u8 gText_MenuRetire[] = _("PARTIR");
const u8 gText_MenuRest[] = _("REPOS");
const u8 gText_MenuDexNav[] = _("NAVI-DEX");
const u8 gText_SafariBallStock[] = _("SAFARI BALLS\nNb: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALLS  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Pyramide\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Niveau 1");
const u8 gText_Floor2[] = _("Niveau 2");
const u8 gText_Floor3[] = _("Niveau 3");
const u8 gText_Floor4[] = _("Niveau 4");
const u8 gText_Floor5[] = _("Niveau 5");
const u8 gText_Floor6[] = _("Niveau 6");
const u8 gText_Floor7[] = _("Niveau 7");
const u8 gText_Peak[] = _("Sommet");
const u8 gText_LinkStandby2[] = _("Connexion en cours…\nBouton B: Annuler");
const u8 gText_PressAToLoadEvent[] = _("Bouton A: Charger évènement.\nBouton B: Annuler");
const u8 gText_LoadingEvent[] = _("Chargement évènement…");
const u8 gText_DontRemoveCableTurnOff[] = _("Ne pas retirer le câble Game Link.\nNe pas éteindre.");
const u8 gText_EventSafelyLoaded[] = _("Chargement de l'évènement achevé.");
const u8 gText_LoadErrorEndingSession[] = _("Erreur de chargement.\nFermeture de la session.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NATIONAL");
const u8 gText_PokedexDiploma[] = _("Joueur: {CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nPOKéDEX {STR_VAR_1}\nCe document certifie\nque vous avez complété\nvotre POKéDEX.\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR 4}{SHADOW 5}");
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} sera envoyé à {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Ciao, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} a envoyé {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Prends bien soin de {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("PV MAX.");
const u8 gText_Attack[] = _("ATTAQUE");
const u8 gText_Defense[] = _("DEFENSE");
const u8 gText_Speed[] = _("VITESSE");
const u8 gText_SpAtk[] = _("ATQ. SPE.");
const u8 gText_SpDef[] = _("DEF. SPE.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Echange de données…");
const u8 gText_RecordMixingComplete[] = _("Echange de données terminé.\nMerci d'avoir patienté.");
const u8 gText_RentalPkmn2[] = _("LOCATION");
const u8 gText_SelectFirstPkmn[] = _("Sélectionnez le premier.");
const u8 gText_SelectSecondPkmn[] = _("Sélectionnez le deuxième.");
const u8 gText_SelectThirdPkmn[] = _("Sélectionnez le troisième.");
const u8 gText_Rent[] = _("LOUER");
const u8 gText_Summary[] = _("RESUME");
const u8 gText_Others2[] = _("RETOUR");
const u8 gText_Deselect[] = _("ANNULER");
const u8 gText_TheseThreePkmnOkay[] = _("OK avec ces trois POKéMON?");
const u8 gText_Yes2[] = _("OUI");
const u8 gText_No2[] = _("NON");
const u8 gText_CantSelectSamePkmn[] = _("Impossible de sélec. le même.");
const u8 gText_PkmnSwap[] = _("ECHANGE");
const u8 gText_SelectPkmnToSwap[] = _("Choisir un PKMN à échanger.");
const u8 gText_SelectPkmnToAccept[] = _("Choisir un PKMN à recevoir.");
const u8 gText_Swap[] = _("ECHANGER");
const u8 gText_Summary2[] = _("RESUME");
const u8 gText_Rechoose[] = _("RETOUR");
const u8 gText_QuitSwapping[] = _("Quitter l'échange?");
const u8 gText_Yes3[] = _("OUI");
const u8 gText_No3[] = _("NON");
const u8 gText_PkmnForSwap[] = _("{PKMN} A ECHANGER");
const u8 gText_Cancel3[] = _("ANNULER");
const u8 gText_Swap2[] = _("SWAP"); // Unused
const u8 gText_Accept[] = _("ACCEPT"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accepter ce POKéMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Ce {PKMN} est déjà dans l'équipe.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("JOUEUR");
const u8 gText_SavingBadges[] = _("BADGES");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("DUREE JEU");
const u8 gText_WirelessCommStatus[] = _("Statut de la communication sans fil");
const u8 gText_PeopleTrading[] = _("Personnes pour échanges:");
const u8 gText_PeopleBattling[] = _("Personnes pour combats:");
const u8 gText_PeopleInUnionRoom[] = _("Personnes dans SALLE UNION:");
const u8 gText_PeopleCommunicating[] = _("Personnes en communication:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} JOUEURS");
const u8 gText_F701Players[] = _("{DYNAMIC 1} JOUEURS");
const u8 gText_F702Players[] = _("{DYNAMIC 2} JOUEURS");
const u8 gText_F703Players[] = _("{DYNAMIC 3} JOUEURS");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("CARTES MIRACLE");
ALIGNED(4) const u8 gText_WonderNews[] = _("INFOS MIRACLE");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("COMMUNICATION SANS FIL");
ALIGNED(4) const u8 gText_Friend2[] = _("AMI");
ALIGNED(4) const u8 gText_Exit3[] = _("RETOUR");
ALIGNED(4) const u8 gText_Receive[] = _("RECEVOIR");
ALIGNED(4) const u8 gText_Send[] = _("ENVOYER");
ALIGNED(4) const u8 gText_Toss[] = _("JETER");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Différents évènements seront\nimportés en transmission sans fil.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Lire les CARTES MIRACLE en\nvotre possession.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Lire les INFOS qui sont\narrivées.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Retourner à l'écran titre.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Vous n'avez pas de CARTE MIRACLE.\nUne nouvelle carte va être ajoutée.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Vous n'avez pas d'INFOS MIRACLE.\nDe nouvelles infos vont être ajoutées.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("D'où accéder à la CARTE MIRACLE?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("D'où accéder aux INFOS MIRACLE?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Transmission…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Fin de la connexion.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Erreur de transmission…");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("La connexion a été annulée.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Jeter la CARTE MIRACLE et\nentrer une nouvelle carte?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Vous n'avez pas encore reçu de carte\nen cadeau. Entrer une nouvelle carte?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Vous avez reçu une CARTE MIRACLE\nde {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Vous avez reçu un objet INFOS\nMIRACLE de {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Une nouvelle CARTE MIRACLE\na été reçue.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Un nouvel objet INFOS MIRACLE\na été reçu.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Un nouveau TAMPON a été reçu.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("Un nouveau DRESSEUR est arrivé.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Vous aviez déjà cette\nCARTE MIRACLE.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Vous aviez déjà cet objet\nINFOS MIRACLE.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Vous aviez déjà ce\nTAMPON.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Il n'y a plus de place pour\nde nouveaux TAMPONS.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Votre record a été transféré par\nCOMMUNICATION SANS FIL.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Vous ne pouvez pas accepter de\nCARTE MIRACLE de ce DRESSEUR.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Vous ne pouvez pas accepter\nd'INFOS MIRACLE de ce DRESSEUR.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Rien n'a été envoyé…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Que voulez-vous faire avec\nles CARTES MIRACLE?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Que voulez-vous faire avec\nles INFOS MIRACLE?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Envoi d'une CARTE MIRACLE…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Envoi des INFOS MIRACLE…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Votre CARTE MIRACLE a été\nenvoyée à {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Vos INFOS MIRACLE ont été\nenvoyées à {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("Un TAMPON a été envoyé à {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("Un CADEAU a été envoyé à {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("L'autre DRESSEUR a déjà la\nmême CARTE MIRACLE.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("L'autre DRESSEUR a déjà les\nmêmes INFOS MIRACLE.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("L'autre DRESSEUR a déjà le\nmême TAMPON.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("L'autre DRESSEUR a interrompu\nla communication.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Vous ne pouvez pas envoyer de\nCADEAU MYST. à ce DRESSEUR.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Si vous jetez la CARTE, son\névènement n'arrivera pas. OK?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Voulez-vous vous débarrasser\nde cet objet INFOS?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Vous n'avez pas reçu le\nCADEAU. Le jeter?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Sauvegarde en cours…\nVeuillez patienter.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Sauvegarde terminée.\nVeuillez appuyer sur le bouton A.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("CARTE MIRACLE jetée.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("INFOS MIRACLE jetées.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("CADEAU MYST.");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}CHOIX {A_BUTTON}OK {B_BUTTON}QUIT.");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}CHOIX {A_BUTTON}OK {B_BUTTON}QUIT.");
const u8 gText_PlayersBattleResults[] = _("RESULTATS COMBATS de {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("RESULTATS V/{STR_VAR_1} D/{STR_VAR_2} EG/{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 80}VICT.{CLEAR_TO 128}DEF.{CLEAR_TO 176}EGAL.");
const u8 gText_CommunicationStandby5[] = _("Connexion en cours…");
const u8 gDaycareText_GetAlongVeryWell[] = _("Ils ont l'air de très bien\ns'entendre.");
const u8 gDaycareText_GetAlong[] = _("Ils ont l'air de s'entendre.");
const u8 gDaycareText_DontLikeOther[] = _("Ils ont l'air de ne pas s'aimer.");
const u8 gDaycareText_PlayOther[] = _("Ils préfèrent jouer avec d'autres\nPOKéMON plutôt qu'ensemble.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("RETOUR");
const u8 gText_Lv[] = _("N.");
const u8 gText_TimeBoard[] = _("PANNEAU DES TEMPS");
const u8 gText_TimeCleared[] = _("TEMPS ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s");
const u8 gText_TrainerHill1F[] = _("RC");
const u8 gText_TrainerHill2F[] = _("1{SUPER_ER}");
const u8 gText_TrainerHill3F[] = _("2{SUPER_E}");
const u8 gText_TrainerHill4F[] = _("3{SUPER_E}");
const u8 gText_TeachWhichMoveToPkmn[] = _("Enseigner quelle {STR_VAR_3}\nà {STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Enseigner {STR_VAR_2}?");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("Enseigner {STR_VAR_2}?\nCela va utiliser une {STR_VAR_3}.");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} apprend\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} tente d'apprendre\n{STR_VAR_2}.\pMais {STR_VAR_1} ne peut pas ap-\nprendre plus de 4 capacités.\pEffacer une capacité \npour {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Arrêter d'apprendre\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 {PAUSE 15}…\n{PAUSE 15}… {PAUSE 15} …{PAUSE 15} {PLAY_SE SE_BALL_BOUNCE_1}Tadaa!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} oublie\n{STR_VAR_3}.\pEt…\p{STR_VAR_1}\napprend {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Arrêter d'enseigner la nouvelle\ncapacité à {STR_VAR_1}?");
const u8 gText_MoveRelearnerStop[] = _("Arrêter d'enseigner de nouvelles\ncapacités à {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Oublier quelle capacité?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("CAPACITES COMB.");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("CAPACITES CONC.");
const u8 gText_MoveRelearnerType[] = _("TYPE/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("POUV./");
const u8 gText_MoveRelearnerAccuracy[] = _("PRECIS./");
const u8 gText_MoveRelearnerAppeal[] = _("CHARME/");
const u8 gText_MoveRelearnerJam[] = _("BLOCAG./");
const u8 gText_ClearAllSaveData[] = _("Effacer toutes les données?");
const u8 gText_ClearingData[] = _("Effacement des données en cours…\nVeuillez patienter.");
const u8 gText_IsThisTheCorrectTime[] = _("Est-ce la bonne heure?");
const u8 gText_Confirm3[] = _("CONFIR.");
const u8 gText_Cancel4[] = _("SORTIR");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Communication en attente du\nchoix d'un participant.");
const u8 gText_BattleWasRefused[] = _("Le combat a été refusé.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("A refusé le combat.{PAUSE 60}");
const u8 gText_NoWeather[] = _("RIEN"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SOLEIL"); // Unused
const u8 gText_Sunny2[] = _("SOLEIL2"); // Unused
const u8 gText_Rain[] = _("PLUIE"); // Unused
const u8 gText_Snow[] = _("NEIGE"); // Unused
const u8 gText_Lightning[] = _("ECLAIR"); // Unused
const u8 gText_Fog[] = _("BROUILLARD"); // Unused
const u8 gText_VolcanoAsh[] = _("CENDRES"); // Unused
const u8 gText_Sandstorm[] = _("TEMPETE SABLE"); // Unused
const u8 gText_Fog2[] = _("BROUILLARD2"); // Unused
const u8 gText_Seafloor[] = _("MER"); // Unused
const u8 gText_Cloudy[] = _("NUAGEUX"); // Unused
const u8 gText_Sunny3[] = _("SOLEIL3"); // Unused
const u8 gText_HeavyRain[] = _("FORTE PLUIE"); // Unused
const u8 gText_Seafloor2[] = _("MER2"); // Unused
const u8 gText_DelAll[] = _("TOUT EF.");
const u8 gText_Cancel5[] = _("ANNULER");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("REPONSE");
const u8 gText_PokeBalls[] = _("POKé BALLS");
const u8 gText_Berry[] = _("BAIE");
const u8 gText_Berries[] = _("BAIES");
const u8 gText_ExpShareOn[] = _("Le Multi Exp est activé.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Le Multi Exp est désactivé.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("SPECTRE");
const u8 gText_Boulderbadge[] = _("BADGE ROCHE");
const u8 gText_Cascadebadge[] = _("BADGECASCADE");
const u8 gText_Thunderbadge[] = _("BADGE FOUDRE");
const u8 gText_Rainbowbadge[] = _("BADGE PRISME");
const u8 gText_Soulbadge[] = _("BADGE AME");
const u8 gText_Marshbadge[] = _("BADGE MARAIS");
const u8 gText_Volcanobadge[] = _("BADGE VOLCAN");
const u8 gText_Earthbadge[] = _("BADGE TERRE");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("CHEN: Il est important de bien\nconnaître ses POKéMON.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("C'est une liste de tes POKéMON,\n{PLAYER}.\pConsulte-la pour voir les\ncompétences de tes POKéMON.\pChoisis aussi POKéMON si tu\nveux donner un objet à l'un d'eux.");
const u8 gText_Eleve[] = _("ELEVE");
const u8 gText_Dresseur[] = _("DRESSEUR");
const u8 gText_Champion[] = _("CHAMPION");