ThreeIsland_House2_Frlg_MapScripts::
	.byte 0

ThreeIsland_House2_EventScript_Man::
	lock
	faceplayer
	famechecker FAMECHECKER_SABRINA, 1
	msgbox ThreeIsland_House2_Text_IAdmireSabrina
	release
	end

ThreeIsland_House2_EventScript_Rocker::
	msgbox ThreeIsland_House2_Text_CantMakeThisSpoonBend, MSGBOX_NPC
	end

ThreeIsland_House2_Text_CantMakeThisSpoonBend::
	.string "Ouarrrrgh…\n"
	.string "Gniiiiiiiiiiiiiii…\p"
	.string "Impossible… J'arrive pas à plier\n"
	.string "cette cuillère avec mon esprit.$"

ThreeIsland_House2_Text_IAdmireSabrina::
	.string "T'as entendu parler d'une fille\n"
	.string "CHAMPION d'ARENE de SAFRANIA?\p"
	.string "Elle utilise des POKéMON PSY,\n"
	.string "c'est bien ça?\p"
	.string "C'est le genre de personne que\n"
	.string "j'admire vraiment.\p"
	.string "Et en plus, elle est super\n"
	.string "mignonne.$"

