FiveIsland_House1_Frlg_MapScripts::
	.byte 0

FiveIsland_House1_EventScript_Woman::
	msgbox FiveIsland_House1_Text_HusbandWentOffFishing, MSGBOX_NPC
	end

FiveIsland_House1_Text_HusbandWentOffFishing::
	.string "Ne t'inquiète pas pour le dîner\n"
	.string "de ce soir!\p"
	.string "C'est ce que m'a dit mon mari\n"
	.string "en partant pêcher ce matin.\p"
	.string "Mais je ne sais pas si je peux\n"
	.string "lui faire confiance là-dessus.$"

