OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
	.string "Le temps est parfait. Rien de\n"
	.string "mieux pour un combat.$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "Aiyeeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "Non, pas le visage!! Je ne veux\n"
	.string "pas abîmer mon maquillage.$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "Je vais finir par attraper un coup\n"
	.string "de soleil…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "Oh, tu sais te battre toi!$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "J'aime beaucoup ta casquette.\n"
	.string "Je m'en achèterais bien une…$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "D'ici, on peut voir les tours du\n"
	.string "MONT BRAISE aller jusqu'au ciel.$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "J'en tombe à la renverse!$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "Le ciel est vraiment immense.$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "Il fallait que je tombe sur toi\n"
	.string "juste pendant ma pause.$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "Hein? Que…\n"
	.string "Quelle claque!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "Au lieu d'utiliser SURF tout le\n"
	.string "temps, tu ferais bien de nager.$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "Attends! Bouge pas!\n"
	.string "J'en tiens un gros!$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "Je l'ai encore laissé filer!$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "Non seulement je perds, mais en\n"
	.string "plus je laisse filer ma prise!$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "Tu pourrais pas m'aider un peu\n"
	.string "avec mon entraînement?$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "J'y étais presque.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "Hum, tu mérites tout mon respect.$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "Il ne se passe pas une journée\n"
	.string "sans qu'on s'entraîne.$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "Quelle idiote je fais!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "A partir de maintenant, je vais\n"
	.string "m'entraîner encore plus!$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "Tous les jours avant le pt'it déj,\n"
	.string "je fais le tour de l'île à la nage.$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "Gasp…\n"
	.string "Gasp…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "J'ai perdu parce que j'ai\n"
	.string "trop couru avant.$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "C'est pas une tenue pour le\n"
	.string "combat, ça!! Tu me fais honte!$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "Pourquoi??$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "Même les vrais guerriers font\n"
	.string "attention à leur tenue aujourd'hui.$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "Tu sais, rien de mieux que de\n"
	.string "se retrouver en pleine nature.$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "Aïe! Ça fait mal!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "L'eau des régions volcaniques\n"
	.string "est très bonne pour la santé.$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "Après un petit repas, rien de tel\n"
	.string "qu'un combat pour digérer.$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "Ça donne soif tout ça.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "Qu'est-ce que je dois faire?\n"
	.string "Je suis morte de faim.$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "KIA: Mon grand frère et moi, on\n"
	.string "fait une super équipe.$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "KIA: Hein?!\n"
	.string "J'arrive pas à le croire!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "KIA: Je ne pensais pas que mon\n"
	.string "frère pouvait se faire battre.$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "KIA: Si tu veux te battre contre\n"
	.string "nous, alors il te faut au moins\l"
	.string "deux POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "MIK: Avec ma sœur à mes côtés,\n"
	.string "je n'ai peur de rien!$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "MIK: Wouah!\n"
	.string "Trop fort!$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "MIK: Comment as-tu fait pour\n"
	.string "battre notre super duo?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "MIK: Hé, tu veux vraiment te\n"
	.string "battre contre nous?\p"
	.string "Alors tu vas devoir revenir\n"
	.string "avec au moins deux POKéMON.$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "C'est la ROUTE TISON.\p"
	.string "Le MONT BRAISE se trouve\n"
	.string "au bout.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "Enflammez votre cœur!\n"
	.string "SOURCE BRAISE$"

